### ISSUE TITLE
Find-DbaAgentJob add parameter to filter on step type

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#1002]
### Is this a *feature* OR *bug*:

**Feature**

We have the ability to search on step name, but in an enterprise environment not many are going to keep up with the step name of every job that could be running. 

Use case: I need to find jobs that are running SSIS packages. There are only 2 step types that could be used to call an SSIS package: Operating System (CmdExec) or SQL Server Integration Services Package (for 2012+).

Addition to 2012+ you can also call SSIS packages via T-SQL if SSISDB catalog is on the server, but not sure trying to find jobs that run a specific T-SQL statement would be an efficient search.

**Comment by niphlod** [comment]
this would probably need a bit of rework. we have *agentstep* function that deal with agent steps, and introduced within find-dbaagentjob the ability to search for steps.... we would need a find-dbaagentjobstep at this point more than introducing a feature on the "parent" ... Also, dunno if the requirement still stands because right now you can do `Get-DbaAgentJobStep -Sqlinstance foo | Where SubSystem -in @('ssis', 'cmdexec')` and get what you need. @wsmelton : thoughts ?

**Comment by wsmelton** [comment]
From need I would say it is still there as it was asked about today, mind you for the copy command:

```
bendy22 [11:36 AM]

Wanting to migrate all Agent jobs related to SSRS. I can see they all have the Category "Report Server", however Copy-DbaAgentJob doesn't seem to have a -Category parameter. Thoughts?
```

**Comment by niphlod** [comment]
that's about copy, and category.  find-dbaagentjob has the -Category parameter.... this issue was about job *steps* and their type

**Comment by wsmelton** [comment]
True dat. We can just close this one.
