### ISSUE TITLE
3rd party backup/restore support

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1035]
### Is this a *feature* OR *bug*:

feature

### Details

Investigate support for 3rd party restore products, like LiteSpeed (never used it so have 0 clue how it works)

**Comment by nocentino** [comment]
Generally speaking the 3rd party vendors call an extended stored procedure for their restore processes. Set the parameters correctly and you're good.   I have some pretty good experience with Redgate's SQL Backup if you need some assistance.  Which cmdlets would you want to add this feature to?

**Comment by Stuart-Moore** [comment]
Best to split out as a separate function called via a switch from the main
functions so its all once piece. Also easier to fix if they change
something.

Nocentino - could use provide an example of how the redgate one would work
with t-sql to scan headers and then restore a full, diff and logs please?

**Comment by nocentino** [comment]
The code below does just what you described, it will search the backup paths and generate the restore based on newest point in time backup building the appropriate restore sequence.  There's also an option to restore up to a defined point in time.  Check out this for more details - https://documentation.red-gate.com/display/SBU7/Scripting+SQL+Backup+Pro
```
EXECUTE master..sqlbackup '-SQL "RESTORE DATABASE [database1] 
FROM DISK = ''\\server1\dbserver1\database1\FULL\*.sqb'' ,
            DISK = ''\\server1\dbserver1\database1\DIFF\*.sqb'' ,
            DISK = ''\\server1\dbserver1\database1\LOG\*.sqb''
            SOURCE = ''database1'' LATEST_ALL WITH NORECOVERY, DISCONNECT_EXISTING, REPLACE"'

```

**Comment by Stuart-Moore** [comment]
Thanks. 
Been sketching out some ideas for this (pencil and paper, going old skool ;) ). Don't want to make things too complicated for the core functionality with lots of branching, etc. So considering have a seperate set of functions to handle this. Looks a lot less complicated than our stuff as it handles the filtering for us. 
But they don't cope with multiple dbs at one time, so we may need to read headers to split them to the restore statements that way.

Though it seems to used msdb..backupset to store history, so Get-DbaBackupHistory should still work ok. So maybe we could offer a close enough experience, but not all the goodies

**Comment by wsmelton** [comment]
@potatoqualitee (nice name) I have the experience with Dell's Litespeed (LS) for SQL Server and it would be difficult to support this.

1) they are proprietary backups (not native SQL Server format), you can only read them using LS procedures or CLI utilities.
2) They now support writing directly to AWS S3 storage, which in order to read those backups using LS you have to pass in the secret key for the S3 storage access. A minor thing for some but would encourage placing secret access keys in plain text scripts for automation.
3) If LS is not installed on the instance you can't even touch the backup files to restore them. You can install LS on a given server to restore, but once you start taking backups it requires a license (just as an FYI for folks).

**Comment by Stuart-Moore** [comment]
I think the decision on this one was that we couldn't support this unless we could get free full copies for all the devs as otherwise we can't test and keep up with their releases. I for one wouldn't want to be the only one to have the apps, and don't have access to any of them without being given them
