### ISSUE TITLE
Test-DbaHadrSyncCommit

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1037]
## Is this:

- [x ] *feature* post 1.0
- [ ] *bug*:

## Details
Can this, including explanations, be turned into a command? Should it?

https://blogs.msdn.microsoft.com/sql_server_team/troubleshooting-high-hadr_sync_commit-wait-type-with-always-on-availability-groups/

**Comment by wsmelton** [comment]
The Tiger Team's GitHub repo already has scripts for troubleshooting the concept in that article. It includes T-SQL scripts to create the XE session, load it into a table, and a PowerBI report to run against the table.

The XE session created in both is not something you would just leave running in a production environment. It would depend on how you would want to implement it, because reading XEL files are very resource intensive (mostly CPU and IO). As well, if that session is run long enough then trying to read all of that into PowerShell will be tricky to deal with for performance. (Dealing with this now at a client).

**Comment by wsmelton** [comment]
I don't see this as being something to implement as there are a ton of variables to deal with and it would not perform efficiently to make it worth the time. Tiger Team's repo has a full script and Power BI report with other tooling that can be used for checking issues with replication on AGs.
