### ISSUE TITLE
Export-sqlLogin

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#1056]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x ] *feature* 
- [ ] *bug*:

## Details

Function Export-sqlLogin does not consider the principal specific permissions. This is considered on the Export-sqlUser. I think this is a required feature as it will help to mimic all the actual permissions the login has.

**Comment by wsmelton** [comment]
@mvillegascuellar Can you give an example of what you are referring to by:
> principal specific permissions

Just so it is clear to the individual that works on this issue.

**Comment by mvillegascuellar** [comment]
Sure, when the login has an associated user that  has specific principal permissions rather than role based permissions, those are not exported when using the export-sqlLogin. However if I export the user (export-sqlUser), it does export those specific principal permissions. I think the export-sqlLogin should contain the export-sqlUser functionality.

**Comment by wsmelton** [comment]
The Export-SqlLogin should not export anything specific to a database user beyond what you see in the login properties in SSMS. The functionality of the login and user functions were separated in this way by design.

I believe most folks combine the two commands to get the desired outcome you are wanting. However, we can certainly work on a wrapper function that would do that (Export-DbaLoginUser ?). As of now though I am not aware of this being considered (no current issues or PRs).
