### ISSUE TITLE
Export-SqlLogin 2008< compatability

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1088]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details
user reported  "I tried Export-SQLLogin. It seems to use commands that not works in SQL 2008 R2 and older. (it users ALTER SERVER ROLE, but in SQL 2008 R2 it is sp_addsrvrolemember)."

There's actually a thing in the SMO scripter (if SMO is used in this export, unsure) where you can set an option for the destination SMO version! so crazy cool.

**Comment by niphlod** [comment]
unfortunately SMO is not in the picture for this

**Comment by niphlod** [comment]
BTW: at SOME point, this and export-sqluser should collapse into one or be better separated. export-sqluser already solves the issue using SMO correctly.

**Comment by ClaudioESSilva** [comment]
With the latest version (0.9.151) the ALTER SERVER ROLE is addressed (PR: https://github.com/sqlcollaborative/dbatools/pull/2998).
Because this command needs a little trick with the SID and HASH, it's not straightforward to implement everything with SMO like Export-DbaUser.

For now, I think as it is is the best balance!

@potatoqualitee if you agree please close this issue

**Comment by potatoqualitee** [comment]
That works thank you!
