### ISSUE TITLE
Copy-SqlJob does not copy maintenance plans

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#126]
If you are dealing with maintenance plans (not custom SSIS packages) for a given instance the cmdlet is only copying the job definition, not the actual maintenance plan.

Do we want cmdlet for copying maintenance plans or include T-SQL to copy msdb.dbo.sysssispackages (just maintenance plans) to destination. Other option would be to look at using SMO for SSIS to export the packages, but T-SQL likely going to be much less painful. Possibly this code: http://dba.stackexchange.com/a/112434/507

**Comment by ctrlbold** [comment]
Hey Shawn, I didn't realize it was bringing over even parts of maintenance plans. I chose not to address maintenance plans because it seemed like such a PITA. I like the idea of T-SQL! I didn't realize it would be that easy. One thing about the code that I'd change is I would do the replace of source with destination in PowerShell itself because that's what all of the other scripts do. It's similar to this:

$sql = $sql -replace [Regex]::Escape("'$source'"), [Regex]::Escape("'$destination'")

If you would like to tackle this, that'd be awesome. If not, let me know and I'll add it to the list.

**Comment by wsmelton** [comment]
Understood. I will give it a shot.

**Comment by wsmelton** [comment]
So building out the query to move the `ownersid` and `packagedata` which are both `varbinary()` data types is showing to be troublesome. PowerShell obviously is converting them both to `byte[]`, and I'm a bit lost finding a way to properly convert it back into `varbinary` for the INSERT statement to the target.

Short of that I have this code done I think.

**Comment by ClaudioESSilva** [comment]
Shawn please see if the first response to this question helps. http://stackoverflow.com/questions/1064121/how-do-i-insert-a-byte-into-an-sql-server-varbinary-column
Try to use a parameterized query.

**Comment by wsmelton** [comment]
Was able to figure it out, but used the PowerShell way of .NET. I was hoping an easier way (less code) was possible but couldn't find anything.
