### ISSUE TITLE
[DbaInstanceParameter] enahancements

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1362]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

##  Details
[DbaInstanceParameter]"sql2016"

I'd like this to result in : 

```
ComputerName    : sql2016
InstanceName    : MSSQLSERVER
Port            : 1433
FullName        : sql2016
FullSmoName     : sql2016
SqlComputerName : [sql2016]
SqlInstanceName : [MSSQLSERVER]
SqlFullName     : [sql2016]
Type            : Default
LinkedLive      : False
LinkedServer    :
InputObject     : sql2016

```

Notice an empty instance name will be MSSQLSERVER and default port of 1433 (even though I think we discussed it and this may not be a good idea)

**Comment by FriedrichWeinmann** [comment]
Do you seriously want me to put in a port number when we cannot make any assumption of validity for it?
The default instance could be running under port 666 for all we know ...
Making a null-instance be `MSSQLSERVER` is trivial though.

Adding more feature to this list though:
 - Should support protocols as part of the input and as property on the output
 - Should support ping results as input
 - Should support dns resolutions as input
 - Should support the output of `Get-ADComputer` as input

**Comment by potatoqualitee** [comment]
If the port for the default instance is changed, it must be specified when connecting remotely. Try on garbo, I changed the port for sql2008 to 777.

**Comment by niphlod** [comment]
Am I the only one to prefer "hostname" to "computername" here?
An instance is not bound to a computer in a lot of cases.
For the "Port number" I tend to stick with fred here: if UDP is available
it's generally not needed to specify a port (and in several setups it's
even dynamic, that's the point of having a running "sql server browser
servir")



Il 30 mag 2017 10:53 PM, "Chrissy LeMaire" <notifications@github.com> ha
scritto:

If the port for the default instance is changed, it must be specified when
connecting remotely. Try on garbo, I changed the port for sql2008 to 777.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/1362#issuecomment-305004821>,
or mute the thread

**Comment by FriedrichWeinmann** [comment]
Heya niph.
Actually, for me it's a naming habit that comes from other powershell modules. Commands that may be targeting clusters will still use the parameter name "ComputerName".
If you really want to have it, I can add a property alias for Hostname (or vice versa, I suppose).

I just did some verification on Chrissy's proposal and discussed it with her (kinda forgot to add it to the issue, sorry):
We'll only add that port when targeting the default instance over an IP protocol:
 - The browser service is never used for the default instance
 - By default, localhost will used named pipes instead.

Additional features I think I'll add:
 - Include "." to validate as localhost.
 - Add property: `IsLocalHost`

**Comment by FriedrichWeinmann** [comment]
Implemented in:
https://github.com/sqlcollaborative/dbatools/pull/1381
