### ISSUE TITLE
-MaintenanceSolutionBackup switch not working as expected

### ISSUE THREAD

**Issue by imbrian21** [sqlcollaborative/dbatools#1458]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

## System Details

- Operating system name and version: Windows 10
- Output from `$PSVersionTable`: 
PSVersion                      5.0.10586.672
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

- Output of dbatools version:
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.8.957    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy...
Script     0.8.957    dbatools                            {Start-SqlMigration, Copy-SqlDatabase, Copy-SqlLogin, Copy...

```

- SQL Server version for source/target - SQL 2016 SP1

#### Example:
1. Created database/object/files/etc - Restoring a backup directory from disk using the Maintenancesolutionbackup switch.
2. Run Command:
```powershell
restore-dbadatabase -sqlserver SERVERNAME -path BACKUPDIR -MaintenanceSolutionBackup 
```
3. WARNING: Get-OlaHRestoreFile - Don't have a FULL folder
```

## Action Results
Restore script doesnt comb through all DB folders in the subdirectory. If you specify a database name it will restore the backups as expected.

## Expected Results
#### Example:
1. Created database/object/files/etc - restore-dbadatabase
2. Run Command:
```powershell
restore-dbadatabase -sqlserver SERVERNAME -path BACKUPDIR -MaintenanceSolutionBackup
```
3. Receive following output (if applicable)
```powershell
SqlInstance            : SERVERNAME
DatabaseName           : DBA_Maintenance
DatabaseOwner          : SA
NoRecovery             : False
WithReplace            : False
RestoreComplete        : True
BackupFilesCount       : 1
RestoredFilesCount     : 2
BackupSizeMB           :
CompressedBackupSizeMB :
BackupFile             : BACKUPPATH
RestoredFile           : DBA_Maintenance.mdf,DBA_Maintenance_log.ldf
RestoreDirectory       : C:\SQL\Data,C:\SQL\Log
Script                 : {RESTORE DATABASE [DBA_Maintenance] FROM  DISK = N'PATH' WITH  FILE = 1,  MOVE
                         N'DBA_Maintenance' TO N'C:\SQL\Data\DBA_Maintenance.mdf',  MOVE N'DBA_Maintenance_log' TO
                         N'C:\SQL\Log\DBA_Maintenance_log.ldf',  NOUNLOAD,  STATS = 1}

```

## Attached screen shots/console output

- Use of Start-Transcript can help collection of console output and exceptions
- Provide screen shots of the output from your console if available.
![image](https://user-images.githubusercontent.com/29493041/27289073-a7c098e0-54d6-11e7-8d65-88c18558ca86.png)

![image](https://user-images.githubusercontent.com/29493041/27288901-2ab5e4d6-54d6-11e7-9b0e-5f780a3b4378.png)

### Import - Attach dbatools logs
- Latest release of dbatools now includes a messaging and logging system. You can find this information via the `Get-DbaConfig` function. Use of the Set-DbaConfig controls the configuration of the system.
- Ensure this returns **true**: `(Get-DbaConfig -Name errorlogenabled).value`
- Locate the log path for the error logs using this command: `(Get-DbaConfig -Name dbatoollogpath).Value`
- **Attach the latest xml and log files found in the path shown.**

**Comment by Stuart-Moore** [comment]
Hi,
This is by design

Recursing down multiple Ola style backup folders doesn't make any sense, you might as well use the DirectoryRecurse switch instead. The idea of the MaintenanceSolutionBackup option was that we could work with a known quantity and shortcut some of the checking (ie; no need to check anything other than FULL, DIFF, LOG folders in the root.). Also drops out quicker if it finds a folder missing a FULL folder, the function actually stops runnnig the first time this happens, again by design.

But it will take an array/object of folders and then push through them:

restore-dbadatabase -sqlserver SERVERNAME -path (Get-ChildItem BACKUPDIR) -MaintenanceSolutionBackup

or
$folders = Get-ChildItem $BackupDir
restore-dbadatabase -sqlserver SERVERNAME -path $folders -MaintenanceSolutionBackup

or

Get-ChildItem $BackupDir | restore-dbadatabase -sqlserver SERVERNAME  -MaintenanceSolutionBackup

Assuming $BackupDir is the folder containing the top level db backup folders.
