### ISSUE TITLE
Various potential new commands from github repo

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1472]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Details

https://github.com/MichelleUfford/sql-scripts

**Comment by wsmelton** [comment]
Oh, her script on SQL Agent status is awesome...been using that one for years. It would be awesome to see the Get-DbaAgentJob expanded to include similar output.

**Comment by jpomfret** [comment]
I can look at incorporating some of the schedule/last execution info into Get-DbaAgentJob, that would for sure be useful.

**Comment by wsmelton** [comment]
Well, last execution would be more fitting in [Get-DbaJobHistory](https://github.com/sqlcollaborative/dbatools/pull/1464) which was just added.

**Comment by PowerDBAKlaas** [comment]
The lastexecution and the like are properties of the AgentJob object, and the Get-DbaAgentJob function already returns them!

The jobschedules are totally different things and don't belong in the Get-DbaAgentJob function.

In JobHistory, the user can | sort and | where and ... to get the latest execution in general, of a specific agent job, the last succeeded, and so on.
Also, JobHistory may be purged and miss lastexecution of certain jobs.

**Comment by wsmelton** [comment]
Can you then expand Get-DbaJobHistory to include the same items that are in Michelle's script?

This is an example of the output I build from her script in my assessment script:
![image](https://user-images.githubusercontent.com/11204251/27482494-59d2d3b4-57e7-11e7-83c1-534a3e1b0f61.png)

**Comment by PowerDBAKlaas** [comment]
Only the ..count columns come from jobhistory, and this is a history table subject to settings concerning purging.
The others are job properties and schedule properties.
we already have all of them, but maybe not combined.
`Get-DbaAgentJob | select *`
`Get-DbaAgentSchedule | select *`

the AgentJob.JobSchedules collection needs to be joined to the AgentSchedule.Name and the counts are aggregates from jobhistory, grouped by result and joined to the job on jobid.

This table will be incorrect if a job has multiple schedules, because those aggregate rows will become a one to many, and the counts will appear multiple times.

As for [Enabled], there is Job.enabled and schedule.enabled.

@sanderstad and @DevOpsFu may have a solution ready.

If not, I think we can build a new script to get those results, because we need to have a lean and fast Get- for those 3 objects separately.

**Comment by wsmelton** [comment]
I would agree in keeping the Get commands separate, but we need to offer a method that either (1) lets a user join the output together to build a full report or (2) build out a wrapper function to do it for them.

Maybe a `Get-DbaSqlAgent` that includes a switch for `Jobs`. Certain cases we need to be able to pull the Agent properties, but others I just want all the jobs configured along with the schedules an such associated with each one. That may be to big to handle on our side in one command, but we should provide an easy method (or set of commands) that does.

**Comment by PowerDBAKlaas** [comment]
Those "wrapper" scripts are my favourites 😄 
like a second layer that bundles the power of multiple functions, that's what gives so much added value.
Only, there are so much possibilities: drill down reports, excel tabs, write-host with colors, write to a database with normalized design (I do that daily), ....
I've done some things like that in scripts, in blog posts like [computerinfo](https://www.powerdba.eu/powershell-for-the-dba/computerinfowrapper) , but I think not everything should be a function.

We've raised the idea of a script repository a few times before.
Wouldn't this be more suitable for someting like that?

**Comment by wsmelton** [comment]
Well I need to grab this type of info for up to hundreds of servers when doing client reviews. So  if it is not added to dbatools I'll just add it to my repo.

**Comment by wsmelton** [comment]
This was not approved to incorporate into the job commands we already have so will it be created as a new maybe `Invoke` command, or just close this request?
