### ISSUE TITLE
Get-DbaMaintenanceSolutionLog Error

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1602]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x] *bug*:

#### Example:
When running the command with one instance I get these many errors.  I validated that I have data in my CommandLog for backups and index routine runs.

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27924779-11f27e1c-6248-11e7-881e-c6edce57bc5c.png)

### Import - Attach dbatools logs

![image](https://user-images.githubusercontent.com/169602/27924796-22f510d0-6248-11e7-97a6-7de7bc4d195b.png)

**Comment by niphlod** [comment]
I think the most beneficial thing would be to attach here a log that shows the error. With a -Verbose you can inspect what particular file is giving issues.

**Comment by niphlod** [comment]
cc @PowerDBAKlaas : if you don't get a shot at it, I'd go with a try/catch here, at least to suppress the red doom ^_^

**Comment by niphlod** [comment]
huh, stop that. I can reproduce too. Will try to fix it ASAP.

**Comment by niphlod** [comment]
Found. It breaks when reading files that contain reading statistics update.
Since the cmdlet is quite a "raw experiment", I'd say let's wait for @PowerDBAKlaas, probably he already has a "plan" to make this better.

If you put this piece after the index parsing, everything clicks but the property object returned is different (mainly because of all the details parsed from the "Comment" line). 
Some of those are not even logged in the "CommandLog" table this cmdlet wants to be a substitute of ^_^
Backfilling each property, since they're built at runtime, doesn't seem a proper solution either.... 

```
if ($line -match '^Command: UPDATE STATISTICS \[(?<database>[^\]]+)\]\.\[(?<schema>[^]]+)\]\.\[(?<table>[^\]]+)\] \[(?<stat>[^\]]+)\]') {
	$index = $db.Clone()
	$index['Index'] = $null
	$index['Statistics'] = $Matches.stat
	$index['Schema'] = $Matches.Schema
	$index['Table'] = $Matches.Table
	$index['action'] = $Matches.action
	$index['options'] = $Matches.options
	Write-Message -Level Verbose -Message "Stat $($index.Statistics) on Table $($index.Table) in Database $($index.Database) on $computername"
}
``` 

instead of breaking everything standing on top of this cmdlet with a PR to fix the reddy blood message, I humbly suggest (for the future):
 - Get-DbaMaintenanceSolution is too generic: ola is famous for backup, check_db and indexes, and each has its log file. This targets indexoptimize's log only ... either it takes a "logtype" and we add the parsing bit down the line or the cmdlet needs a namechange
 - add a -Since parameter (hi, I'm an alcoholic and I like to have 54k IndexOptimize_ files in my dir)
 - add a -Path parameter
 - standardize returned properties
 - either manage everything on indexoptimize (which counts for indexes AND statistics)  or discard statistics alltogether (but, alas, the cmdlet would need a rename to Get-DbaOlaIndexOptimizeLogJustForTheIndexPart 😵 )

**Comment by potatoqualitee** [comment]
hey @PowerDBAKlaas - can you take a look by tomorrow?

**Comment by potatoqualitee** [comment]
Thank you for the suggestions, @niphlod !

**Comment by niphlod** [comment]
@PowerDBAKlaas has been provided a full chunk of code that enables parsing a whole lot easier. Since it's his own child I'll let him

**Comment by potatoqualitee** [comment]
@PowerDBAKlaas - i'll be releasing tomorrow. let me know if you can get it in, if not, ill just remove it from the psd1 until the next release

**Comment by niphlod** [comment]
this has been fixed
