### ISSUE TITLE
Test-DbaSqlManagementObject

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#1621]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [x] *feature* 
- [ ] *bug*:

## Steps to Reproduce

Would it be possible to present a cleaner error if the user inputs something outside of 9 - 14?

#### Example:
The launch of Apollo 12 failed due to electrical system failure

## Attached screen shots/console output

![image](https://user-images.githubusercontent.com/169602/27967404-8a15d3d8-6308-11e7-8b08-068ad02a16a3.png)

**Comment by gbargsley** [comment]
Same can be applied to Get-DbaSqlManagementObject if this is fixed for the Test command.

**Comment by wsmelton** [comment]
@gbargsley that commands needs to be updated to use `Stop-Function` and will output cleaner messages.

However it was discussed on doing validation on the input version, however in doing that you then have to maintain that code each time a new version of SMO is released.

In reference to your last entry, passing an alpha character, that is basic PowerShell input validation since the parameter is set to `[int]`. That is just PowerShell itself doing it's job.

If you input an integer greater than 14 the command returns `false` which is the purpose of it. That version was not found on the given machine.

**Comment by potatoqualitee** [comment]
i just removed it, no need really
