### ISSUE TITLE
 Backup-DbaDatabase observations

### ISSUE THREAD

**Issue by crshnbrn66** [sqlcollaborative/dbatools#1654]
## Is this:
_Just place "x" to indicate selection (e.g. "[x]")_

- [ ] *feature* 
- [x ] *bug*:

## System Details

- Operating system name and version:windows 10 Enterprise
- Output from `$PSVersionTable`:
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
 ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.8.957    dbatools                            {Backup-DbaDatabase, Clear-DbaSqlConnectionPool, Connect-D.

- SQL Server version for source/target
SQL 2014 
Server OS 2012r2

#### Example:
1. Created database/object/files/etc
2. Run Command:
```powershell
backup-dbadatabase -sqlCredential (get-credential) -backupdirectory c:\databases -backupFileName myDatabase.bak -SQLinstance MyDBSErver
````

When first executing this command I didn't achieve success until I at a minimum entered the backup directory and backupfilename.   I would suggest that those be made mandatory.  Additionally not being a fulltime dba I didn't realize that the backup was happening on the Server that you are calling. I mistakenly assumed the backup would come to my machine.  In addition if I put in a directory that didn't exist on the target the script didn't really error till it was nearly done and then the exception wasn't very helpful. I couldn't tell that the problem was on the target database server.  It would be very helpful to let the Script user know that this backjup is happening on the server in question with a unc display or something.  Also is the directory checked for existence? Before the backup starts?

One other point of confusion was the -sqlinstance parameter  does this imply server name + the instance on that SQL server mydbserver\instance1  is that the reason the -sqlinstance variable is named that.  Would'nt it be clearer if you used standard -computername for the name of the server to run on and then reserve instance for the name of the instance on the target host? 

thanx Thom

**Comment by potatoqualitee** [comment]
Hey thom,
Thanks for your feedback - I'll address a few and @Stuart-Moore probably will too.

>  I didn't achieve success until I at a minimum entered the backup directory and backupfilename

I specifically requested that the SQL Server's default Backup Directory be used and the backup file name be auto generated if it's not provided. Upon running this:

`Backup-DbaDatabase -SqlInstance sql2016 -Databases AdventureWorks2014`

It auto-generated the following BackupPath: `C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup\AdventureWorks2014_201707112131.bak`

What did you get?

> I would suggest that those be made mandatory.

Again, this should have been auto-generated for you - we made it optional to increase the ease-of-use. Your execution failed hard, it seems - we will try our best to recreate your environment to see what we can do.

> I mistakenly assumed the backup would come to my machine. 

This is a common mistake. We do try to ensure that it's clear where the backup goes - the information is included in the BackupDirectory parameter and the examples. In the help, it's even explicitly stated "Sql Server needs permissions to write to the location. Path names are based on the Sql Server (c:\ is the c drive on the SQL Server, not the machine running the script)"

Where did you look so that we can be aware and add the documentation there?

>  Also is the directory checked for existence? Before the backup starts?

Yes indeed. We even offer a parameter called CreateFolder that helps with creating folders that don't exist.

With regards to the -SqlInstance parameter name, we aligned the parameter with the conventional way of connecting to SQL Server. When you open up the dialog box in SSMS, etc, you're prompted to connect to a SQL Server instance - like sqlcluster\sharepoint. That's how most of us have our server name inventory, too. We do have ComputerName in many commands, but they are reserved for our Windows-based commands.
