### ISSUE TITLE
Get-Dba*Log, need for consolidation

### ISSUE THREAD

**Issue by niphlod** [sqlcollaborative/dbatools#1656]
We have two cmdlets doing very similar things:
- Get-DbaWindowsLog
- Get-DbaSqlLog

The first one asks for eventID = 17111 from windows's application log to look for the path where they are stored, and then proceed to parse the log on the server, via powershell and runspaces. It does NOTHING else with Windows logs.
The second one leverages SMO's readerrorlog (which dubs xp_readerrorlog).

So, both read the *same* ERRORLOG data, just in a different way: I'd go for merging those and have a single `Get-DbaSqlLog` .`Get-DbaWindowsLog` can then be a simple 

```
$eventSource = "MSSQLSERVER"
if ($InstanceName -notmatch "^DEFAULT$|^MSSQLSERVER$")
{
    $eventSource = 'MSSQL$' + $InstanceName
}
Get-WinEvent -FilterHashtable @{
    LogName	     = "Application"
   ProviderName = $eventSource
}
```

Differences/Problems:
- we have a start and an end param for `Get-DbaWindowsLog` but lognumber for `Get-DbaSqlLog`
-  `Get-DbaWindowsLog` fails to give you back anything if your application log cycled over event 17111, but there are better/alternative places to look for where app logs are stored
- `Get-DbaSqlLog` permits you to read from 0 to 9 logs .... but SQL can pack up 99 of those
- `Get-DbaSqlLog` needs the instance to be up and running, `Get-DbaWindowsLog` doesn't
- the format of the parsed object is a bit different between the two, `Get-DbaWindowsLog` would need to be adapted to match `Get-DbaSqlLog` (or the other way around)
- `Get-DbaWindowsLog` would be a perfect method to parse logs in absence of an instance (i.e. you recovered logs around and need to investigate) but it can't be passed a path or be run locally
- both impact *heavily* on the target system with default values. I'm on heavily audited envs with a 100MB of win app log and 99 ERRORLOG files with a daily rotation. An ERRORLOG here weights 150MB for a total net of 500k rows
- `Get-DbaSqlLog` could benefit from using sp_readerrorlog directly and filter for a specific pattern (`-Filter` ?)

**Comment by wsmelton** [comment]
One thing to consider on reading the Windows Event log is permissions and access. It requires a login access to the server, where reading the ERRORLOG can be done via SQL Login at minimum; or 'sa' account. I'd say we would need to weigh it based on accessibility and common usage.

I'd prefer to use Windows Event log because it is much more efficient and is easier to filter on what you want to find happening.

I will say the windows log command should be considered a bug restricting that to 17111 messages only, that is cutting out a large portion of information that can be identified/searched. I mean the version information on startup is ID 17069, so we are cutting out a large portion of information restricting that ID.

We might put feelers out to see who uses which command the most, or if either one is used. If not I would vote for getting rid of the ERRORLOG. In truth I've never seen a DBA not be able to read the Event Log on Windows.

**Comment by andreasjordan** [comment]
Just what to note that Get-DbaSqlLog now is Get-DbaErrorLog.

I personally would leave both in place.
@niphlod : Do you still want to work on this or can we close?
