### ISSUE TITLE
Test-DbaCompression question

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbatools#1853]
## Feature Request

Should we only show tested compression values for tables with at least one access? Or we should no matter what

**Comment by ClaudioESSilva** [comment]
imo we should show for every table. 
I can just want to know the gains I can get by doing it.
Also, if my instance has started and no access was done to the table (s) because it is one with less usage but I know that is big and I want to check the values as it is today isn't possible.

columns with % of read (scan) / write (update) should be kept but show N/A for the cases where the division can be done because of 0 reads. This way user still be able to weigh his decision 😄

**Comment by potatoqualitee** [comment]
Yes, @ClaudioESSilva - this was my expectation as well and I wondered why I had so few results across my estate. Please do modify the T-SQL as we discussed in Slack, submit a PR and I'll add a Pester test 👍 

@js0505 - Claudio and I are on the same time zone and I'd like to get a Pester test in today so I asked him to jump in and modify the T-SQL 💯 

Thanks to you both!

**Comment by niphlod** [comment]
fixed
