### ISSUE TITLE
Get-DbaWaitStat - Good command to add?

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbatools#1854]
## Feature Request

Get-DbaWaitStats - Good command to add?

**Comment by potatoqualitee** [comment]
@PowerDBAKlaas - you opinion?

**Comment by wsmelton** [comment]
What would the command output @js0505 ?

**Comment by wsmelton** [comment]
Talking just general output from [sys.dm_os_wait_stats](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-wait-stats-transact-sql) or something like Paul Randal's query?

**Comment by PowerDBAKlaas** [comment]
I'd like to see some more description too first.

**Comment by js0505** [comment]
I was thinking something along the lines of Paul Randal's stuff here https://www.sqlskills.com/blogs/paul/capturing-wait-statistics-period-time/

**Comment by PowerDBAKlaas** [comment]
Well, although I'm using PowerShell as much as I can, I don't think I'm gonna uninstall SSMS any time soon. So, the question is: "Why would I want to do this with PowerShell instead of SSMS?". What are we going to add that makes this better?

And also, for wait stats alone we can find a dozen different versions. Even Paul Randall himself wrote multiple versions. Some exclude a list of 'normal' waits that can change dependent on the specific configuration. And there's more on DMV's,missing indexes, unused indexes, index fragmentation, data profiling, blocking, plan cache, ...
We should consider a general strategy first on how to deliver those existing wealth of useful t-sql scripts.
We don't want to end up with `Get-DbaWaitStatsPaulR7` `Get-DbaWaitstatsKevinEK2`.
Would we want `Get-DbaWaitstats -flavor PaulR7`?
Or rather decide to have only one `Get-DbaWaitstats` and adapt the t-sql to the majority's wishes?

Often the needed flavor is dependent on the situation; I have 19 t-sql scripts on gathering wait stats, and pick one I think would be the most useful at that moment. Or run 2 or 3 consecutively. And it's easier to comment and uncomment some types in SSMS than  typing a list of `Include` or `-Exclude` in a console.

I'm not saying we shouldn't have it, but I need to be convinced with some flashy feature.
In that case we would probably need a very specific name too, like `Get-DbaWaitstatsForCaseabc` or something.

**Comment by potatoqualitee** [comment]
Done! Get-DbaWaitStatistic

**Comment by potatoqualitee** [comment]
and based off of Paul's famous post.
