### ISSUE TITLE
Test-DbaSqlBuildReference - Show actual and most recent version (various scenarios)

### ISSUE THREAD

**Issue by ClaudioESSilva** [sqlcollaborative/dbatools#1919]
## Feature Request
Actually we have `Get-DbaSqlBuildReference` that shows the actual version of the instance.
I would like to have a way to also get the last update and release date (we can know how many days we are "outdated").

### Problem to solve
Being able to know what is the most recent release based on instance version.
How many days I'm outdated

### Additional information
Command name suggestion: `Test-DbaSqlBuildReference `

After a conversation with @niphlod the main question is which parameters and its names we want to support.

I would start with 
`-MostRecentUpdate` - Will list the last CU from the last RTM/SP

But Simone brought another concerns like:
`-MostRecentSP`
`-MostRecentCU`

Also a parameter to that allows ignore X number of versions. `-IgnoreLastXUpdates`
`-IgnoreLastXUpdates 1`
This will allow to search for not the last version but the one before.

Suggestions for parameters names are welcome 😆

**Comment by niphlod** [comment]
we don't have release dates though. 
Updates are usually feature-driven (that release enables feature xx), fix-driven (that release fixes the issue xx) , compliance-driven (you can't run out of support versions, you can't be on the before-the-last service pack).
I apply every once in a while the "you can't run on n-3 releases", but that's just because trusting everything works fine with 5 CUs in a single update can be a hard process.  
I have seen no usecase for "I want to install that release only if it's at least 6 months old"

**Comment by ClaudioESSilva** [comment]
True. I remembered that value because the method I have used to accomplish the tast without dbatools. I forgot that we don't have it on the json file.

**Comment by niphlod** [comment]
we'll continue the discussion over at #2375
