### ISSUE TITLE
New Commands: Get/Stop-DbaExternalProcess

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#1936]
This was discussed on Twitter today. Seems like something cool to explore 

https://web.archive.org/web/20201027122300/http://vickyharp.com/2013/12/killing-sessions-with-external-wait-types/

**Comment by nvarscar** [comment]
Did a short research on this, seems that killing a SQL Server thread is a dangerous thing to do, since it can crash the instance: [http://sqlblog.com/blogs/linchi_shea/archive/2010/02/04/killing-a-sql-server-thread-don-t.aspx](url)
How to trace SPID to the OS PID of the external process: [https://www.sqlservercentral.com/Forums/Topic1486545-391-1.aspx](url)

**Comment by wsmelton** [comment]
@nvarscar it states in your second link:

> Killing a Windows OS process where the PID shown in Task Manager matches the hostprocess value returned by the query above is safe to do. It would be analog to a data-client restarting their computer while they had an open session with SQL Server.

> Killing a Windows OS thread that is a child thread of the SQL Server host-process (sqlservr.exe) where the OS thread ID shown in Process Explorer matches the kpid returned by the query above is what is ill-advised and is the subject of Linchi's article.

**Comment by wsmelton** [comment]
First step...Get-DbaExternalProcess:

![image](https://user-images.githubusercontent.com/11204251/92956722-fd156e80-f42c-11ea-8910-1b9dc81114dc.png)

![image](https://user-images.githubusercontent.com/11204251/92956760-0999c700-f42d-11ea-8cf7-6663e6fb6fbf.png)
