### ISSUE TITLE
Copy-SqlAgentJob - Allow the ability to exclude/incldue jobs based on partial name

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#196]
Copy-SqlAgentJob - Allow the ability to exclude/include jobs based on partial name. (I.e. All jobs that start with Admin)

**Comment by potatoqualitee** [comment]
This could be solved with allowing the piped results from Find-DbaAgentJob or Get-DbaAgentJob or actually, we could (and this goes for allllll commands that use our TEPP commands ;))

**If $database -match '*' then do a match instead of an -in**

Shawn, what if we made a function called like GetJobList and it does that whole routine we've been putting in every command?

````
$jobs = $server.JobServer.Jobs
			
			if ($Job) {
				$jobs = $jobs | Where-Object Name -In $Job
			}
			if ($ExcludeJob) {
				$jobs = $jobs | Where-Object Name -NotIn $ExcludeJob
			}
`````

**Comment by wsmelton** [comment]
With the `Get-JobList` added I would say the next step will be to simply include a "-Filter" and maybe `-ExcludeFilter` to the `Copy-DbaAgentJob` command.

Thoughts @potatoqualitee  ?
