### ISSUE TITLE
Remove-DbaDatabase fails when DB is in restoring state

### ISSUE THREAD

**Issue by pbarryuk** [sqlcollaborative/dbatools#2035]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Enterprise
 - PowerShell Version: Platform: V5 64Bit
 - SQL Server (Edition|Version): SQL Server 2016 Enterprise Edition (build 13.0.4435)

## Steps to Reproduce

1. Leave a DB in the restoring state (in my case this was the secondary replica after removing the DB from an AG).
2. Run the following:

`Remove-DbaDatabase -SqlInstance <ServerName> -Databases <DBName>`

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)
```
VERBOSE: [Remove-DbaDatabase][15:58:23] Connecting to !ServerName!
VERBOSE: Performing the operation "KillDatabase" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: Performing the operation "alter db set single_user with rollback immediate then drop" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: Performing the operation "SMO drop" on target "[!DatabaseName!] on [!ServerName!]".
VERBOSE: [Remove-DbaDatabase][15:58:27] Could not drop database [!DatabaseName!] on [!ServerName!]
ComputerName : !ServerName!
InstanceName : MSSQLSERVER
SqlInstance  : !ServerName!
Database     : !DatabaseName!
Status       : Index operation failed; the array index evaluated to null.
```
Does the logic need to be changed to just attempt to drop a database when it is in a restoring state?

**Comment by wsmelton** [comment]
I know this was already merged by @nvarscar but I would have to disagree with implementing this as a default action.

Just because a database is in restoring state it should not delete it on a whim. Consider a database involved in log shipping can show as restoring at times of the process. If on a DBA team and some junior goes to clean up a server and drops it, then log shipping on HA is effected and requires a ton of work to fix (especially if the database is in the TBs).

I would recommend this be done using the `-Force` flag, that causes them to think more before actually just dropping in any database in restoring state.

**Comment by nvarscar** [comment]
@wsmelton I like the idea, but also I don't want to force people who know what they are doing to use switches for all of the restoring databases. Perhaps, require -force only when the database is a part of the logshipping/mirroring/ag? That would probably require tsql code though.

**Comment by Zhunya** [comment]
This fixed, even in RDDv2!
