### ISSUE TITLE
Get-DbaPrivilege needs more detailed information/error logging when WinRM is not accessible

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#2048]
## Bug Report

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

## Steps to Reproduce

- Stop WinRM service on local machine
- Execute Get-DbaPrivilege for local machine

The error says "Failed to connect to <computername>". It is missleading on what the issue actually is, I think the error should be logged to a log file like the dbatools log, and in the warning indicate the user that for further details go to the log file.

**Comment by wsmelton** [comment]
But if you turn off WinRM it does fail to connect to the machine/computer. However I can confirm it is not writing anything to the dbatools log right now, so that does need to be fixed.

We do not add the specific text to "see logs for more details", if we do that in this one it would need to be done across the board so it is consistent.**

Only thing that command does is run `Test-PSRemoting` (an internal command). Which in turn just executes `Test-WSMan`. Which the `Test-PSRemoting` is not using our messaging system so we can update that and it should trickle the proper error out to the log.
