### ISSUE TITLE
Connect-DbaSqlServer with -ApplicationIntent parameter

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#2070]
## Bug Report
Connect-DbaSqlServer throws error when used with -ApplicationIntent parameter:

![image](https://user-images.githubusercontent.com/30303784/29174375-bfd21226-7dab-11e7-8f0f-14e5a7b92ab9.png)

### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Win7
 - PowerShell Version: 5
 - SQL Server (Edition|Version): SQL2016

## Steps to Reproduce
```
Connect-DbaSqlServer -SqlInstance $instance -ApplicationIntent readwrite

The property 'ApplicationIntent' cannot be found on this object. Verify that the property exists and can be set.
At line:225 char:39
+ ... onIntent) { $server.ConnectionContext.ApplicationIntent = $Applicatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```
 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`) - no entries in the log related to Connect-DbaSqlServer
 - [x] Attach output from PowerShell console (if possible/allowed)

## Feature Request
Thinking about some AG-related scenarios where queries should be run on a secondary instances.

### Problem to solve
Don't have one yet.
Seems that at some point the connection object type has been changed and this new object does not support this parameter anymore.

**Comment by galador** [comment]
It looks like the [ServerConnection class](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.common.serverconnection.aspx) doesn't actually have an ApplicationIntent property. It looks like there's a [Connect Item to add it](https://connect.microsoft.com/SQLServer/Feedback/Details/1088152).


I tried changing the function locally so that it just adds that property to the connection string, as it looked like there were [some other properties that do that](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Connect-DbaSqlServer.ps1#L245), but it looks like setting the SqlInstance property that was added in https://github.com/sqlcollaborative/dbatools/commit/ed20673bcc858492249b308039490e3621590046 might've broke things.

When I was working on it, I got the error below because [the code](https://github.com/sqlcollaborative/dbatools/blob/master/functions/Connect-DbaSqlServer.ps1#L276) calls `InnerException` twice, but there is only one InnerException:

```
You cannot call a method on a null-valued expression.
At C:\DTCdev\git\dbatools\functions\Connect-DbaSqlServer.ps1:280 char:17
+                 $message = $message.ToString()
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

The actual error I get if I step through the debugger is: 

```
"Exception setting "ServerInstance": "Property ServerInstance cannot be changed or read after a connection string has been set.""
```
