### ISSUE TITLE
Test-DbaMigrationConstraint returns nothing

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2100]
Can someone please fix Test-DbaMigrationConstraint? It has $Database -eq 0 which isn't working. Claudio, not sure if you have time but please take a look.

Would you also be able to make a column that's like "IsMigratable = $true" so that it's easy to determine?

Also would you be able to do a check for FileStream to non-filestream?

**Comment by potatoqualitee** [comment]
Full text too? Whatever Copy-DbaDatabase checks for

**Comment by ClaudioESSilva** [comment]
Will submit a PR with:
 - the fix for `$Database -eq 0` 
 - include `IsMigratable` property.
 - include FileStream validation

Full-Text Catalog checks
Regarding the Full-Text catalog this is enabled per database (not server level). Also, please read the remarks section here: https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-fulltext-database-transact-sql
