### ISSUE TITLE
Restore-DBADatabase fails when the file path is greater than 255 characters (Read-DBABackupHeader)

### ISSUE THREAD

**Issue by emcneil3** [sqlcollaborative/dbatools#2131]
### General Troubleshooting steps

- [x ] Verified running latest release of dbatools? 0.9.31
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): 
Windows 10 and Windows 2012 R2
 - PowerShell Version: 
PSVersion                      5.1.14393.1480
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1480
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 - SQL Server (Edition|Version): 
SQL 2012

## Steps to Reproduce

We use Ola Hallengren's backup scripts to do backups for SharePoint SQL Servers because it is able to truncate the name of the backup file to fit within Windows file path character limit. When I tried to restore the backup using the Restore-DBADatabase command it fails. Below is the message that gets generated:

"WARNING: [Read-DbaBackupHeader][15:30:29] File  does not exist or access denied. The SQL Server service account may not have access to the source directory."

The account does have permission to the file and the file does exist. The way I was able to get this to work was to manually modify the file so the file path would be 255 characters. It looks like with the Ola backup script the file name can be up to 259 characters. Below is the command that I executed:

restore-dbadatabase -sqlserver xsv123sql12345 -path [network path location 40 characters long]\[sql server]\Search_Service_Application_012813_AnalyticsReportingStoreDB_9b7582af739543f1aba4944a322a8a9f -ignorelogbackup -NoRecovery -outputscriptonly

Same warning message using the Read-DBABackupHeader cmdlet
 - [x ] Attach output from PowerShell console (if possible/allowed)

**Comment by Stuart-Moore** [comment]
Actual error is thrown by Test-DbaSqlPath, which in turn is reporting back the results from xp_FileExists which is saying the file doesn't exist. So that'll be MS having different standard across a product group 🤦‍♂️ 

It's not Ola's scripts btw, the underlying T-SQL backup command is set to allow 259 characters, hence the facepalm.

There is a potential work around using xp_dirtree, which does return the overlength files, but that's quite a departure from the current method. So wanting feedback from @potatoqualitee  and @ClaudioESSilva  before pushing that as an option as it's quite a bit of either a rewrite of Test-DbaSqlPath, or other functions that rely on that function.

**Comment by emcneil3** [comment]
Thanks for your response. Yes I just found that out the xp_FileExists has this limitation so the work around that seems to work is when referencing the backup directory in Ola’s script I append the .com to may domain name and when I use the ‘Restore-DbaDatabase’ I remove the .com from the path I specify.

**Comment by Stuart-Moore** [comment]
Thanks for the feedback.

Going to close this now as it's not really something we (dbatools) can fix reliably
