### ISSUE TITLE
Design RFC: Silent and AllowException

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2135]
I now agree that it should be two params to handle the way we're "nice" ;) - Silent AND AllowException.

Considering this, can we have a global setting? Most of the type of programming I'm doing now would be Silent and AllowException across the board.

**Comment by FriedrichWeinmann** [comment]
I too see a need to
 - Control exception handling
 - Handle downlevel verbosity

The current design as I am working on it includes:
 - A global shut-up option (Verbosity only)
 - The `AllowExceptions` parameter

I'm not yet quite sure what the best way to handle item level verbosity is. Basically, there are two ways to go, both have their benefits and penalties:
 - `-Silent` parameter: Besides introducing a breaking change (one I could live with), it would require consistent inheritance/passing through on all levels. Public functions couldn't use default values to pass it through either, since it'd be null. On the plus side, actually opting out of the verbosity would be trivial.
 - Variable `$DbatoolsVerbosityPreference`. Similar to other preference variables, it'll be known on all inner scopes and thus automatically respected. This is the easiest solution from an architecture perspective and lenient with the average contributor. On the other hand, making the inner function shut up will be a bit more a hassle in that model:
```PowerShell
$DbatoolsVerbosityPreference = 'AllSilent'
Start-DbaCommand
Remove-Variable DbatoolsVerbosityPreference
```
Or using an internal function to make it more intuitive:
```PowerShell
Set-DbaVerbosity -Verbosity 'AllSilent'
Start-DbaCommand
Set-DbaVerbosity -Clear
```

**Comment by niphlod** [comment]
I for one vouch for a numerical loglevel to control the output of messages even from functions that call functions (that call functions, and so on). The module already adopted a "non-powershelly" way to handle messaging, I don't see why a more flexible system may scare the average contributor away more than the current "status of things"

**Comment by wsmelton** [comment]
There is a numerical value to our logging, Fred just added a textual value that is also accepted. Unless you are talking about a different number value.

**Comment by niphlod** [comment]
it's numerical but it's "global". We can't (AFAIK), use in a calling function "resolve-dbanetworkname -loglevel 3" to make that call (and only that) less chatty than the default, or, in one of a baked script "on top" of dbatools, use different levels of verbosity for each function.

**Comment by niphlod** [comment]
although I feel we still have a long way to go for logging, I'm closing this as it won't probably ever get enough traction since I'm the only "pusher" :P 
Thanks all for all the efforts and keeping up with me.
