### ISSUE TITLE
Update-ServiceStatus use of `Get-WmiObject` should be updated

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2159]
## Feature Request
This is an internal command that is utilizing `Get-WmiObject` and should be written to utilize CIM via our `Get-DbaCmObject` command so we can support multiple protocols to access a remote device.

### Problem to solve
Limitations of `Get-WmiObject` and should be replaced to utilize `Get-DbaCmObject`.

**Comment by nvarscar** [comment]
Can someone tell why WMI protocol in Get-DbaCmObject is disabled by default? 
```powershell
Get-DbaConfigValue -Name 'ComputerManagement.Type.Disable.WMI'
#True
```
CimRM and CimDCOM do not return any methods to control services. WMI does. Is it okay to temporarily enable WMI for this kind of request, since Cim* protocols are not an option?
I could probably try to switch to `Get-Service ... |Stop-Service` instead of doing that through WMI, but that would also mean that CmObject function won't be utilized. I could go with SMO object methods, but those are really clunky: don't return exit codes from what I remember and sometimes throw weird errors.

**Comment by nvarscar** [comment]
@wsmelton that was my original intention - to use managedcomupter object, but those methods don't return exitcodes. The script won't be able to catch meaningful errors, only success/failure based on service status after refreshing the object. Same stays true for `Get-Service ... |Stop-Service` - no exit codes. Win32_Service WMI class seems to be the only thing that outputs something.
There is an option to go with Invoke-WMIMethod instead of calling methods of the WMI object. In this case I would be able to use Get-DbaCmObject, but will still have to do WMI method calls using a different function. Please let me know if you think that's a good idea.

**Comment by nvarscar** [comment]
Switched to Get-DbaCmObject and Invoke-CimMethod. Thanks for the suggestion - it works really fast!
