### ISSUE TITLE
Get-DbaSqlService methods for stop, start and restart

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#2170]
This is not a bug nor a feature request, but a question of what is the need for them?

If I run:
```powershell
(Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Stop()
```
Will give me the warning that dependent services are still running so it cannot stop the service. That is fine and dandy, so why would we ever use it? If I have to manually call the command for each service that is dependent I could have done it quicker by just calling `Stop-Service mssqlserver -force` and it will stop everything for me.

The odd ball is the Restart() method in the command. If I stop `mssqlserver` and then try the Restart() method it gives a false warning for some reason but then starts the service.

```powershell
C:\GitHub\dbatools [development ≡]> (Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Restart()
WARNING: [Get-DbaCmObject][21:20:09] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."
WARNING: [Restart-DbaSqlService][21:20:12] The attempt to stop the service MSSQLSERVER on MANATARMS returned the following error: The
requested control code cannot be sent to the service because the state of the service (Win32_BaseService.State property) is equal to 0
, 1, or 2.
[Restart-DbaSqlService][21:20:15] Service MSSQLSERVER on MANATARMS was successfully started.
C:\GitHub\dbatools [development ≡]> Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver | select ServiceName, State
WARNING: [Get-DbaCmObject][21:20:33] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."

ServiceName            State
-----------            -----
MSSQLSERVER            Running
MSSQLServerOLAPService Stopped
ReportServer           Stopped
SQLSERVERAGENT         Stopped
```

If I start the agent service and then try to use the restart method again I get a warning about stopping and starting. It seems that `Restart-DbaSqlService` does not quick when it hits the first issue with the service:

```powershell
C:\GitHub\dbatools [development ≡]> (Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver -Type Engine).Restart()
WARNING: [Get-DbaCmObject][21:22:16] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."
WARNING: [Restart-DbaSqlService][21:22:17] The attempt to stop the service MSSQLSERVER on MANATARMS returned the following error: The
service cannot be stopped because other services that are running are dependent on it.
WARNING: [Restart-DbaSqlService][21:22:18] The attempt to start the service MSSQLSERVER on MANATARMS returned the following error: The
 service is already running.
C:\GitHub\dbatools [development ≡]> Get-DbaSqlService -ComputerName manatarms -InstanceName mssqlserver | select ServiceName, State
WARNING: [Get-DbaCmObject][21:22:25] [manatarms] Could not find a valid connection protocol, interrupting execution now | Exception ca
lling "GetConnectionType" with "2" argument(s): "No connectiontypes left to try."

ServiceName            State
-----------            -----
MSSQLSERVER            Running
MSSQLServerOLAPService Stopped
ReportServer           Stopped
SQLSERVERAGENT         Running
```

Overall, I would recommend removing those methods from `Get-DbaSqlService`, and just let folks stick with `Stop-Service` and `Start-Service` that are built-in. Truthfully I will likely stick with using those as I'm not going to try and import dbatools just to get a service started, stopped or just restarted.

It may just be my opinion but maintaining extra commands when there is already a built-in way to handle it just seems a bit excessive.

**Comment by nvarscar** [comment]
Hey @wsmelton , thanks for testing! Most of the warnings will go away once #2158 is resolved, I was also thinking about introducing -Force switch, that would include dependent services and stop/restart them as well, so that's a great suggestion. As for the questions:
_>Will give me the warning that dependent services are still running so it cannot stop the service._
You could've added Agent type to the -Type list, including the agent service. I'll also add -Force parameter later to deal with such situations.
_>The odd ball is the Restart() method in the command. If I stop mssqlserver and then try the Restart() method it gives a false warning for some reason but then starts the service._
It tries to stop and then start the service. I'll add service status handling and remove the necessity to stop the service if it's already stopped.
_>If I start the agent service and then try to use the restart method again I get a warning about stopping and starting. _
In your code there is Engine, not Agent service type in the parameters. Engine failed to stop since there was a dependency on Agent and failed to start as it was already running.

As for the use case scenario, I'm pretty sure that it's really rare to have a need to restart multiple services on multiple servers at once, but in my environment we change passwords for service accounts every so often and the services need to be restarted after that. Most of my instances are named ones and if I use Restart-Service, I have to script a comprehensive logic to search for services that have certain name patterns and then restart them in due order. This set of commands helped me a lot to automate such restarts.

**Comment by wsmelton** [comment]
> You could've added Agent type to the -Type list, including the agent service.

This does not work...and I tried using `Agent,Engine` or `Engine,Agent`
![image](https://user-images.githubusercontent.com/11204251/30001410-f831062c-9052-11e7-8528-932ffbdbbcc1.png)

Do you  mean adding the Force switch to `Get-DbaSqlService` or the other service commands? If to the other commands how would you move that ability into the method in Get-DbaSqlService?

> Restart-Service, I have to script a comprehensive logic to search for services that have certain name patterns and then restart them in due order

For applications, maybe but SQL Server has a set pattern on what each service will be named for a default instance and a named instance. You only ever deal with SSAS and SSRS outside of Agent but Agent is the only one dependent/tied to SQL Server engine service. Everything else will recovery itself if SQL Server is restarted without having to be restarted themselves.

**Comment by nvarscar** [comment]
Right now, methods are executed for each object separately. I wonder if I could make it work with the array as well, but that would require some logic changes behind the scenes and I'm not even sure that would be possible, need to test that.

> Do you mean adding the Force switch to Get-DbaSqlService or the other service commands? If to the other commands how would you move that ability into the method in Get-DbaSqlService?
To the other commands. Methods seems to be an awkward place to implement something like this.
`(Get-DbaSqlService).Restart($true)` doesn't feel too right, but might actually work out in the end.
>For applications, maybe but SQL Server has a set pattern on what each service will be named for a default instance and a named instance. You only ever deal with SSAS and SSRS outside of Agent but Agent is the only one dependent/tied to SQL Server engine service. Everything else will recovery itself if SQL Server is restarted without having to be restarted themselves.
Yep. It's only been done for SQL Server Agent mostly. For other services it seemed like a logical thing to do.

**Comment by nvarscar** [comment]
All of the issues have been addressed (hopefully) - thanks again for comprehensive testing!
