### ISSUE TITLE
Feature Request - Balance Data

### ISSUE THREAD

**Issue by artyq** [sqlcollaborative/dbatools#2357]
## Feature Request

It would be interesting if you could create a function that would re-balance data within multiple data files to make them equal, when either adding new data files or reducing the number of data files.

**Comment by potatoqualitee** [comment]
Ouuuu I like that! I'll see if anyone is up for it

**Comment by Stuart-Moore** [comment]
Only way I know is to create a new filegroup across multiple files and then
MOVE the data across to that group. If there's multi files Sql will write
across them (balancing). As far as I know it won't rebalance if you add an
existing file, it'll just write across them from then on.

You might be able to cheat by rebuilding the c index with drop, but that's
going to mean double the storage (or more) while that's going on.

it's the sort of thing that needs planning for each scenario, rather than a
'one size fits all' thing.

So, it's doable, but wether it's doable in a sensible way we can offer to
people who don't understand the underlying actions is another thing.

**Comment by wsmelton** [comment]
Unless you plan on adding some AI or machine learning code to this function you will not be able to cover every scenario.

@Stuart-Moore is right in that data files in a filegroup are written to in a round robin method, so just adding a new file will not have any effect. SQL Server will simply begin writing to that file until the free space matches up close to the other files.  A rebuild of an index within that file group will not help any because your file size will not change, so you cannot force the round robin piece of SQL Server.

**Comment by niphlod** [comment]
@wsmelton , @potatoqualitee : is this in as Invoke-DbaBalanceDataFiles ? if yes, please close this
