### ISSUE TITLE
Propose DataFileSizeMB in Set-SqlTempDbConfiguration if not provided

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#257]
Can we auto guess DataFileSizeMB if it's not specified? Perhaps there's a formula or general recommendation.

**Comment by ConstantineK** [comment]
I did some additional research(googling) and found a few places that make recommendations around autogrowth, and the rub is basically:

https://support.microsoft.com/en-us/kb/315512
- Set it in MB (we do this)
- Grow your database to a point where you shouldn't hit autogrowth "this year" (VLF issues can happen here and this is also a blocking op to grow the file, especially a problem for log files because they don't benefit from instant file initialization.) 
- Using IFI means you can get a large chunk of data made available without zeroing, but if they dont have this one a growth of 1GB could take awhile. 

http://www.sqlservercentral.com/blogs/steve_jones/2011/12/02/autogrow-guidelines/
and https://voiceofthedba.wordpress.com/2011/12/02/autogrow-guidelines/
Issue the following guidelines:

```
MDF Size - File Autogrowth
< 1GB 	       100MB
1GB-50GB       2GB
50GB-200GB     5GB
200GB-1TB      10GB
> 1TB 	       50GB
```

http://www.sqlskills.com/blogs/paul/importance-of-data-file-size-management/
"I can't give any guidance here as to what a good number is, but I'd probably settle on something around 10% (fixed), with the percentage steadily falling as the database size grows. It's very important that you have alerts setup to you can tell when auto-growth does occur, so you can then take any necessary action to grow it even more or tweak your settings."

After reading the various resources, I dont know if it is useful to try and extrapolate:
- Actual disk space available. 
- IFI enabled
- Number of databases on disk and the amount of free space they have (could we trigger an autogrowth on 10 large databases and fill up the drive?)
- Expected growth (really, you only want autogrowth as a backup plan when a db is growing more than the space you have planned for it)
- DB growth over time (generally we want to autogrow as little as possible and have the DBAs notified about the growth so they can address the issue and grow the db file again manually and in a much larger increment)

Does anyone have any other resources that might shed some light on this?

**Comment by ConstantineK** [comment]
Taking from https://blogs.msdn.microsoft.com/batuhanyildiz/2013/05/29/what-size-is-suitable-as-an-initial-size-for-tempdb-system-database/
- 10% of the total size of databases greater than 1TB
- 15% of the total size of databases greater than 100GB and less than 1TB 
- 25% of the total size of databases greater less than 100GB

The only issue with that approach is that if the system doesn't have databases already on it, a fixed choice such as 512/1024 as originally used makes a lot more sense. 

So, combining approaches where we set a lower bound of 512MB (which can be overridden with the other fixes in the pipeline if you want to specify a very small value) and then increasing in useful increments seems like the way forward. 

Does anyone know if https://connect.microsoft.com/SQLServer/feedback/details/481594/log-growth-not-working-properly-with-specific-growth-sizes-vlfs-also-not-created-appropriately would affect older version of SQL Server? Should I be making sure we don't have a file size divisible by 4096MB?

**Comment by ClaudioESSilva** [comment]
Starting from the end:
Yes you should. I have addressed that issue on https://github.com/sqlcollaborative/dbatools/blob/development/functions/Expand-SqlTLogResponsibly.ps1 function. 

I think that bug is on every version before 2012.
Read description and see if it helps.

I agree with the combinationed approaches.

**Comment by niphlod** [comment]
@ClaudioESSilva : just spring cleaning here... is this issue still valid ?

**Comment by potatoqualitee** [comment]
@ClaudioESSilva - will you add this information as required? but use [dbasize] so it can auto adjust the size

**Comment by potatoqualitee** [comment]
gotta get a stale bot
