### ISSUE TITLE
Add backup parameters to Copy-DbaDatabase

### ISSUE THREAD

**Issue by jjmcmullan** [sqlcollaborative/dbatools#2585]
## Feature Request

Can the backup and restore parameters be added to the command please i.e. buffercount, maxtransfersize, blocksize, filecount, compression. I'm not sure what the thoughts are within the community but maybe encryption should be included too.

Thanks,

Jonny

**Comment by josh-simar** [comment]
I could add this if agreed. Currently Copy-DBADatabase is sitting at 25 switches / parameters that can be added to it so this would add quite another few depending. If we want to add this as being able to be specified on both sides of the equation it would be 7, if we want it to only be on 1 side it would be 4 (buffercount, maxtransfersize, and blocksize can all be specified on both backup and restore). File count can already be specified so I'm not including that. If decided that we only want to do 4 new parameters would we want to apply the shared one's to both sides or only the backup side?

**Comment by wsmelton** [comment]
The file count is already being used in the command, it is statically set to 3 files. Which that value was determined from testing and on average was the optimal value. 

Compression I would say does not need to be a parameter since you can set that value at the instance level, and should be enabled. If that is done then any backup against that instance would be compressed.

I'll leave it up to @potatoqualitee and @Stuart-Moore but I would say the parameters for buffer count, transfer size and block size are not commonly used enough to extend the parameter count for this command. If there is a dire need to utilize those for backing up a database backup then the `Backup-DbaDatabase` command should be used. 

The encryption parameter is not currently supported by `Backup-DbaDatabase` so no point in adding it to the copy command.

**Comment by jjmcmullan** [comment]
On the system I'm working the difference in speed is huge. A 60GB DB takes over 10 minutes to backup but with the correct buffer count, transfer size and block size parameters supplied the same backup runs in 2.5 minutes. 
For this migration I have done exactly as @wsmelton suggested and run a migration command with -NoDatabases and then a separate backup and restore to move the databases and complete the move.

**Comment by Stuart-Moore** [comment]
Coukd this be held off on please as I'm trying to finalise the new restore
stuff which is meaning some work on this and backups.

Your life (and mine would be good if a PR can be held off on for a couple
or days.)

Saves merge fun for someone as well :)

Cheers
Stuart

**Comment by niphlod** [comment]
I'd instead go for solving these kind of issues splitting the copy
operations in pre/backup/post or else every param added to the underlying
functions will be requested to be added also in the "upper level" ones.

Il 06 nov 2017 6:42 PM, "Stuart Moore" <notifications@github.com> ha
scritto:

> Coukd this be held off on please as I'm trying to finalise the new restore
> stuff which is meaning some work on this and backups.
>
> Your life (and mine would be good if a PR can be held off on for a couple
> or days.)
>
> Saves merge fun for someone as well :)
>
> Cheers
> Stuart
>
>
>

**Comment by jjmcmullan** [comment]
There's no hurry for this from my point of view, I just suggested it as it may help someone else. If it's not deemed suitable or is well down the priorities list then so be it. 
I'm not very proficient in PowerShell so I don't know it the following is possible but I'll suggest it anyway; is there a way that the dbatools library could have "global environment variables" that could be setup. so I could set things like BufferCount, MaxTransferSize and BlockSize and then every command that uses them would pick them up from the default environment unless overridden by the local parameter. That would mean that the parameters wouldn't need to be passed through every command. 
It would also mean each developer or team could tune the dbatools library to their environment.

**Comment by nocentino** [comment]
Regarding adding compression as a parameter. I have a client system that uses CommVault as their enterprise and database backup platform. The CommVault backup client itself is managing the compression with its own mechanisms. So the standard build has the instance level compression turned off. We leave this off because we the VDI stream will be uncompressed into CV client avoiding spending CPU time compressing the data twice. But there are cases where we still use Copy-DbaDatabase to move data around between systems and would love to have compression available for those backup streams. Just wanted to give y'all another data point in that decision process.

**Comment by wsmelton** [comment]
@nocentino so if you have what looks to be one-off situations where you need to move a database, why not just use the Backup/Restore commands themselves? The only thing extra that the Copy command would be doing for you is moving that backup file around.

**Comment by potatoqualitee** [comment]
I've often leaned to suggesting Piping the results of `Backup-DbaDatabase | Restore-DbaDatabsae`. Copy does a couple extra things like setting the owner using those two plus a couple other dbatools commansd, and you could have a more powerful copy comment suited for your environment.

**Comment by nocentino** [comment]
@wsmelton and @potatoqualitee : Totes, that's what I'm doing now. Just wanted to give y'all another perspective on how it's used :)

```
$backup = Backup-DbaDatabase -SqlInstance $source -Database $Databases -BackupDirectory $backupShare -CopyOnly -FileCount $NumFiles -CompressBackup
$backup | Restore-DbaDatabase -SqlInstance $destination 
```
