### ISSUE TITLE
Get-DbaRoleMember change output object to native SMO object

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#2691]
### General Troubleshooting steps

- [X] Verified running latest release of dbatools?
v0.9.102
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 1703 15063.674
 - PowerShell Version: 5.1.15063.674
 - SQL Server (Edition|Version): SQL 2008 R2 SP3 10.50.6220 Standard

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

```Get-DbaRoleMember -SqlInstance MYSERVER | Get-Member | Select-Object -ExpandProperty TypeName | Select-Object -Unique # check if output is Smo to pass into Export-DbaScript```

```Get-DbaRoleMember -SqlInstance MYSERVER -IncludeServerLevel | Export-DbaScript -Path $rolesoutputfilesql # cannot use since System.Management.Automation.PSCustomObject thus not SMO object```

```WARNING: [Export-DbaScript][08:49:16] InputObject is of type System.Management.Automation.PSCustomObject which is not a SQL Management Object. Only SMO objects are supported.```

## Feature Request

By changing the output object from  System.Management.Automation.PSCustomObject to Microsoft.SqlServer.Management.Smo.DatabaseRole (or other more appropriate SMO object if found) it will allow usage with `Export-DbaScript` which requires SMO object.

### Problem to solve
Allow usage with `Export-DbaScript`

### Additional information

SMO Reference:
https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.databaserole.aspx
Perhaps via the EnumMember() Method?

**Comment by PowerDBAKlaas** [comment]
@wsuhoey you're looking at this the right way, but the real solution is just a little bit different. 😃 

Since there is no SMO object 'Rolemember', we can't create one. As you found, there is an object 'DatabaseRole' ( and also a 'ServerRole'). Creating `Get-DbaDbRole` and `Get-DbaServerRole` is on the list, and those will return the SMO objects.

We were just brain storming recently with @wsmelton about whether we should or should not combine them and what the consequences for `Get-DbaRoleMember` will be.
I think I will create both functions soon.

**Comment by wsmelton** [comment]
#2485
