### ISSUE TITLE
test-dbalastbackup | Out-DbaDataTable BackupDate incompatibility

### ISSUE THREAD

**Issue by dhlotter** [sqlcollaborative/dbatools#2701]
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10 Version 1703 (OS Build 15063.674)
 - PowerShell Version: 5      1      15063  674   
 - SQL Server (Edition|Version): Developer Edition | Microsoft SQL Server 2016 13.0.4206.0 (X64)

## Steps to Reproduce
```powershell
Test-DbaLastBackup -SqlInstance localhost | Out-DbaDataTable | Write-DbaDataTable -SqlInstance localhost -Table Utilities.dbatools.BackupRestoreTests -AutoCreateTable
```
 - [x] Attach any screenshots (if possible/allowed) 
![capture](https://user-images.githubusercontent.com/5402695/32989358-52af0d22-cd1d-11e7-86d5-785089adfa06.png)
 - [x] Attach logs generated by dbatools (`Get-DbatoolsLog`) 
[dbatools.log](https://github.com/sqlcollaborative/dbatools/files/1485413/dbatools.log)
 - [x] Attach output from PowerShell console (if possible/allowed) 
[console.log](https://github.com/sqlcollaborative/dbatools/files/1485415/console.log)

## Additional Info
```sql
USE [Utilities]
GO
CREATE TABLE [dbatools].[BackupRestoreTests](
	[SourceServer] [NVARCHAR](MAX) NULL,
	[TestServer] [NVARCHAR](MAX) NULL,
	[Database] [NVARCHAR](MAX) NULL,
	[FileExists] [BIT] NULL,
	[Size] [BIGINT] NULL,
	[RestoreResult] [NVARCHAR](MAX) NULL,
	[DbccResult] [NVARCHAR](MAX) NULL,
	[RestoreStart] [NVARCHAR](MAX) NULL,
	[RestoreEnd] [NVARCHAR](MAX) NULL,
	[RestoreElapsed] [NVARCHAR](MAX) NULL,
	[DbccStart] [NVARCHAR](MAX) NULL,
	[DbccEnd] [NVARCHAR](MAX) NULL,
	[DbccElapsed] [NVARCHAR](MAX) NULL,
	[BackupDate] [DATETIME2](7) NULL,
	[BackupFiles] [NVARCHAR](MAX) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
BackupDate column type is `[DATETIME2](7)` 
when performing the same command to gridview with:
```powershell
Test-DbaLastBackup -SqlInstance localhost | Out-GridView 
```
we see that the BackupDate values are not supported by datetime. 
![capture2](https://user-images.githubusercontent.com/5402695/32989426-2cc34eb0-cd1e-11e7-8a72-0c11aa397c96.png)

i will be able to overcome this by changing `[BackupDate] [DATETIME2](7)` type but would like to have this done the correct way especially as the `-AutoCreateTable` switch is used.

**Comment by leejkl** [comment]
I would like to add some additional information relating to this issue.  If the table is created with -autocreatetable and the database(s) are in simple recovery the column BackupDate is created as datetime2(7).  If the table is created with -autocreatetable and the database(s) are in simple recovery the column BackupDate is created as nvarchar(max) as there are multiple backupdates for representing log files.

**Comment by potatoqualitee** [comment]
Greetings,
This _may_ have been fixed by another patch, please try again with the most updated version.

`ConvertTo-DbaDataTable` is no longer required 🎉  You can now just execute

`Test-DbaLastBackup -SqlInstance sql2017 | Write-DbaDataTable -SqlInstance sql2017 -Table tempdb.dbo.BackupRestoreTests -AutoCreateTable`

If it does not work, however, please note that AutoCreateTable is intended to be a best guess bandaid that uses the first row to guess. For long term table use, we do recommend evaluating the best data types for each column and recreating the table with appropriate dadta types. If you find yourself frustrated by the guesses being too restrictive, you can also use -UseDynamicStringLength which will set everything to `nvarchar(max)` until you can recreate the table with the appropriate data types.
