### ISSUE TITLE
Get-DbaBackupInformation - new switch `RestoreTime`

### ISSUE THREAD

**Issue by Zhunya** [sqlcollaborative/dbatools#2713]
## Feature Request

Get information on what files we need to restore database to given date/time from `msdb`.
This may save us time to get files from tape, or, just supply files list to `Restore-DbaDatabase` this will save time consuming step to read backup headers from disk.

### Problem to solve

Save time

**Comment by niphlod** [comment]
isn't that a feature already present for get-dbabackuphistory ? if you have to go to msdb, use the history, if you don't have it, go to get-dbabackupinformation

**Comment by Stuart-Moore** [comment]
I think you're asking for what Select-DbaBackupInformation does? That filters down backups to those needed to get to RestoreTime

What you actually want is a 'Only scan files newer than this' parameter?

**Comment by Zhunya** [comment]
@niphlod nope GDBI don't give as info for `RestoreTime`, just last full/diff/log and since some date, but what I want, I home, will make GDBI all around command for backup information.
@Stuart-Moore, I'll take a look at `Select-DbaBackupInformation`

**Comment by Stuart-Moore** [comment]
If you pipe Get-DbaBackupHistory output into Restore-DbaDatabase with the `-TrustDbBackupHistory` switch it skips GDBI (so all header scans) and just dumps it into Select-DbaBackupInformation to build a history up.

If someone wants to reduce the number of files being scanned there's the option to do this:
```
Gci c:\mybackups  -recurse | ?{$_.LastWriteTime -gt (Get-Date).AddDays(-2) | Restore-DbaDatabase .....
```

Same works with GDBI as well. Thinking is that if someone wants to do something that complex it's probably better they work with standard PS components and then we take over, rather than writing overly complex code that won't be right for everyone

**Comment by Zhunya** [comment]
Thank you guys for help!

`Get-DbaBackupInformation` and `Select-DbaBackupInformation` is what I need =)
