### ISSUE TITLE
Update-dbatools - Always installs to $PROFILE/../Modules/Powershell

### ISSUE THREAD

**Issue by dwierenga** [sqlcollaborative/dbatools#273]
Although the install.ps1 cmdlet accepts a $Path parameter, the Update-DBATools command does not pass any arguments to the install script.  

Therefore, calling Update-DBATools always results in the module being installed to a parent path of your powershell $PROFILE, regardless of where you currently have the module installed.

**Comment by wsmelton** [comment]
If you install the module from the PowerShell gallery using `Install-Module` it will be installed under `C:\Program Files\Windows PowerShell\Modules\dbatools`. 

So if you are using the Package Management commands to install the module, you will need to keep using those to update or remove the module. 

We may just need to add a check to see where the module is installed instead of defaulting to the user's profile path.

**Comment by ctrlbold** [comment]
Thanks @dwierenga. update-dbatools was intended primarily to support non-gallery installs. In order to support Gallery, looks like we'll have to 

    try { 
        Get-InstalledModule -Name dbatools
        Update-Module dbatools 
    }
    catch { 
        Do regular routine 
    }

**Comment by niphlod** [comment]
@ctrlbold : pinging against staleness... if there is a solution it should be in the next release or in the n+1 one.

**Comment by niphlod** [comment]
@ctrlbold : ping+1 . IMHO this got solved with all the recent jabberish with incorrect encoding and @ck sweat. Please close this if we're all good.

**Comment by potatoqualitee** [comment]
checking, @niphlod

**Comment by potatoqualitee** [comment]
This has indeed been resolved!
