### ISSUE TITLE
module stuck 'Importing' when adding to Azure Automation

### ISSUE THREAD

**Issue by cabana1** [sqlcollaborative/dbatools#2814]
## Bug Report
dbatools module stuck 'Importing' when adding to Azure Automation
### General Troubleshooting steps

- [x ] Verified running latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [ ] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): NA
 - PowerShell Version: NA
 - SQL Server (Edition|Version): NA

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Problem to solve

Am I missing a prerequisite that will allow this to complete?

**Comment by FriedrichWeinmann** [comment]
Heya cabana, thank you for notifying us about this issue, and apologies for the inconvenience.
The first thing you can do to receive maximum information is to run this before import:
`$dbatools_serialimport = $true`

By default, dbatools optimizes import speed by parallelizing some tasks. This however makes it harder to track what happens when something goes wrong, since the background actions are invisible. Setting this option before import has everything running in the foreground.

If you set this and import again, does it report any errors?

**Comment by cabana1** [comment]
Thanks for you reply @FriedrichWeinmann 

I was actually adding the module via the Azure Module Gallery.  When you find the module you want to add it only gives you a 'Import' button.  I clicked that button.  Azure reported it was imported successfully under 'notifications' but the Module list still reports 'Importing' (for hours).

**Comment by cabana1** [comment]
Has anybody been able to load dbatools into Azure?  Could I be missing a prerequisite for dbatools to install on azure?

**Comment by cabana1** [comment]
To remove the module I was able to run: Remove-AzureRmAutomationModule.  I don't recall if I tried this before.  In any event, this removed the module.  I was then able to import the module (0.9.188) successfully (https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/remove-azurermautomationmodule?view=azurermps-5.1.1).

PS C:\>Remove-AzureRmAutomationModule -AutomationAccountName "Contoso17" -Name "ContosoModule" -ResourceGroupName "ResourceGroup01"

 Make sure you change the cmdlet with the proper parameters from your account.
