### ISSUE TITLE
Importing dbatools module breaks tab completion of .NET types via command line

### ISSUE THREAD

**Issue by gwojan** [sqlcollaborative/dbatools#2907]
## Bug Report
I was working with some different .NET types from the command line and noticed once ```dbatools``` was imported tab completion of the type name is broken.
### General Troubleshooting steps

- [x] Verified running latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/fresh PowerShell.exe session?

### Version Information
 - Operating System (Name|Version): Windows 10, Windows Server 2012 R2, Windows Server 2008 R2
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): N/A

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [ ] Attach output from PowerShell console (if possible/allowed)
 * Open new PowerShell console
 * Type ```[system.date<press tab>``` and it will tab complete to ```[System.DateTime```
 * Import dbatools module directly or indirectly
 * Type ```[system.date<press tab>``` and nothing happens

**Comment by potatoqualitee** [comment]
wow, super interesting. can repro. @FriedrichWeinmann any ideas?

**Comment by FriedrichWeinmann** [comment]
I've been wondering about that for some time and have come to assume it's due to the sheer amount of SQL Server libraries we load. That either it's just too many of them or that one of them introduces an error in whatever PowerShell uses to tabcomplete types (just loading our own library is fine).
Wasn't bothered by it yet, so I've kept pushing that issue back, but it looks like it's finally caught up with me :smile: 
I'll look into it
