### ISSUE TITLE
Extended Property Commands needed

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#2908]
https://www.red-gate.com/simple-talk/sql/database-delivery/reading-writing-creating-sql-server-extended-properties/

**Comment by awickham10** [comment]
Do you have any ideas on how this would be implemented? Would they be specific to each scope or would there be a generic set of extended property commands? 

**Generic**
* [Add/Remove/Get/Set]-DbaExtendedProperty

**Specific**
* [Add/Remove/Get/Set]-DbaDbExtendedProperty
* [Add/Remove/Get/Set]-DbaLoginExtendedProperty
* [Add/Remove/Get/Set]-DbaDbUserExtendedProperty
* ...

**Comment by wsmelton** [comment]
Since in SMO I believe these are all based on one calls it would fall into the generic and then we may have to have an Object parameter that specifies which one you are dealing with... https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.extendedpropertycollection

However, doing this in SMO will likely be good bit of work considering there are likely no examples out there in docs. So if we go the T-SQL route it will still be generic because you only deal with one stored procedure: [sp_addextendedproperty](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql)

**Comment by wsmelton** [comment]
I could see us making it easier on the user because the LevelTypes on that stored proc only accept a certain value based on what object. So we could have an ObjectType parameter and then ask for the name of it, then auto-fill in all the level parameters? You could either accept  a multi-part name (e.g. database.dbo.table) or we'd have multiple parameters to accept each one, but I see that as complex.

**Comment by awickham10** [comment]
I did some more research on this. Turns out the SqlSmoObject has an ExtendedProperties property which makes the implementation of this pretty easy (see Example Code below) so it's just a matter of how to design it. Let me know what you think about my proposal below.

## Proposal
- Single set of commands named `Get-DbaExtendedEvent`, `Set-DbaExtendedEvent`, `Add-DbaExtendedEvent`, `Remove-DbaExtendedEvent`
- `ObjectType` parameter with the below valid values (or some form of them)
  - AGGREGATE
  - ASSEMBLY
  - COLUMN
  - CONSTRAINT
  - CONTRACT
  - DATABASE
  - EVENT NOTIFICATION
  - FILEGROUP
  - FUNCTION
  - INDEX
  - LOGICAL FILE NAME
  - MESSAGE TYPE
  - PARAMETER
  - PARTITION FUNCTION
  - PARTITION SCHEME
  - PROCEDURE
  - QUEUE
  - REMOTE SERVICE BINDING
  - ROUTE
  - RULE
  - SCHEMA
  - SERVICE
  - SYNONYM
  - TABLE
  - TRIGGER
  - TYPE
  - VIEW
  - XML SCHEMA COLLECTION

## Example Code
### Get Database Extended Properties
```powershell
# database level
$smo.Databases['WideWorldImporters'].ExtendedProperties['MyExtendedProperty']

# table level
$smo.Databases['WideWorldImporters'].Tables[0].ExtendedProperties['Description']
```

**Creating Extended Property**
```powershell
$extendedProperty = New-Object Microsoft.SqlServer.Management.Smo.ExtendedProperty ($parent, 'Description', 'This is my description')
$extendedProperty.Create()
```

**Removing Extended Property**
```powershell
$smo.Databases['WideWorldImporters'].ExtendedProperties['Description'].Drop()
$smo.Databases['WideWorldImporters'].ExtendedProperties.Refresh()
```

**Updating Extended Property**
```powershell
$extendedProperty = $smo.Databases['WideWorldImporters'].ExtendedProperties['Description']
$extendedProperty.Value = 'MyNewValue'
$extendedProperty.Refresh()
```

**Comment by potatoqualitee** [comment]
ohhh that is so fantastic. i love it. sorry for the delay, been on vacation 🇨🇦 🍟 

a `-Type` parameter with a validateset would be great. I'm not so sure about the name tho. Did you mean to say ExtendedEvent? I associate that with XEs. Also, are there any extended properties not associated with Databases? If not, can we go with `-DbaDbExtendedProperty`

Any interest in blogging about the set of commands after they are done for dbatools.io/blog?

**Comment by awickham10** [comment]
> ohhh that is so fantastic. i love it. sorry for the delay, been on vacation 🇨🇦 🍟
> 
> a `-Type` parameter with a validateset would be great. I'm not so sure about the name tho. Did you mean to say ExtendedEvent? I associate that with XEs. Also, are there any extended properties not associated with Databases? If not, can we go with `-DbaDbExtendedProperty`
> 
> Any interest in blogging about the set of commands after they are done for dbatools.io/blog?

Definitely did not mean ExtendedEvent! I'll take a further look to see if any reside outside a database and get back to you. I'd love the opportunity to throw out an article when they're done, thanks!
