### ISSUE TITLE
Start-SqlMigration / Copy-SqlDatabase -WhatIf does not test share accessibility

### ISSUE THREAD

**Issue by amandadebler** [sqlcollaborative/dbatools#291]
I made a share on the destination server, and until I added the SQL Server service account to read access on it, Copy-SqlDatabase (and Start-SqlMigration) would write the backup files from the source databases, but was denied read access for the restore to the destination server.

-WhatIf should test read accessibility for the network share.

**Comment by ctrlbold** [comment]
Hey Amanda,
Because it uses SQL Server Service accounts, it's kinda hard to test, but we do currently attempt to do so.

Within Copy-SqlDatabase, we use Test-SqlPath (which uses SQL Server's built in procedure,  master.dbo.xp_fileexist ).

    if ($NetworkShare.Length -gt 0)
    		{
    			if ($(Test-SqlPath -SqlServer $sourceserver -Path $NetworkShare) -eq $false)
    			{
    				throw "$Source cannot access $NetworkShare"
    			}
    			
    			if ($(Test-SqlPath -SqlServer $destserver -Path $NetworkShare) -eq $false)
    			{
	    			throw "$Destination cannot access $NetworkShare"
    			}
    		}

Unfortunately, if that doesn't throw an error, I don't think there is a straightforward way around it that SQL offers.

**Comment by wsmelton** [comment]
You could throw in running `RESTORE HEADERONLY FROM DISK...` command. It would try to access and actually read the backup file. It would throw the proper error of access if it is not there for the file.

**Comment by wsmelton** [comment]
Also consider that xp procs can be disable for some environments, be good to have some other method to use. Even just `Test-Path` as a last resort maybe, supported in PS 3.0+.

**Comment by ctrlbold** [comment]
RESTORE HEADERONLY FROM DISK seems like a waste is if it's just doing the same thing as a restore anyway. 

Good call on the xp being disabled, I'll make it throw a warning. Copy-SqlDatabase does a check using Test-Path but it just throws a warning since it's totally possible for the PS process to not have access but the SQL Service account does.

**Comment by wsmelton** [comment]
True, but header only does not try to load the file. So it might actually return a failure in a second where doing the restore doesn't.

Seem to recall I've had this happen before where restore command took a few seconds more to fail than just header only.

**Comment by niphlod** [comment]
this is closely related to https://github.com/sqlcollaborative/dbatools/issues/449

**Comment by potatoqualitee** [comment]
Yeah, we do what we can to the best of our ability and it's skipped if it's not genuinely accessible and thus causing failure which is caught later on in the script

````
if ($(Test-DbaSqlPath -SqlInstance $sourceServer -Path $NetworkShare) -eq $false) {
				Write-Message -Level Warning -Message "$Source may not be able to access $NetworkShare. Trying anyway."
			}
			
			if ($(Test-DbaSqlPath -SqlInstance $destServer -Path $NetworkShare) -eq $false) {
				Write-Message -Level Warning -Message "$Destination may not be able to access $NetworkShare. Trying anyway."
			}
````
