### ISSUE TITLE
Import-DbaCsvToSql: add TextQualifer parameter

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#2972]
## Feature Request

Add a parameter called `-TextQualifier` (to match the nomenclature in SSIS packages that use Flat File Connection Managers) that will parse the CSV's data values ignoring the text qualifier. Usage would be similar to `-Delimiter` parameter, in that you tell it what the text qualifier is like '"' (that's double quote wrapped in apostrophes).

In some CSVs, there are text qualifiers wrapped around data values, particularly when a comma or (other delimiter) is included in the data, similar to escape characters.

Example data value: `"1,234"` versus `1,234`.
A raw CSV file would contain a value, INCLUDING THE DOUBLE QUOTES, around the data like "1,234" but `Import-DbaCsvToSql` interprets that comma as the `-Delimiter`, and therefore erroneously thinks the 234 is the next column's data value. In this example, the data that should be inserted into the SQL table is 1,234 (without quotes, with the comma).

We see errors like this when this process fails:

```
WARNING: The following line (2) is causing issues:
00010158
1468
644
599
"1
093"
"3
068"
946
"1
```
```Import-DbaCsvToSql : Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Cannot find column 14.""```

The `-TextQualifer` should not assume that all values have the text qualifier. For example, some values may not have the "double quote"s around the value, such as 3 digit values like 599 might not be wrapped in "599".

**Comment by gbargsley** [comment]
+1 to this as I just had the same issue I had to work around.

**Comment by wsalzman** [comment]
+1 also happens to my... but... I find that -Safe doesn't seem to throw an error but it only reports that it copies rows up to the error row with a comma in it.  (which is my first row.  so I get 338570 rows will be copied  1 total row copied  while using the -Safe parameter but no rows are actually copied... value in row 1 column 2 = "Company Name, Inc."

**Comment by wsalzman** [comment]
I see that the code checks for quoted identifiers and handles them if it finds them, but it looks like it just checks the last line of the csv and if there are no quoted identifiers there then it assumes none of the rows have them... Could we just add a switch like -HasQuotedIdentifiers that would set that test to true always (at the cost of some speed) to handle those cases?   lines 1105 - 1135 in the ps1

**Comment by wsalzman** [comment]
also, i'm not sure but would this catch a column like "Company Name, INC" or would the  $checkcolumns = $checkline.Split($InternalDelimiter) break up that ^^ into two columns in $checkcolumns?  i.e. "Company Name        and            INC"  neither of which would set $quoted = $true

                    $quoted = $false
                    $checkline = Get-Content $file -Last 1
                    $checkcolumns = $checkline.Split($InternalDelimiter)
                    foreach ($checkcolumn in $checkcolumns) {
                        if ($checkcolumn.StartsWith('"') -and $checkcolumn.EndsWith('"')) {
                            $quoted = $true
                        }
                    }

**Comment by MaPa39** [comment]
+1 to this 
PS C:\Windows\system32> Import-DbaCsvToSql -Csv BI_SourceCSV.csv -SqlInstance XXXXXX-db -Database XXXX -FirstRowColumns
[*] Started at 10/25/2018 11:06:35
[*] Calculating column names and datatypes
[*] Logging into uhsm-dmi-db as Windows login uhsm\svc-mupatel
[*] Database exists
[*] Table exists
[*] Starting bulk copy for BI_SourceCSV.csv
WARNING: The CSV file appears to use quoted identifiers. This may take a little longer.
WARNING: The following line (4) is causing issues:
4
"YYYYYYYY"
01010101
"Harold Wilson Street"
"Progressing well, can discontinue soon."
WARNING: The import has failed, likely because the quoted data was a little too inconsistent. Try using the -Safe parameter.
Import-DbaCsvToSql : Exception setting "Item": "Exception calling "set_Item" with "2" argument(s): "Cannot find 
column 5.""
At line:1 char:1
+ Import-DbaCsvToSql -Csv S:\CO-IT-Development\DataSets\BI_SourceCSV.csv -SqlInsta ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-DbaCsvToSql
 
[*] 4 total rows copied

**Comment by potatoqualitee** [comment]
This should be fixed in the next release. please let me know if it's not. the parameter wasnt added but the parsing was changed drastically. or you can try from dev now and let me know.
