### ISSUE TITLE
Copy-SqlLogin - Allow choice of default database

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#303]
Allow choice of default database when "source instance" database isn't available

Adding a parameter to allow default database to be either master or tempdb could be good. Frankly I'd rather give a login access to tempdb than to master, in general.

Request from Steve Armistead

**Comment by ConstantineK** [comment]
Working on this in https://github.com/sqlcollaborative/dbatools/tree/add-defaultdb but realized a few issues that will take a bit more time to address:

1. Copy-SqlLogin can sync, update, or export your logins.
2. If you are exporting logins you dont know if the database (that by default your user has set) exists, so added dynamic sql to pick the default db as your override if the user's db doesnt exist. 
3. I think I can probably avoid most of this work in the other pieces because the other scripts touch the destination server (and so I can check if it exists or not and replace.)

**Comment by niphlod** [comment]
see also #295 . I'm keeping this and closing that so we can move forward.

**Comment by SQLDBAWithABeard** [comment]
Can we have a default of 

> sysadmins - default database master - as if SQL is available master should be available
> 
> None-sysadmins - specific database if absolutely needed otherwise tempdb as if SQL is available for normal users then tempdb should be available and also this mitigates users being unable to logon when their default database is moved from the server or becomes unavailable when they only need to access a different database and also mitigates the risk of users creating objects in or accessing the master database should further permissions allow them to when they "forget" to use the USE [DB} statement
> My suggestion use tempdb as default database if default database does not exist

or is a choice better?
