### ISSUE TITLE
Re-add support for localdb

### ISSUE THREAD

**Issue by TheOtherTimDuncan** [sqlcollaborative/dbatools#3215]
## Bug Report

#2771 actually removed support for localdb

### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version):  Windows 10.0.16299 
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): LocalDb any version (See https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-2016-express-localdb)

## Steps to Reproduce

Attempting to connect to a local instance of LocalDb using any command returns a "Cannot connect to localhost\instance"

**Comment by potatoqualitee** [comment]
Thanks for self assigning, Fred! And thanks for reporting, Tim 👍🏻

**Comment by FriedrichWeinmann** [comment]
Heya, fix is submitted, worked well in local testing: https://github.com/sqlcollaborative/dbatools/pull/3219

Note: This wasn't really an error committed on the PR listed above, but an omission in the interpretation (before that, it wouldn't work at all). Basically, that PR added support for _ConnectionStrings_ targeting thus, but omitted straight `(localdb)\instancename` (due to some reason I can't remember, I probably plain messed up there and forgot to do it right to the end).

Whatever the reason back then, unless the tests bomb, this should do the trick.

**Comment by niphlod** [comment]
closed via #3219
