### ISSUE TITLE
Get-DbaSpConfigure Does not show Config setting for "backup checksum default"

### ISSUE THREAD

**Issue by mvillegascuellar** [sqlcollaborative/dbatools#3237]
### General Troubleshooting steps

- [x ] Verified running the latest release of dbatools?
- [x ] Verified errors are not related to permissions?
- [x ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - SQL Server (Edition|Version): SQL Server 2014 Developer Edition

## Steps to Reproduce
Get-DbaSpConfigure -SqlInstance localhost | ft -AutoSize

**Comment by awickham10** [comment]
It looks like SMO doesn't expose that configuration setting which was added in SQL 2014. 

@potatoqualitee What's the protocol when the bug is outside dbatools? 

[https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.configuration.aspx](Microsoft.SqlServer.Management.SMO.Configuration)
