### ISSUE TITLE
Test-DbaDatabaseOwner with domain account - Insufficient hexadecimal digits

### ISSUE THREAD

**Issue by david-potts** [sqlcollaborative/dbatools#3311]
## Bug Report
When running Test-DbaDatabaseOwner to check all databases are owned by a listed domain account and error message is received: 

```
PS C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.0.3\checks> Test-DbaDatabaseOwner -SqlInstance T-DBA-DB-02 -TargetLogin 'UNI\unidbo'  
parsing "UNI\unidbo" - Insufficient hexadecimal digits.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.210\allcommands.ps1:76106 char:17
+             if (($server.Logins.Name) -notmatch $TargetLogin) {
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```

This is followed by output showing the database owner for all databases and 'OwnerMatch' appears to be correctly evaluated. 
 
The syntax used is as suggested in example 2 of the cmdlet help.

### General Troubleshooting steps

- [Y] Verified running the latest release of dbatools? dbatools 0.9.211
- [Y] Verified errors are not related to permissions? Account used is Windows Administrator and SQL Server sysadmin
- [Y] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2 Datacenter
 - PowerShell Version: 5.0
 - SQL Server (Edition|Version): SQL Server 2016 Standard Edition (SP1)

## Steps to Reproduce
See above. 
Screenshots attached below :

![output](https://user-images.githubusercontent.com/29427364/36739910-05d98148-1bd9-11e8-85d5-713fc04dcd79.jpg)
![versions](https://user-images.githubusercontent.com/29427364/36739911-05f20ace-1bd9-11e8-9701-d014d4d38890.jpg)

Get-DbatoolsLog output:
![dbatoolslog](https://user-images.githubusercontent.com/29427364/36740046-4587145e-1bd9-11e8-9e8b-f137ddb7f861.jpg)

**Comment by potatoqualitee** [comment]
Great report! Thanks @david-potts 

looking into this now

**Comment by wsmelton** [comment]
Figured out this is not necessarily an issue of escaping @potatoqualitee it is because we have the order wrong on the if statement.

`if (($server.Logins.Name) -notmatch $TargetLogin)`

This is comparing an array to a single value which is why it will always return true, even if the login exist in that array. This should be reversed to compare the single value to the array object.

`if ($TargetLogin -notmatch $server.Logins.Name)`...I've hit this in another command sometime back and had that pointed out. While the regex method works, not sure it is the proper way.
