### ISSUE TITLE
 Get-DbaLastBackup and DbaBackupHistory -LastFull potentially wrong results

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3321]
hello,
I received this email from a user. Please take a look at your convenience. Thank you very much.

```
I went to SQLBits last week and saw Chrissy and Robs presentation on DBATools.

Very eager to replace our old scripts with nice shiny DBATools and have been testing some of the commands.

In our environment, Get-DbaLastBackup and DbaBackupHistory -LastFull showed the wrong full backup for master database (showed one from 2015!)

Looks like the underlying tsql script sorts the backups on lsn and date to determine the last backup.  In our environment, the lsn in 2015 was higher than it is now (guess some restore or something happened then) so it returned that one.  I know... we shouldn't have history going back that far!

If I run the tsql script with the ranking changed to
RANK() OVER (ORDER BY  backupset.backup_finish_date desc, backupset.last_lsn desc ) AS 'BackupSetRank'
instead of the other way round it returns the right one.

Not sure if that's a bug..
```

**Comment by Stuart-Moore** [comment]
I think that's a real edge case. I'd be more worried on general dbs (UK at least) there'll be at least one hour a year where that'd potentially fail (clocks go back, 3am happens twice, last LSN wins).

Do you have contact details for the user? Might be worth getting the values. In the Restore stuff I check the RecoveryForkID which should let you work out if you're restoring the latest restore chain as well, that could be worth porting across.

The only way the old LSN can be higher is because someone has restored another database over the top. At this Backup history is completely FUBARed and really should be removed as it's no longer related to reality (IMHO)

Could be a justification for  a Remove-DbaOldBackupHistory command as well ;)

**Comment by potatoqualitee** [comment]
Thanks so much for the explanation. I've reached out to the guy and asked him to respond!

**Comment by Zhunya** [comment]
@Stuart-Moore What you think about using `backup_set_id` as sorting key, he is unique for server and sequential?

**Comment by niphlod** [comment]
solved via https://github.com/sqlcollaborative/dbatools/commit/18545f2366b2f653c7678c5027628d5e6b84d744
