### ISSUE TITLE
Get-DbaSqlService (now Get-DbaService), SSRS 2017, No ComputerManagement Namespace

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#3349]
### General Troubleshooting steps

- [x] Verified running the latest release of dbatools?
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012 R2, Windows Server 2016
 - PowerShell Version: 5.1.14409.1005
 - SQL Server (Edition|Version): SSRS 2017 Enterprise, October 2017 release

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [x] Attach output from PowerShell console (if possible/allowed)

"WARNING: [Get-DbaSqlService][15:08:35] No ComputerManagement Namespace on [servername]. Please note that this function is available from SQL 2005 up."

## Feature Request

If possible, would like to be able to successfully use Get-DbaSqlService (now Get-DbaService) against a target which has only SSRS 2017 installed (no other SQL Server components installed).

### Problem to solve
Get-DbaSqlService (now Get-DbaService) doesn't currently work against a target which hosts only stand-alone SSRS 2017.

### Additional information

Perhaps the needed WMI provider or namespace is not created when SSRS 2017 is installed stand-alone on a server on which no other SQL Server components have been installed?

**Comment by wsmelton** [comment]
This is because SQL Server Configuration Manager can not be used to manage SSRS 2017+. When you install it there is a new namespace added `ReportServer`.

![image](https://user-images.githubusercontent.com/11204251/37068686-8a8df044-2175-11e8-970c-b4c3e229ce36.png)

![image](https://user-images.githubusercontent.com/11204251/37068644-5458a99c-2175-11e8-8349-0be782daba24.png)

![image](https://user-images.githubusercontent.com/11204251/37069226-16976802-2178-11e8-8cda-e15a4cb4bf93.png)

Whomever is up to the task will need to update the command(s) to look for this namespace, still considering the version (right now we just have 14 but it will go up):

However @potatoqualitee we are going to need to determine what DLLs need to be added to support this now. I'm not positive but it may be these DLL files:

![image](https://user-images.githubusercontent.com/11204251/37068763-eaf3b1c6-2175-11e8-90ab-2aad15abe662.png)

Or all the the different language files:

![image](https://user-images.githubusercontent.com/11204251/37068776-063cefc4-2176-11e8-863c-995cbf8f835e.png)

Or there is potential to get files from [ReportingServicesTools](https://github.com/Microsoft/ReportingServicesTools/) ? Where I figured out what the [right classname was to use in above screenshots](https://github.com/Microsoft/ReportingServicesTools/blob/fdb2d7442f73b40a3c570684f2abfc55c3f27851/ReportingServicesTools/Functions/Utilities/New-RsConfigurationSettingObject.ps1#L88)

**Comment by wsuhoey** [comment]
I believe a potential fix is to add an entry for `SQLServerReportingServices` to this line in Get-DbaService:

```if ($service.ServiceName -in ("MSSQLSERVER", "SQLSERVERAGENT", "ReportServer", "MSSQLServerOLAPService"))```

Because the `ServiceName` changed for SSRS 2017 (and maybe SSRS 2016 too, unconfirmed).

**Comment by nvarscar** [comment]
Actually, Start/Stop services already work with Win32_Service, so that's cool. Only the first question is relevant.
