### ISSUE TITLE
Copy-DbaDatabase  Backup failure Files Headers Could Not be Read

### ISSUE THREAD

**Issue by rjoflorida** [sqlcollaborative/dbatools#3377]
### General Troubleshooting steps

- [X] Verified running the latest release of dbatools?
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version:  

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10240  17709  

 - SQL Server (Edition|Version): SQL Server 2016 Dev 13.0.4001.0

## Steps to Reproduce

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach logs generated by dbatools (`Get-DbatoolsLog`)
 - [X] Attach output from PowerShell console (if possible/allowed)

### Problem to solve
Solve issue of backup and restore failures on some databases on server.  Several other databases on this same server migrated with no issues.

**Comment by rjoflorida** [comment]
When I migrate using Copy-DbaDatabase or Start-DbaMigration some databases migrate or copy succesfully.  However, I have a few databases that fail to migrate due to the error below.  This is from a SQL 2016 to SQL 2016 database copy.

WARNING: [Backup-DbaDatabase][10:24:38] Backup Failed:  Exception calling "SqlBackup" with "1" argument(s): "Backup failed for Server 

WARNING: [Restore-DbaDatabase][10:24:38] No backups passed through. 
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue

**Comment by niphlod** [comment]
Do you by any chance have a database with the same name of another one that got dropped in the past ?

**Comment by rjoflorida** [comment]
These were new databases on the target server.

**Comment by niphlod** [comment]
was talking about the source server

**Comment by ChristopherSerre** [comment]
Hi.
I also have the exact same problem sometimes when using Copy-DbaDatabase with version 0.9.307 (it worked in 0.8.x)).
I’m not sure how you collect the info about the backup file that will be used for Restoring on Target, but my guess it’s how you do it that’s causing the problem in some cases.
The error message says that the file that will be used for Restore “cannot be read”.
WARNING: [Test-DbaBackupInformation][17:03:13] Backup File \\Userdata4001\sql_migrering$\Serres_Test_201803231655-3-of-3.bak cannot be read 
The file name is incorrect and the script looks for an older file that does not exist anymore which is casing the problem.
The problem seems to occur when a NEW database is setup on the Source server with the exact same Name as an earlier Database (Database GUID is different)!
This “solves” my problem when cleaning up in MSDB for my Database with the problem.
exec msdb..sp_delete_database_backuphistory @database_name = 'Serres_Test'  
I hope you will find a fix for this soon.
Thank you for a very good tool for us DBA’s!

**Comment by niphlod** [comment]
Happy to be not the only one with the issue: we need to tune the backuphistory query a bit because we order by LSN,date (for a set of valid reasons) so it *may* happen that the wrong Last backup spec is fetched

**Comment by potatoqualitee** [comment]
ahhh this is the thing that's been driving me crazy on that test. looking fwd to the fix!

**Comment by potatoqualitee** [comment]
This may also be the problem of the on again, off again failures

https://ci.appveyor.com/project/sqlcollaborative/dbatools/build/0.9.11681/job/0uhhs2loch3pdwkv

**Comment by niphlod** [comment]
fixed some time ago
