### ISSUE TITLE
Remove-DbaRemoveOrphan not excluding valid user ModuleSigner in SSISDB

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3443]
Hello,
I see now with the current upgrades that the remove-DbaRemoveOrphan users is not being utilized.
It seems with this function the SSISDB permissions used to execute SSIS packages.
So I thought it might be a good idea to log it with you guys so that it can be mentioned for other people in case they, too remove the SSIS permissions needed to execute jobs (woopsy) I got a lot of interesting emails afterwards.

Thank you so much!

/cc @ClaudioESSilva

**Comment by wsmelton** [comment]
I'm not sure I follow what the issue is in that email?

**Comment by potatoqualitee** [comment]
i interpreted it that there was a system user that appeared orphaned that actually wasnt?

**Comment by cfradenburg** [comment]
I poked in one of our SSISDB systems and it looks like AllSchemaOwner is a stock SSISDB user with no login and many of the SSIS procs have "WITH EXECUTE AS 'AllSchemaOwner'" in them.  Dropping that user would certainly cause issues from what I'm seeing.

**Comment by ClaudioESSilva** [comment]
I will take a look on this later.
But, users without login should be skipped by the filter on
https://github.com/sqlcollaborative/dbatools/blob/development/functions/
Remove-DbaOrphanUser.ps1#L172 maybe an edge case :-)

**Comment by ClaudioESSilva** [comment]
Btw,@potatoqualitee <https://github.com/potatoqualitee> can you confirm
with the sender he/she was using the latest dbatools version?
Thanks!

**Comment by potatoqualitee** [comment]
hey @ClaudioESSilva - any chance you can take a look at this within the next week?

**Comment by wsmelton** [comment]
I can confirm this is indeed a bug.

You are picking up the `moduleuser` cert user in SSISDB that is used for signing the module within SSIS.

```powershell
PS C:\Windows\system32> Remove-DbaOrphanUser -SqlInstance sqlvm -Database ssisdb -WhatIf -Verbose
VERBOSE: [13:57:27][Remove-DbaOrphanUser] Validating users on database [SSISDB].
VERBOSE: [13:57:27][Remove-DbaOrphanUser] Orphan users found.
VERBOSE: [13:57:27][Remove-DbaOrphanUser] User [ModuleSigner] does not own any schema. Will be dropped.
What if: Performing the operation "Dropping user [ModuleSigner]" on target "SSISDB".
```

This line appears to be what you need to address because there is no login for this user:

https://github.com/sqlcollaborative/dbatools/blob/9b43322cd5d0e7785d20b0c4a1ede412b0b5c15c/functions/Remove-DbaOrphanUser.ps1#L157

```powershell
PS C:\Windows\system32> Get-DbaDbUser -SqlInstance sqlvm -Database ssisdb | where Name -eq 'ModuleSigner'


ComputerName       : cma-cac1-sqlvm
InstanceName       : MSSQLSERVER
SqlInstance        : cma-cac1-sqlvm
Database           : SSISDB
CreateDate         : 4/30/2016 12:46:16 AM
DateLastModified   : 4/30/2016 12:46:16 AM
Name               : ModuleSigner
Login              :
LoginType          : Certificate
AuthenticationType : None
State              : Existing
HasDbAccess        : True
DefaultSchema      :
```

**Comment by ClaudioESSilva** [comment]
Thanks for the analysis @wsmelton.
The problem here is the `LoginType`. I was just looking for the `SQL user without login` to be excluded but the `user mapped to a certificate` also need to be excluded from here.

I mentioned you on the PR so you can test and accept only after that.

Thanks in advance.

@cfradenburg if you would like to test it and give your "OK" too, we appreciate.
