### ISSUE TITLE
Get-DbaPermission feature request

### ISSUE THREAD

**Issue by SQLDBAWithoutABeard** [sqlcollaborative/dbatools#355]
Please can Get-DBAPermission be extended to output server and database role level permissions such as DBOwner, db_datareader, db_datawriter, db_executor?
Many thanks
Andy

**Comment by PowerDBAKlaas** [comment]
The permissions on the fixed server and databaseroles are documented here:
https://technet.microsoft.com/en-us/library/ms175892(v=sql.105).aspx
https://technet.microsoft.com/en-us/library/ms189612(v=sql.105).aspx

We can list the permissions for fixed roles, but apparently not the permission_state (GRANT or DENY).
So far, there's the choice between querying those permissions and leaving permstate blank, or adding the permissions with permstate hardcoded to the query.

**Comment by niphlod** [comment]
hum. is it an issue even with Copy-Sqllogin and Sync-SqlLoginPermissions ?

**Comment by PowerDBAKlaas** [comment]
@niphlod what do you mean?

**Comment by niphlod** [comment]
meaning that from where I stand get-dbapermission and sync-sqlloginpermissions, which is the base for copy-sqllogin, are two faces of the same medal, one done via T-SQL and the others via SMO.

If the permission_state is not retrievable "as documented (by technet)" I guess if the same pickle can/could also be an issue (a not tested one?) of the sync-sqlloginpermissions and copy-sqllogin "editions".

**Comment by PowerDBAKlaas** [comment]
@SQLDBAWithABeard @SQLDBAWithoutABeard @ctrlbold @dansqldba can you give your opinion on this, please?
As far as I can find, we have 3 options:
1. query the permissions of fixed roles, and not have the permission state ( Grant | Deny )
2. add a hard coded list of permissions as found in the TN documentation
3. not include the fixed roles permissions

my idea:
1. is rather useless, knowing if it's a Grant or Deny makes all the difference. At server level, it seems to be all Grants (for now), but at the DB level both exist.
2. is most complete solution, but may become outdated and give wrong information in future versions if we don't follow this up. (if we choose this solution, I would add a switch -IncludeFixedRoles)
3. the easiest, most reliable choice, but of course missing some info.

**Comment by SQLDBAWithABeard** [comment]
My understanding is that what was required was to be able to output the list of permissions granted to a user - IE if they are a member of the securityadmin role and the db_datareader role as well as the explicit permissions that were granted. I agree that it is difficult to out put the permissions of those roles but role membership is what I think was required

**Comment by PowerDBAKlaas** [comment]
Role membership is in Get-DbaRoleMembership,
explicit permissions to every principal except the fixed roles is in here.
I'm also looking at listing the members of Windows Groups in another function.

The combination of the three functions could result in a complete overview in the end.
I'm experimenting with both a script, and a t-SQL query. t-SQL will be the fastest I guess, since joins on the sql server side should be a lot faster than nested foreach loops in a script. The downside may be that we have an additional function to return the whole security model, and the current functions to do a part of that.

Still, the 4th pilar for both could be the fixed role permissions, and the question remains.

But for your client, @SQLDBAWithABeard , could it suffice to see that a user has granted write permission on tableA and is member of the deny_dbwriter role in the DB? It's in this case not hard to guess that this role has deny write on all securables in the DB.
There's of course also the possibility that one permission is granted to a user, and another to a group to which the user belongs.

Automated conclusions on what's the resulting effective permission demand some more complicated statements, and can be implemented in yet another script or function. ( I found a great stored procedure last week, and I'm studying that one now)

**Comment by potatoqualitee** [comment]
@SQLDBAWithABeard can you please let @PowerDBAKlaas know your preference. I have no opinion here :(

**Comment by SQLDBAWithABeard** [comment]
OK @PowerDBAKlaas what the client expected to get from Get-DBAPermission was not only the specific granted permissions but also the role membership as well instead of having to get the role membership separately and then trying to combine the results which they struggled with but we resolved for the report that was requested

I think that what you suggest is a good idea

Over arching Get-DBAPermissions

Calling 
Get-DBARoleMember to get role membership
Get-DBAPermission for explicit permissions
Get-DBARolePermissions (?) for user server or database role permissions

Possibly Making use of Find-DbaLoginInGroup in a filter (although that gets messy and large real quick)

**Comment by PowerDBAKlaas** [comment]
This is 8 months ago, I'll have to look work myself into it again. I feel strongly that DbaPermission should get the permissions, and DbaRoleMember gets role members. Those functions should be what they are now. 
I now feel it may be best to add the fixed roles hard coded anyway, since it's the only way to get them and otherwise, well, we won't have them.

About the 'second layer', I got some ideas on the 24 HoP in may, about security.
It's not easy, but it could eventually lead to a `Get-DbaSecurity` ?
As a next step, I will look at a combination of Roles and Permissions.
Adding the group memberships will indeed be a complex undertaking.

**Comment by SQLDBAWithABeard** [comment]
Closing as future improvements will improve this
