### ISSUE TITLE
New Command: Set-ClusterPermissions

### ISSUE THREAD

**Issue by jdanton** [sqlcollaborative/dbatools#3552]
## Feature Request

Grant permissions to a newly created Windows Server Failover Cluster Active Directory Virtual Computer Object to create new computer requirements. This process is current manual, and as far as I know not possible through Active Directory's PowerShell module.

**Comment by allanhirt** [comment]
https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adcomputer?view=win10-ps

You'd only use this if prestaging objects. If permissions are given, it's not a big deal.

**Comment by allanhirt** [comment]
New/Set-ADComputer should work if you give the CNO rights on the OU. What Joey is asking is if that isn't the case. Here's one way to do it in PS, but it's not a single command.

https://blogs.msdn.microsoft.com/adpowershell/2009/10/13/add-object-specific-aces-using-active-directory-powershell/

**Comment by wsmelton** [comment]
This would be our of scope for the modules.

**Comment by potatoqualitee** [comment]
I do err on the side of "if jdanton takes time to suggest it, it's probably needed" but admittedly, I'm biased and like features ;) 

I see this as similar to the Firewall commands that were approved; it is something that I've encountered myself and would be nice to have in a single command, especially because the scope is reasonable and reduces the possibility of mucking up AD since it's automated. We do have `Grant` as an approved Verb in PowerShell, is that more appropriate?

We are sorely lacking in clustering commands and I'd appreciate this functionality being available as well.

**Comment by wsmelton** [comment]
I'm going to close this one @potatoqualitee because I don't feel this in-scope for the module, even after the cluster commands have been built. If you feel it is by all means open it back up.

For a user to even have rights to modify these permissions requires delegation control, and if they have that correctly configured, they can handle this with the AD module. This has nothing to do with cluster permissions directly, it is AD permissions for an AD object.
