### ISSUE TITLE
Restore-DbaDatabase, smarter checks when -MaintenanceSolution is passed

### ISSUE THREAD

**Issue by digitalohm** [sqlcollaborative/dbatools#3704]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

* When there are multiple full backup files in the directory there should exist a flag so that the most recent is the one picked for reading headers.  This is using the -MaintenanceSolution flag.  

We've run into the error: 

BackupDiskFile::OpenMedia: Backup device '\\a\storage\path\adb\LOG\adb_LOG_20180529_073009.trn' failed to open. Operating system error 2(The system cannot find the file specified.).

The file does not exist, because it is outside the retention window for whatever backup file is being read.  If the most recent file was read log backups would still exist.

### Proposed technical details (if applicable)

* In recent testing we found that multiple full backup files will cause some issues where all the files are read.  For example restoring the transaction logs could fail if your retention time is not encompassing the entirety of the headers on each backup file?  (still a little foggy on this)

If a new flag could be introduced that gets the most recent backup file based on date created that might be useful to avoid this situation.

### Latest version of dbatools as of writing

* latest

**Comment by Zhunya** [comment]
Please, can you give us examples in which you got errors in restore process.

We still have one nasty bug in Test-DbaBackupInformation (I maybe wrong on
exact name) some times it's gives errors in LSN chain, but SSMS builds
chain just fine on same files set.

**Comment by potatoqualitee** [comment]
`Get-DbaBackupHistory -Last -SqlInstance sql2017 -Database dbatoolsci_agroup | Restore-DbaDatabase -SqlInstance sql2017 -WithReplace` should also work

**Comment by niphlod** [comment]
halt. this doesn't reflect what was discussed on Slack. I will try to explain better because it actually makes sense ...

When restore-dbadatabase does not have info from history, but just the path, it resolves to scan each and every file and only AFTER it selects the chain (the process of selection and even the retrieval from msdb history can be buggy or not, but there are definitely other issues opened for those).
 
When -MaintenanceSolution is passed, and you want to restore to the latest PITR possible, Restore-DbaDatabase will scan, e.g., 7 FULLs stored in the FULL directory of Ola's default structure while it _could_ trust both the name and/or LastWriteTime. 
Namely instead of scanning everything (7 FULLs are not that much, but think 1k of incrementals), it _could_ trust:
- that the name of the file contains the "start date" of the backup
- that the lastwriteTime of the file itself contains the "end date" of the backup
As of now it doesn't trust anything other than what restore headeronly returns, at the cost of having to scan everything. If it could trust name and lastwritetime (speaking of ola's scheme), then to restore to the last PITR it _could_ : 
- list the FULL and pick the most recent
- list the DIFF and discard everything whose lastwritetime is less than the lastwritetime of the previously selected FULL (wanna be safe? throw in a leeway, but still cut something)
- list the LOG and discard everything whose lastwritetime is less than the lastwritetime of the previously selected DIFF (wanna be safe? throw in a leeway, but still cut something)
- etc.

**Comment by digitalohm** [comment]
I'm a little confused here, do you still want me to add my example scenario with error code?

**Comment by Zhunya** [comment]
Please don't add new switch, just change logic in `Get-DbaBackupInformation`
Tрis behavior, with Ola Maintenance Solution and RDD, discussed many times with Stuart, but he refused to implement it.

**Comment by digitalohm** [comment]
so are we saying that we should just use: 

Get-DbaBackupHistory -Last -SqlInstance sql2017 -Database dbatoolsci_agroup | Restore-DbaDatabase -SqlInstance sql2017 -WithReplace

or that this issue should be fixed somewhere else?  or that its not an issue?

**Comment by Zhunya** [comment]
@digitalohm this is one approach you can use:
```powershell

$gbh = Get-DbaBackupHistory -Last -SqlInstance sql2017 -Database dbatoolsci_agroup
$gbh | Restore-DbaDatabase -SqlInstance sql2017 -WithReplace -Trustbackuphistory

```

**Comment by niphlod** [comment]
we all get there are ways to speed up the process but one of the goodies of PS is (also) in this case to NOT have any recorded backup history whatsoever. There's really no point of having -MaintenanceSolution if you need to scan the whole fileset.
