### ISSUE TITLE
Add support for results of Get-DbaSqlService to [dbainstance]

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3775]
![image](https://user-images.githubusercontent.com/8278033/42448620-760305be-8319-11e8-9b49-6e62a6c2703c.png)

merci!

potentially @FriedrichWeinmann or @zippy1981 can take a look?

**Comment by FriedrichWeinmann** [comment]
Heya Chrissy,

could easily do this. In fact had already looked into it ... and decided against it!
Thing is: `Get-DbaSqlService` returns many objects if you do not properly filter it:
- Multiple services per instance (including default instance)
- Some global services for all instances

Important to note: `[DbaInstance]` can always only look at a single object and does not know what came before or what will come after. It also nly has two ways to react: Accept or fail with exception - it cannot silently skip an object.

So with regular usage, it would lead to multiple calls against the same instance.
If we limit it to a single legal service, I would be force to throw an exception against all others, since I cannot ignore them.

If you want to have support for a single specific service type - with the full awareness that all other service types will cause exceptions - I'll be happy to add that, just tell me the service type that is legal.

**Comment by zippy1981** [comment]
@FriedrichWeinmann for part of the answer, what if every object returned by `Get-DbaSqlService` set some sort of NoteProperty so that `Get-DbaDatabase` and other methods would know to skip those services?

Also, why must it throw, why not Write-Warning?

**Comment by FriedrichWeinmann** [comment]
> ... and other methods would know to skip those services?
Because that would need to be implemented in every single command. All 400+ of them and all the new ones. I do not consider this to be worth the effort - onetime and continuing forwards.

> Also, why must it throw, why not Write-Warning?
Because the parameter class is not a function and only has two ways to communicate: Throw an exception (= conversion failed) or don't (= conversion worked).
All current code works on that premise and assumption. Breaking this would break tons of commands.

Further note:
Please keep in mind that the parameter class is used for a lot more than just passing it towards `Connect-SqlInstance`, so attempts to manage that within that internal command are also non-applicable.

**Comment by potatoqualitee** [comment]
will close since it was decided against
