### ISSUE TITLE
Get-DbaAgReplica - Add custom property for secondary connections

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#3817]
### Summary of new feature

A bug that [has already been reported](https://feedback.azure.com/forums/908035-sql-server/suggestions/32902525-cannot-join-database-to-ag-using-gui-if-replica-sq) when dealing with an instance that is on a non-default port does not contain enough information to make a connection to that secondary just from the Name property.

A property would need to be added that looks up if there is a non-default port and then added to the property.

// @nvarscar 

### Proposed technical details (if applicable)

Add a property string that is basically `SqlInstanceName,port` from the secondary object. Only place the port is likely found is in the endpoint URL so may just string manipulation where we strip it out.

**Comment by nvarscar** [comment]
Endpoint URL points towards the hadr DATABASE_MIRRORING endpoint, which does not accept any connections other than AG synchronization, so that port is pretty much useless for our case. So far, I failed to discover a way of learning the custom TCP port of the secondary server in AG, except, maybe, WMI or CIM2 query to the secondary server - but that's not going to be trivial: somehow the script should be able to find the right network configuration item among all others and figure out which one is a correct one. I might try to dig in that direction, but that will probably turn the lightweight command into a heavy-lifter.

**Comment by nvarscar** [comment]
After spending some time researching the DMVs and SMO, I can only confirm that there is no information on what port the secondary instance(s) is listening on. If we're going to go with the road of assumptions, it should be something like this:
```powershell
try { Connect-SqlInstance -SqlInstance $SERVER\$INSTANCE }
catch {
  try { Connect-SqlInstance -SqlInstance $SERVER\$INSTANCE,current_listener_port } 
  catch {
    try { Connect-SqlInstance -SqlInstance $SERVER\$INSTANCE,current_connection_port } 
    catch { fail-miserably } 
  }
}
```
The other way around would be to use the ManagedComputer object and to get the current IP port from the remote machine(s):
```
$wmi = New-Object Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer($Computer)
$ips = $wmi.ServerInstances[$InstanceName].ServerProtocols['Tcp'].IPAddresses
$ports = $ips | ? { $_.IPAddress.IPAddressToString -in @('0.0.0.0',(Resolve-DbaNetworkName $Computer)) } |  % { $_.IPAddressProperties["TcpPort"].value }
if (!$ports) { 
  $ports = $ips | ? { $_.IPAddress.IPAddressToString -in @('0.0.0.0',(Resolve-DbaNetworkName $Computer).IPAddress) } |  % { $_.IPAddressProperties["TcpDynamicPorts"].value }
}
foreach ($portString in ($ports | ? { $_ } )) {
  foreach ($port in $portString.Split(',')) {
    try { $s = Connect-DbaInstance -SqlInstance "$Computer\$InstanceName,$port" }
    catch{ }
    if ($s) { break }
  }
  if ($s) { break }
}
$s.Name
```

**Comment by wsmelton** [comment]
Closing this as not supportable.
