### ISSUE TITLE
Get-DbaSpConfigure not returning all configurations in SQL 2017

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbatools#3822]
### Before submitting a bug report:

- [X ] Ensure you are able to reproduce it on the latest released version (_we release often_)
Script     0.9.375    dbatools 
- [ X] Verified this bug is not already reported in an issue
- [X ] Verified errors are not related to permissions
- [X ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

I was looking to check the clr strict security setting on a 2017 instance so I checked spconfigure and it was not available via dbatools

```powershell
<#
    Get-DbaSqlBuildReference -SqlInstance $instance | Select Build, NameLevel, SPLevel

(Get-DbaSpConfigure -SqlInstance $instance).Count

$query = @"
EXEC sp_configure 'show advanced options', 1
RECONFIGURE;
EXEC sp_configure
"@
(Invoke-Sqlcmd -ServerInstance $instance -Query $query ).Count

#>
```
![image](https://user-images.githubusercontent.com/6729780/42884425-36ad0e12-8a96-11e8-8172-356e8194a620.png)

```powershell
$PowerShellnames = (Get-DbaSpConfigure -SqlInstance $instance).DisplayName
$TSQLNames = (Invoke-Sqlcmd -ServerInstance $instance -Query $query ).Name Compare-Object $PowerShellnames $TSQLNames
````
![image](https://user-images.githubusercontent.com/6729780/42884670-d1a46866-8a96-11e8-8e44-d9ccf2f4a2af.png)

## Expected Behavior

The two outputs should be the same

## Actual Behavior

There are differences - 
access check cache bucket count =>
access check cache quota        =>
allow polybase export           =>
automatic soft-NUMA disabled    =>
backup checksum default         =>
clr strict security             =>
external scripts enabled        =>
hadoop connectivity             =>
polybase network encryption     =>

are not available in the dbatools command but are via T-SQL - I was looking to check the clr strict security setting

## Environmental data

 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2312
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2312
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - - SQL Server: 

 $query = "SELECT @@VERSION"
 (Invoke-Sqlcmd -ServerInstance $instance -Query $query).Column1
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)
        Aug 22 2017 17:04:49
        Copyright (C) 2017 Microsoft Corporation
        Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by sqllensman** [comment]
This is a more general case of issue raised in Issue #3237 

The problem is that Microsoft has again chosen to not consistently update the SMO library.

As per investigation in #3237 the missing values all have a value in the Configuration.Properties collection but don't have a matching property in Configuration class.

The issue is that the Name returned by Get-DbaSpConfigure is the Property name from Configuration class and does not exist for these missing configurations.

This name is only defined by the SMO class and is not actually part of information returned from sys.configurations, The name in sys.configurations is mapped to DisplayName in the Configuration.Properties collection while the name value seems to be a derived value with inconsistent rules.

To fix this bug the options would seem to be
(a) Base information solely on the data returned from the Configuration.Properties collection and either remove the name or use DisplayName as Name  (Breaking Change
(b) Add another internal utility function similar to Get-SqlDefaultSpConfigure that maps between DisplayName and Name and provides entries for the missing values.

**Comment by sqllensman** [comment]
Further investigation indicates that 
(a) The current SMO class being used not only does not include all Properties that are available in sys.configurations it also includes Properties that don't exist . Eg SqlMailXPsEnabled property was removed from SQL Server 2012 but still present in SMO.

(b) There seems 1 to 1 correspondence between the entries in sys.configurations and the Configuration.Properties collection. I haver tested on an instance of 2005 and higher.
For SQL Server 2000 the results of sp_Configure and Configuration.Properties collection also match.

(c) The utility class Get-SqlDefaultSpConfigure has a number of errors and does not match fully with values in sys.configurations. This results in in the values returned for IsDefault being inaccurate.

(d) As the description of the function is: "Returns all server level system configuration (sys.configuration/sp_configure) information" then using the incorrect / inaccurate names from the SMO Configuration class is not consistent with the stated purpose and is supplying information that is not part of either sys.configuration/sp_configure.

**Comment by wsmelton** [comment]
We have no control over what is returned or not returned by SMO. It will have to be decided whether we stick with SMO for the commands or move them to T-SQL for consistency.
