### ISSUE TITLE
Copy-DBALogin warn if copied across a sysadmin login

### ISSUE THREAD

**Issue by hfleitas** [sqlcollaborative/dbatools#3861]
---
name: Warning when Login Copied as sysadmin to destination :bomb:
about: enhancement
---

### Summary of new feature
Copy-DBALogin -Source Server1 -Destination Server2 -Login contoso\hfleitas, sqlapp1, readuser

Display...
Warning: sysadmin contoso\hfleitas copied to Server2 successfully. 

### Latest version of dbatools as of writing
0.9.382
* Please provide the latest released version of dbatools module.

**Comment by niphlod** [comment]
Why should it warn when you are the one requesting a copy?

Il mar 31 lug 2018, 17:08 Hiram Fleitas <notifications@github.com> ha
scritto:

**Comment by hfleitas** [comment]
because you dont know it was sysadmin to begin with and you just added a sysadmin to another box by and perhaps you would like to know about it so you can lower that login's permissions on the destination svr.

**Comment by niphlod** [comment]
If you have those concern you should check beforehand what login are you
going to copy. Remind that dbatools is all about tooling, and it's not
named dbasolutions for a reason (as in: there is no complete solution that
is ok for everyone). Another user may ask for a warning to be raised if a
login is dbcreator, and soon enough you have the output littered with
warnings.

Copy-item copies. That's what it is supposed to do and it warns if it is
unable to copy.
When you want to copy files between dirs, it doesn't warn you if there are
jpgs in it. If you want to know what is that you are going to copy, you
need to do a, e.g., get-childitem on the source. The same applies here:
copy- copies and any warning is only related to the good status of the copy
itself.
If your routine needs to know beforehand what sysadmin are being copied
because you wanna be stricter about them, do e.g. a get-dbaserverrole first.


Il 31 lug 2018 7:35 PM, "Hiram Fleitas" <notifications@github.com> ha
scritto:

because you dont know it was sysadmin to begin with and you just added a
sysadmin to another box by and perhaps you would like to know about it so
you can lower that login's permissions on the destination svr.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/3861#issuecomment-409304930>,
or mute the thread

**Comment by hfleitas** [comment]
I know what to do before-hand and after, plus how to pipe one function to another. This is just a feature enhancement recommendation to make the tool better. Some of the other functions in the project already do this very well without having to call multiple ones, and we don't consider that littering its actually very useful information that can be controlled by another context switch/param (-Show None). I still think it would be of help to have this enhance and I get your point. Not asking to rename the project nor a solution to a problem. Again, it's an enhancement recommendation. The copying part works great, the enhancement isn't to prevent that copy nor slow it down beforehand. We're not talking about copying files, the comparison is irrelevant. This is about copying a sysadmin login. If it were possible to check after it was copied it would help, not before. The concern is impacting the destination. Get-DBAServerRole doesnt return the members, the online doc is out-of-date.

![image](https://user-images.githubusercontent.com/4984616/43529593-a62e29ae-9579-11e8-958d-0e7da969a504.png)

![image](https://user-images.githubusercontent.com/4984616/43530209-ff0fa7ea-957a-11e8-99b4-1069b80414b2.png)

**Comment by hfleitas** [comment]
Closing
