### ISSUE TITLE
Backup-DbaDatabase not working with SQL Server 2000

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3889]
![image](https://user-images.githubusercontent.com/8278033/44006194-8b70ba32-9e1b-11e8-9739-166bfdf18294.png)

I added the usual backup/restore suspects. If anyone doesn't want to be assigned, please DM me and I'll keep you off in the future 🌮

**Comment by potatoqualitee** [comment]
Confirmed working on 2005 and above

**Comment by nvarscar** [comment]
Are we still supporting SQL 2000? Even Microsoft doesn't.
Anyways, since I don't have 2000 instance around, I would put a couple suggestions here, as I can't test it properly.
1) Remove slash before the file name. It seem to not matter at all for SQL that I have around - both `BACKUP ... TO DISK '\file.bak'` and `BACKUP ... TO DISK 'file.bak'` have the same result. Is it the same for SQL2000? If so, we'll need to change the following line to insert `$slash` only when `$FinalBackupPath[0] -ne ''` https://github.com/sqlcollaborative/dbatools/blob/e5e583ad14d8b716601f3faa820c1eccc4aa3a84/functions/Backup-DbaDatabase.ps1#L381
2) Replace the following line: 
https://github.com/sqlcollaborative/dbatools/blob/e5e583ad14d8b716601f3faa820c1eccc4aa3a84/functions/Backup-DbaDatabase.ps1#L359
With:
```powershell
if ($BackupDirectory) { $FinalBackupPath += $BackupDirectory }
else { $FinalBackupPath += $Server.BackupDirectory }
```
