### ISSUE TITLE
Databases with same name on multiple instances

### ISSUE THREAD

**Issue by pmsousa** [sqlcollaborative/dbatools#3916]
## Steps to Reproduce

- 2 SQL Server instances (non related, different systems/servers) – inst1 e inst2;
- Both instances have SharePoint BD’s, thus you have BD’s  with common names (i.e.: SharePoint_Config, WSS_Logging, WSS_Content, etc.)

powershell
```
#Backup history timeline:
Get-DbaBackupHistory -SqlInstance 'SQL01','SQL02' -Since '2018-08-18 00:00' | ConvertTo-DbaTimeline | Out-File C:\temp\Get-DbaBackupHistory.html -Encoding ascii 

```

## Expected Behavior

The expected behavior should be a timeline for each database, with no aggregation by database name or an added column to the results with the servername/instancename to separate the databases.

## Actual Behavior

Has you can see, looking at the chart it seems that **WSS_Logging** database had **2 Full Backup** on the same day at different hours. The reality is that both SQL Server instances have a  WSS_Logging database and different schedules for the Full Backup on the same weekday.

![image](https://user-images.githubusercontent.com/12728678/44471784-8d08d580-a624-11e8-869d-94a1d2d46f69.png)

## Final Notes
GREAT WORK!!!!! Kudos for this... 🥇

**Comment by potatoqualitee** [comment]
Thank you for the bug report @pmsousa !

@marcingminski can you please take a look? also, i'll be sending you an invite to the sqlcollab so that you can be assigned 😅

**Comment by marcingminski** [comment]
Hi, yes, for some reason this had skipped my radar. It was only brought to my attention couple of days ago on slack. Technically not a bug as it wasn’t designed to handle multi server and it only groups by database name. Since dbatools however have multisever at heart, I will make this work but looking for some input how you guys want it to work:

- I can make server name and database name into a composite key and everything will be shown on same chart. The name will be SEREVERNAME - DATABASENAME

- I can make chart per server. Then the format will not change but there will be repeated charts for each server.

Or maybe I’ll do both cos I don’t like compromises.

**Comment by pmsousa** [comment]
Hi @marcingminski,
I can relate to that, it also skipped my first tests on Dev Environments but when I started using dbatools on more and more envs, this issue popped-up. SharePoint developers tend to leave the defaults for database names and when you have more that one server of these... :)


From both proposed solution, I think the best approach is the first. If we wanted separate charts, then we just add to run the cmdlet one instance at a time and get separate graphs. If I run the cmdlet for multiple SQL instances, one should assume that I want an overview of all those instances in just one graph. So the composite key and one chart seems the best solution.

What do you think? Makes sense?

**Comment by marcingminski** [comment]
Bad bot.
Apologies I completely forgot about it. I’ll add it to my task list.
