### ISSUE TITLE
Backup-DbaDatabase, add NO_COMPRESS for encrypted dbs

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#3941]
Had a comment:

> Whew!!  Found the problem.  The database that could not be read was encrypted.  It was backed up using Backup-dbaDatabase .... -Compress.  since it is the only encrypted DB we have, we specify Compress='Y' in Ole's backup job and it knows to switch to NO_COMPRESS for an encrypted DB.  Backup-dbaDatabase will successfully compress an encrypted DB, but it will be unusable.  That's usually but a good thing   :slightly_smiling_face:   You might consider putting some logic into Backup-dbaDatabase to switch to NO_COMPRESS no matter what the switch or server default is.  THAT was a mind bender.

Basically, compression will never work with encrypted dbs, so we should warn and stop if -Compress is used or pull an Ola and do NO_COMPRESS no matter what (and warn).

**Comment by Stuart-Moore** [comment]
OK, so appveyor doesnt offer TDE (as it's express).

Should I:
a) delete the test
b) comment out the test so we have it for future reference if needed

**Comment by niphlod** [comment]
hum. express does not have agent and we surely have agent-based tests .... maybe try on the 2016-2017 instances ?

**Comment by potatoqualitee** [comment]
yeah 2016 and 2017 are Developer Edition 👍

**Comment by potatoqualitee** [comment]
thanks for taking a look btw!

**Comment by Stuart-Moore** [comment]
Will it causes issues with the pester grouping if I have 1 sql2016 test in the backup tests? All the others are 2008. 

Is the balancing thing still a thing?

**Comment by niphlod** [comment]
If I did the work well, it selects within the matrix the needed env. We do
not balance among the matrix, we just run what can we run where it can run.

We also provisioned the organization in order to support multiple test
files per function, will the need arise to have a function tested in
multiple envs (check the wiki for naming convention, or ask me directly)

Il gio 30 ago 2018, 18:37 Stuart Moore <notifications@github.com> ha
scritto:
