### ISSUE TITLE
Failure to Build Restore chain quick enough

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#3966]
### Before submitting a bug report:

- [X ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce
We use the Ola backup solution.  I am trying to do a point in time restore.  The Restore-DbaDatabase has to read through 4000 log files.  Due to the fact we run TLogs every 5 minutes, by the time the function gets all the file names and then come backs to read the header the oldest TLog is gone and I get error file not found.  I even have tried -AllowContinue and get the same behavior.

```Restore-DbaDatabase -SqlInstance $Server `
    -Path '\\crpitsisln17.exclaim-crp.com\sql\exclaim-prd\PRDPRSDBS13$NLS_Rise_AG\NLS_Rise' -MaintenanceSolutionBackup `
    -DatabaseName "$($previousMonth)_Rise_CBR" -DestinationDataDirectory R:\SQLData -DestinationLogDirectory R:\SQLLogs `
    -ReplaceDbNameInFile -RestoreTime $RestoreTime -AllowContinue

```

![image](https://user-images.githubusercontent.com/169602/45000750-3046dc80-af8d-11e8-9fd4-e507134b26ab.png)

**Comment by Stuart-Moore** [comment]
You're pushing in 2 weeks worth of backups,. This is nothing to do with your 5 minute backups (I do those as well), just that you're pushing in too much data. 

Unless you're really only taking a full backup every 2 weeks can you prefilter:

`Gci c:\path | ?{$_.LastWriteTime -lt (Get-date).adddays(-3) | restore-dbadatabase.........`

Or you can use Get-DbaBackupHistory:

`Get-DbaBackupHistory......  | Restore-DbaBackup -TrustDbBackupHistory.......... `

which only checks the files exists. Remember you can get history from the prod server and then pipe it into a restore on a test server. It'll just work if both can see the same paths. If the can't then you just need to modify the paths to the files

**Comment by gbargsley** [comment]
So all of my backups are stored in the file path and we use Ola's backups.  I need to do a point in time restore of 09/01/2018 @ 4:00am.  Using your suggested method, how would I scan the folder or the MSDB backup history to build the restore chain to this point in time.  We store 14 days of backups in our backup paths.

**Comment by Stuart-Moore** [comment]
OK, need to ask some questions about your back schedules to answer that. Feel free to submit false info, but please make sure it's in the right ballpark and rebase my answers based on what you've provided.

To filter the files I'd need to know when you take the full backup as that's the earliest file  you need. For a restore to a Saturday on my larger systems I know I'd need to pull the Full from Wednesday (we do fulls on Sunday and Wednesday, diffs other days) and they start at 21:00. So I'd then go

`Get-ChildItem \\server\\backups\prod | Where-Object {$_.LastWriteTime -gt (Get-Date "29/08/2018 21:00"} | Restore-DbaDatabase -SqlInstance TargetServer -RestoreTime (Get-Date "01/09/2018 04:00") -AllTheOtherOptions`

Note, you don't need to specify Path when pushing files in like that. So you can just change the date on the file filter to accomodate your backup schedule. Should at least halve the number of files you're scanning (assuming you're at the furthest point from your full backup)

For Get-DbaBackupHistory I'm assuming you have a Production server that's actually doing the backups and already has the backup history. So in that case I'd go:

`Get-DbaBackupHistory -SqlInstance Prod -Since (Get-Date "29/08/2018 21:00"}) | Restore-DbaDatabase -SqlInstance TargetServer -RestoreTime (Get-Date "01/09/2018 04:00") -TrustDbBackupHistory -AllTheOtherOptions`

This doesn't read any files, just checks they exist. This is the fastest way to pass backup information into the restore process.

If those don't work for you then there are more complex filtering options I can go in to if you'd like?

**Comment by gbargsley** [comment]
We take a full weekly on Sunday at 4:00am. We take diffs every other day at 4:00am and tlogs every 5 minutes. Our fulls take between 4 and 6 hours to complete. 

So the example I am working with this month was yesterday I needed to start a restore that was for a point in time of 09/01/2018 at 4:00am. So I pointed the restore function to my backup folder. And it seemed that before the function could get everything it needed a tlog ran ad deleted the oldest tlog. Then when the function tried to read header on that tlog it was gone since the tlog job deletes old tlogs older that 14 days. 

So I just have to figure out with automation how to build the restore chain to a point in time either via a folder scan or using msdb from the original server.

**Comment by Stuart-Moore** [comment]
Yes, or think about your overall backup strategy. I have a policy that I have to have a FULL restore chain on disk, ie for any full backup I must have all the diffs and logs up till now on disk. This is my DR plan, so if we lose a prod server I can recover without having to go back to tape/archive. So my backups are removed after the next full is taken and only up to that full.

In your case a file filter would be

`Gci \\share\prod | Where-Object {($_.extension -eq '.bak') -or ($_.extension -eq '.trn' -and $_.LastWriteTime -gt that $RestoreTime.AddHours(-28)}`

This will return all the fulls and diffs (*.bak), and all the logfiles from the 28 hours before your restore points. I'd put a bit of overlap in there just to cover yourself

So it's not just the backups you need, but it should have slimmed you down from 4k files to 3-400.

With both of the inputs (filtered files or history) Restore-DbaDatabase will still build the chain for you. You just have to give it the information

**Comment by Stuart-Moore** [comment]
No response for 14 days, closing as not a dbatools issue.
