### ISSUE TITLE
Installer Function for SqlWatch?

### ISSUE THREAD

**Issue by koglerk** [sqlcollaborative/dbatools#4003]
### Summary of new feature

Given that [SqlWatch prefers a DACPAC deployment](https://sqlwatch.io/docs/installation/dacpac-deployment/), and dbatools has `Publish-DbaDacpac`, should we offer an installer function similar to `Install-DbaFirstResponderKit` and `Install-DbaMaintenanceSolution`?

At my day job, I have a need to automate the deployment of SqlWatch across my SQL Servers. I'd be happy to code this and contribute it back to the community if it's a good fit. What I'm unsure about it whether this is better suited for dbatools or SqlWatch. @marcingminski can you tell me which you'd prefer?

### Latest version of dbatools as of writing

* 0.9.417

**Comment by marcingminski** [comment]
Hi, 

Thank you for your interest in SQLWATCH!

This has been on my to-do list for some time. I think this would be a better fit for dbatools rather than the SQLWATCH repo for a number of reasons:
1. SQLWATCH already offers a number of standard ways it can be deployed to a single server
1. Multi-server management using PowerShell is what dbatools have been designed for. 
1. I feel it would be duplicated effort if we wrote a PS deployment script/module from scratch if dbatools already offer such functionality?

Does @potatoqualitee agree?

**Comment by potatoqualitee** [comment]
yep! i agree, it belongs in dbatools. I just realized that's where @tootblan posted the issue, unsure if you thought it was in SqlWatch, @marcingminski. either way, i'd love to see supporting commands for SqlWatch in dbatools 🌮

**Comment by tootblan** [comment]
Thank you both for weighing in so quickly! I'll see if I can get it coded and have a PR submitted by the end of this coming week.

**Comment by marcingminski** [comment]
Good deal, I will focus on building SQLWATCH then. Thank you!

**Comment by potatoqualitee** [comment]
sounds fab @tootblan !

**Comment by tootblan** [comment]
The SQLWATCH [DACPAC deploy documentation](https://sqlwatch.io/docs/installation/dacpac-deployment/dacpac-deployment-using-command-line/) indicates the property `RegisterDataTierApplication` should be set to `$True` when the DACPAC is published. The best way I can see to do that would be to modify the XML used as a template in `New-DbaDacProfile`:

```
function Get-Template ($db, $connstring) {
    "<?xml version=""1.0"" ?>
    <Project ToolsVersion=""14.0"" xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
        <PropertyGroup>
        <TargetDatabaseName>{0}</TargetDatabaseName>
        <TargetConnectionString>{1}</TargetConnectionString>
        <ProfileVersionNumber>1</ProfileVersionNumber>
        <RegisterDataTierApplication>{2}</RegisterDataTierApplication>
        </PropertyGroup>
    </Project>" -f $db[0], $connstring, $RegisterDataTierApplication
}
```

In the code above, I've added `$RegisterDataTierApplication` as a switch parameter to `New-DbaDacProfile` so it can be set to `$True` or `$False` when the function is called. This works great in my test environment, but there's [a large number of other properties ](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-2017#publish-parameters-properties-and-sqlcmd-variables)that could potentially be set. None of them are needed for installing SQLWATCH, but I want to make sure the changes to `New-DbaDacProfile` are as future-proof as possible. 

So the question for @potatoqualitee (and anybody else) is this: should I change the switch parameter I added to be a hashtable instead to allow for any of the publish options listed above? Or should I just not worry about it now and deal with that later if we ever have a need for it?

**Comment by tootblan** [comment]
The parameter in the previous comment was updated to use a hashtable as proposed. PR coming shortly.

**Comment by tootblan** [comment]
OK @marcingminski I'm officially stuck. 

I've got functions written to install and uninstall SQLWATCH and I've got Pester tests for both. You can see them [in this branch](https://github.com/tootblan/dbatools/tree/Install-DbaSQLWATCH) if you like.

I can run `Install-DbaSQLWATCH` and specify a database name of `SQLWATCH` and everything works great. But when I try to specify any other database name, I get a warning and two errors. 

It looks like, [based on your 09/09 blog post](https://sqlwatch.io/blog/2018/09/development-progress-09-09/), that your intention might be to force all users to use a database called `SQLWATCH` and not specify their own database anymore. Can you tell me if that's true? If so, you can ignore everything else in this comment. 

But, assuming users can specify their own database, then the error that's preventing me from going forward is `Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_verify_jobstep, Line 294 The specified @database_name ('SQLWATCH') does not exist.` 

It looks like there might be an Agent job that's hard-coded to the SQLWATCH database instead of picking up TargetDatabaseName from the publish options.

Here's the full error dump that contains both the warning and the two errors:

```
Could not deploy package.
Warning SQL72017: The unnamed foreign key between tables [dbo].[sql_perf_mon_snapshot_header] and [dbo].[sql_perf_mon_config_snapshot_type] will be checked by checking the table.  Name the 
foreign key to avoid checking the entire table and only check the new constraint.
Error SQL72014: .Net SqlClient Data Provider: Msg 14262, Level 16, State 1, Procedure sp_verify_jobstep, Line 294 The specified @database_name ('SQLWATCH') does not exist.
Error SQL72045: Script execution error.  The executed script:
IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_config_who_is_active_age]) = 0
    BEGIN
        INSERT INTO [dbo].[sql_perf_mon_config_who_is_active_age]
        SELECT 60;
    END

UPDATE swd
SET    [database_create_date] = db.[create_date]
FROM   [dbo].[sql_perf_mon_database] AS swd
        INNER JOIN
        sys.databases AS db
        ON db.[name] = swd.[database_name]
            AND swd.[database_create_date] = '1970-01-01';

EXECUTE [dbo].[sp_sql_perf_mon_add_database] ;

IF (SELECT count(*)
    FROM   [dbo].[sql_perf_mon_server]) = 0
    BEGIN
        INSERT INTO dbo.sql_perf_mon_server
        SELECT CONVERT (sysname, SERVERPROPERTY('ComputerNamePhysicalNetBIOS')),
                CONVERT (sysname, @@SERVERNAME),
                CONVERT (sysname, @@SERVICENAME),
                CONVERT (VARCHAR (50), local_net_address),
                CONVERT (VARCHAR (50), local_tcp_port)
        FROM   sys.dm_exec_connections
        WHERE  session_id = @@spid;
    END

CREATE TABLE #sql_p
```
The second error I'm guessing is related to the first, but I could be wrong about that. The warning about an unnamed foreign key is probably worth fixing but not fatal to integrating SQLWATCH with dbatools. 

If the database name will always be `SQLWATCH`, then I can make a few quick adjustments to the functions and have a PR up in a few days.

**Comment by marcingminski** [comment]
Hi, nah you should be able to use any database name, there shouldn’t be anything hardocded in the agent but I’ll double check. I need to improve the way I create agent jobs anyway. Which version are you using?

**Comment by tootblan** [comment]
@marcingminski version 1.2.6839.42002.

**Comment by marcingminski** [comment]
Yeah there’s a bug, I just looked at the code. Apologies. I’ll fix that tommorrow. You can try with previous version 1.1 (in releases) that should work with any database name.

**Comment by tootblan** [comment]
No worries. I'll wait till tomorrow and do some final testing.

**Comment by marcingminski** [comment]
Hi, Fixed. There were two bugs actually, one to do with hardcoded database name and one with primary key violation due to missing `snapshot_type_id` for new indexes collector. These fixes were both in the PostDeploy script - which, as I found out today, do not trigger Dac build and therefore do not increase build count (I have been doing this for the past few years and never noticed). The result was a fixed code visible to me but still failing due to not refreshed Dac which had the old copy! This,  embarrassingly, also caused binary file conflict in Git which I think I sorted now. Interesting how an easy task of changing one variable can change into 4 hour nightmare. Please let me know if you run into any issues.

**Comment by potatoqualitee** [comment]
How's this looking, @marcingminski ?

**Comment by koglerk** [comment]
@potatoqualitee @marcingminski I'm 99% done with it. You can see it in [my branch](https://github.com/koglerk/dbatools/tree/Install-DbaSQLWATCH) if you like. I should have a PR done this weekend.

(Life got in the way and it took a LOT longer than I initially thought!)

**Comment by koglerk** [comment]
PR submitted. Let's see if my code survives peer review!
