### ISSUE TITLE
Install-DbaInstance

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4076]
Mike Wells made the popular SPADE script set to help automate the install of SQL Server. I'm looking to do something similar in dbatools. Got any suggestions?

First one of my own is to auto build a config ini based on an existing SQL Server's configs. I'm thinking the following:

* New-DbaInstallConfigIni that accepts SqlInstance or Version
* Install-DbaInstance that works remotely, accepts the ini and uses a Credential object for passwords

And while I wait for responses, can anyone create the following ini templates?

* Configuration_2014.ini
* Configuration_2016.ini
* Configuration_2017.ini
* Configuration_2019.ini

Also if anyone wants to take this on, please feel free. I'll be exploring HA stuff for a bit.

**Comment by potatoqualitee** [comment]
Also this is for my reference: https://natethedba.wordpress.com/2017/08/04/automating-sql-installation/

**Comment by greenmtnsun** [comment]
One of my biggest problems with creating INI files is the MANY options that are available and getting them right.  If you were able to get all available configuration options into the module, with all of the workable options as well, that would be a MAJOR slam dunk for silent installs.

**Comment by potatoqualitee** [comment]
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-2017

**Comment by OxyMethylene** [comment]
Goodmorning,

You could use dynamic parameters to load in all possible parameters you can use for the installation. By using some default config files and using powershell parameters to overwrite/add certain options could be interesting.

I tried something like this a few months ago, but due to lack of time it got pushed back on the pile of possible fun projects :)
The original idea was to make SQL Setups easier when we need to deploy a large amount of servers. We had the idea to use a default config .INI file with our general setup and use Powershell variables to overwrite or add extra options.

The code loads in all possible variables that you can use to install a SQL server with command line from the json file with some extra information. (All commands are in the json, but they arn't in the correct groups and don't have the correct datatype either; [Installation Parameters Docs](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017#Install))
It uses parameter sets to decide what parameters will be mandatory.
 
I've thrown the code onto a public github repo, feel free to use whatever from it. It was the first time that i used dynamic parameters in Powershell and this code is also from the time that I just started with Powershell, so it may need some love :)

![image](https://user-images.githubusercontent.com/13507100/48052605-b4ddf300-e1a8-11e8-8f0d-38a4e6bfbc97.png)

**Comment by potatoqualitee** [comment]
Thanks so much, @OxyMethylene ! @reitse you may find some of this useful for your PR, take a look! 👍

https://github.com/OxyMethylene/SQLSetup/

We can also explore it for v2

**Comment by potatoqualitee** [comment]
consolidating to https://github.com/sqlcollaborative/dbatools/pull/5175
