### ISSUE TITLE
Export-DbaLogin / Alter user with login

### ISSUE THREAD

**Issue by Shashahan** [sqlcollaborative/dbatools#4241]
---
name: Alter Export-DbaLogin so it will only create a database user if it does not exist.

---

### Summary of new feature

* Right now the command will create statements like CREATE USER FOR LOGIN, but this should only happen if the user does not exist in the database. If the user already exists, in case of a migrated or restored database the command should use ALTER USER WITH LOGIN

### Proposed technical details (if applicable)
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = '@login_name')
BEGIN
      CREATE USER ['@login_name'] FOR LOGIN ['+@login_name+']'+isnull(' WITH DEFAULT_SCHEMA=['+default_schema_name+']','')+'
END
ELSE
BEGIN
 ALTER USER ['@user] WITH LOGIN ['+@login_name+']
END

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
Latest stable

**Comment by nvarscar** [comment]
Right now, there is Export-DbaUser which is using the following syntax for creating users:
```sql
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'asd')
CREATE USER [asd] FOR LOGIN [asd] WITH DEFAULT_SCHEMA=[dbo]
```

So that partially covers the user creation when it does not exist, but it would be great to have it for Export-DbaLogin as well. Also, as far as I know, Export-DbaLogin does not capture object-level permissions in the databases, which probably makes it logical to re-use Export-DbaUser code inside Export-DbaLogin. I'll look into it as a part of a cloning SQL Login issue #3864 
The other part - re-mapping user to a login after a restore - is covered by `Repair-DbaOrphanUser`, which assigns users to logins based on matching names.
Re-mapping users seems slightly out-of-scope for the Export-DbaLogin/Export-DbaUser commands, I can imagine edge cases where end-users will not want to re-map all the users automatically. One of the examples would be `login <= dbo` mapping, where implicit re-mapping will cause the database owner to change (or maybe simply fail, not sure), so that's not something I will be willing to implement as a part of the Export-DbaLogin experience.
I would still recommend using `Repair-DbaOrphanUser` as a second step in your user restore agenda (which is the way I'm using it currently). That way you (and all others who are thinking about this scenario) would have more control over the user creation process. And I will definitely look into adding `IF EXISTS` to the current command.

**Comment by nvarscar** [comment]
The scripting logic of the user creation is handled by the ScriptingOptions object which can be provided as a parameter to the function. Which means it can't be modified by external means other than supplying your own ScriptingOption object, which, unfortunately, doesn't support such behavior. If the user already exists in the database by the time this script is applied, a different process (such as `Repair-DbaOrphanUser`) should take care of altering the users to match them with logins.
