### ISSUE TITLE
Fix PSAvoidUsingWMICmdlet

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbatools#4461]
### Summary of new feature

There are 4 cmdlets breaking the PSAvoidUsingWMICmdlet script analyzer rule, which could be impacting cmdlet use as well as our BOH. This rule states that CIM cmdlets should be used instead of the older WMI cmdlets
```
ScriptName               Line Extent
----------               ---- ------
Get-DbaCmObject.ps1       310 Get-WmiObject @parameters
Reset-DbaAdmin.ps1        204 Get-WmiObject -Class Win32_NetworkAdapterConfiguration -Filter IPEnabled=TRUE -Compute...
Set-DbaPowerPlan.ps1       93 Get-WmiObject -Namespace Root\CIMV2\Power -ComputerName $ipaddr -Query $query -ErrorAc...
Set-DbaPowerPlan.ps1      116 Get-WmiObject -Name root\cimv2\power -ComputerName $ipaddr -Class Win32_PowerPlan -Fil...
Test-DbaCmConnection.ps1  177 Get-WmiObject -ComputerName $ComputerName -Credential $Credential -Class Win32_Operati...
Test-DbaCmConnection.ps1  210 Get-WmiObject -Class Win32_OperatingSystem -ErrorAction Stop
````

See [PSAvoidUsingWMICmdlet.md](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/AvoidUsingWMICmdlet.md) for more details

### Proposed technical details (if applicable)
Since these are all `Get-WmiObject` cmdlets it seems that it would easy to replace with `Get-CimInstance` cmdlets. However, I saw an [old post in trello](https://trello.com/c/XbStF12s) that suggested making this change was not possible because of support for older clients. Thoughts @cl and @wsmelton ?

**Comment by sqllensman** [comment]
Hi Josh.

I have been looking into this as result of different issue. Namely that commands that read or modify the PowerPlan information are using different approaches when getting data.

As part of that I looked into all uses of  Get-WmiObject.

My thoughts are that
1. Test- DbaCmConnection is testing all connection options . The use Wmi here is necessary part of functionality. 
2. Get-DbaCmObject is similar and probably cannot be changed without reduction in functionality.  WMI only used when Cim not working/available 
3. The usage in Set-DbaPowerPlan can likely be changed. The first usage can use Get-DbaCmObject to retrieve state and the call to alter state can be changed to use Cim commands.  PowerPlan information is only available for Windows 2008R2 or higher so support for older versions not required. I was planning on testing this over weekend. 
4.I have not looked into the Reset-DbaAdmin command

**Comment by wsmelton** [comment]
I'm curious to know right off why we are worrying about rules with PSSA that we previously have never bothered or even tested against? PSSA rules are moving forward to get rid of habits that were only supported in older versions of PS and Windows. However, dbatools is not at this time and still supports older versions of both Windows PowerShell and Windows....which means some of these rules have to be ignored.

Back to this issue at hand....They are all there to support backward compatibility...and unless you can guarantee that same support, should not be changed (meaning you can show proof it supports back to PS3 and against Window 2003 server....yes I really mean 2003 sadly.). So basically any change to these commands should be very carefully tested against older versions of Windows, because what is tested in Appveyor does not represent the majority of configurations and environments where they are more commonly used.

**Comment by joshcorr** [comment]
@sqllensman That is awesome! thanks for looking into those.

@wsmelton I was working on the PSSA rules as a result of looking at the ~120 or so cmdlets on the BOH that failed PSSA. The BOH isn't clear on which rules are in place and which ones are being ignored, so I just used PSSA as the guide. If it showed up then it needed to be fixed in my mind. If we need to ignore this rule for backwards compatibility that is great, but if we don't have a testing environment in appveyor can we really say we support it? Ultimately I am just trying to get that section of BOH to 100% so if it means replacing that WMI cmdlet, or if it means putting an override in place on this rule I am game either way.

**Comment by wsmelton** [comment]
We run PSSA rules against appveyor. I don't control how boh is run it setup.

We are bound to rules against the PS gallery as well which are not strict. Unless the rule is critical then we are not enforcing it or overwriting with a flag. There is no reason to add override flags for something that does not apply to our validations.

**Comment by wsmelton** [comment]
Mind you appreciate the effort but there are other things of higher priority than satisfying every PSSA role out there. PSSA itself has already started dropping support for older versions of PS that we still support... So just something to keep in mind.

Unless Chrissy has set something that I'm not aware of...

**Comment by potatoqualitee** [comment]
I haven't, but I do really like the idea of following the PSSA. One of the reasons I didn't want to enforce it earlier was because the task of refactoring for compliance seemed impossible.  But now we have devs tackling it and I'm excited that we're developing in a more structured and formalized way.

Our code editors are making it easier, too, and I think going forward, it'll become a natural part of coding for us and in turn, people learning from our code 💝

**Comment by wsmelton** [comment]
I'm all for it as long as it is understood that becoming compliant means no longer supporting older versions of PS.

**Comment by potatoqualitee** [comment]
Just tried on Win7 client and it worked 😅 I'm primarily concerned with client support for PS3. Remote servers with old OSes aren't so much a focus because a lot of our commands won't work with them anyway (all of the ones using Invoke-Command2/Remoting)

**Comment by sqllensman** [comment]
Most of those issues can be trapped by using Test-WSMan and then skipping calls that use Remoting.
