### ISSUE TITLE
Connect-DbaInstance - keep throwing?

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4577]
Connect-DbaInstance fails ugly. Do we add `-EnableException` or keep as is? so that people can easily use it in try/catch?

**Comment by nvarscar** [comment]
Might be a breaking change for a whole bunch of commands that rely on it throwing by default. Since it's a cornerstone command, I would rather have it throwing by default or it could cause all kinds of logic issues. We could add an opposite flag (-IgnoreException? -Silent?) in this particular function to support a non-throwing execution.

**Comment by potatoqualitee** [comment]
all great points, thank you. just unsure of the name 🤔

**Comment by wsmelton** [comment]
The fact this is not an internal command I think it should follow the same guideline/rules we apply to other public commands. So it should not throw.

Breaking change is breaking change for 1.0 so it won't matter as we have published this fact enough. I see no reason to continue to make this command throw because it is a user based command so it should have the basic logging....because it does not means this is one of the only commands that does not get included in the logging system does it not?

**Comment by wsmelton** [comment]
I would also not classify this one as a cornerstone command...only the heavy/deep users of the module likely even know it is there and what purpose it serves.

**Comment by nvarscar** [comment]
I did a quick search, and only a few commands are actually using Connect-DbaInstance ( I was expecting to see much more there). And all 3 of them, which can be easily hotfixed. 
My biggest concern is about user scripts that rely on that command. I wonder, how impactful of a change it's going to be for people who rely on this command to stop execution of their scripts if something happens.
Also, almost all of our tests are using this one. Should we switch to internal Connect-SqlInstance instead?

**Comment by potatoqualitee** [comment]
I ended up going with DisableException, I think it's a good call because it'll mostlyl be used for internal scripts and shoudl be handled. I'm horrified that a couple of our commands in \functions are using Connect-DbaInstance, that should be rectified. I'm alright with our tests using it since our tests are similar to external scripts.

**Comment by wsmelton** [comment]
What commands do we have using a public command? Any of our functions should be calling the internal function just like everything else...so those need to be fixed.

**Comment by potatoqualitee** [comment]
logged them here : https://github.com/sqlcollaborative/dbatools/issues/4603
