### ISSUE TITLE
Seas of blood in Get-DbaBackupHistory

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#4594]
hey Stuart,
can you take a look at this?

![image](https://user-images.githubusercontent.com/8278033/48739763-3e83cb00-ec55-11e8-8d30-194d2bd48708.png)

1. -Force fails hard on sql2016 in the lab
2. Should Force be `-Raw` instead? unsure, but maybe
3. We had a user complain about the parameterset error since it's so vague. Any chance you can do manual validation with if and Stop-Function?

Thank you,
Chrissy

**Comment by Stuart-Moore** [comment]
It will have been broken for ages......

Raw!=Force

Force forces the raw SQL output via a select * 🤮skipping dbatools aliases
Raw returns the dbatools aliases output with aliases

Put an extra test in for $force so we just dump the stuff out.

Due to my incompetence with git this was fixed in PR #4675

**Comment by potatoqualitee** [comment]
LOL np, thank you 🙇
