### ISSUE TITLE
Remove-DbaAgReplica does not remove replica database

### ISSUE THREAD

**Issue by jchantha** [sqlcollaborative/dbatools#4895]
### Before submitting a bug report:

- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
```

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by jchantha** [comment]
Remove-DbaAgReplica does not work. The replica database was not removed.

**Comment by wsmelton** [comment]
@jchantha You don't have checked that you can reproduce this issue. Do you have more details on what you were doing (e.g. command, AG configuration, logs, errors)?

**Comment by goodsoul1914** [comment]
same for me. 0.9.734 dbatools.
Remove-DbaAgReplica -SqlInstance 'srv1' -AvailabilityGroup agDB -Replica 'srv2' -Confirm:$false
executed with no errors, return nothing ans replica still in place

**Comment by wsmelton** [comment]
@goodsoul1914 is saying the replica stays in place.
@jchantha is saying the replica "database" was not removed.

To clarify on the later, `Remove-DbaAgReplica` will not remove the database and it is not meant to perform that action. All the command does is issue the `ALTER AVAILABILITY GROUP [] REMOVE REPLICA ON [];` which will leave the databases in a recovering state on the removed replica. This is by design.  

@goodsoul1914 your comment does not seem to be inline with the original issue submitted so if you would like to submit a new issue with all the details we request, we can see what the next steps will be.
