### ISSUE TITLE
Get-DbaDbSpace command is returning all DBs including all system database

### ISSUE THREAD

**Issue by TechieFriend** [sqlcollaborative/dbatools#4905]
### Before submitting a bug report:

- [ ] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [ ] Verified this bug is not already reported in an issue
- [ ] Verified errors are not related to permissions
- [ ] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

## Steps to Reproduce

```sql
/*
    Any T-SQL commands involved or used to produce test objects/data.
*/
```

```powershell
<#
    Provide exact (or sanitized) code to reproduce the error
#>
```

## Environmental data

 - PowerShell: 
 - - SQL Server:

**Comment by potatoqualitee** [comment]
This is an empty issue, please provide more information

**Comment by alevyinroc** [comment]
Per the message output when using the `IncludeSystemDBs` switch, this appears to be expected behavior; if filtering is needed, the list of DBs should be filtered before passing into this function.

Absent any other information, I don't think this is a bug. @TechieFriend, can you please update this issue with more information?

**Comment by TechieFriend** [comment]
Sure, let me test and update you.






Thanks,
Pinakin Patel
