### ISSUE TITLE
Handling -EnableException when calling other functions

### ISSUE THREAD

**Issue by nvarscar** [sqlcollaborative/dbatools#4956]
## Issue
Many of the functions expect that the value of `$EnableException` variable will be automatically propagated to all the other functions called from within the original function.
This, however, is not always the case, let's see all the possibilities that we have right now:
1. Function calls a **public** function using `-EnableException:$EnableException`. Works perfectly fine, since the value is explicitly passed along to the second function.
2. Function calls a **public** function without explicitly defining `-EnableException`. Since in every public command, `$EnableException` is defined as `[switch]$EnableException`, it will never receive the original value of parent `$EnableException` variable.
3. Function calls an **internal** function, specifying `-EnableException $EnableException`. Works fine, value is explicitly passed.
4. Function calls an **internal** function without defining `-EnableException`. Depending on the  definition of `$EnableException` in the internal function, it can go either way from here:
4.1 `$EnableException = $EnableException` will automatically pick up value from the parent function. Can probably also be a switch, doesn't matter. Only implemented in a few functions.
4.2 `$EnableException = $false/$true` will always use a preferred value regardless of a parent variable.
4.3 `$EnableException` without a default value. Will NOT inherit the value of the parent function, as it's an internal variable now, which was redefined in the internal function to have a `$null` value (non-initialized). 
5. Call **any** function within a try/catch block and use `-EnableException $true`. Works fine, but slightly obscures the error that occurred down the line. It is still available in `$_.Exception.InnerException.ErrorRecord`, but getting proper error Line# and original file is more difficult now.

The only function that really usually makes use of `$EnableException` is `Stop-Function`. In the code, it is defined as 
```powershell
        [bool]
        [Alias('Silent')]
        $EnableException = $EnableException,
```
which means it grabs the value from the external context, but by default, requires it to be defined on a higher level. If an internal function had `$EnableException` redefined, `Stop-Function` will use a redefined value inside this function.
So, in our situation, if we call another function from within a function, we need to ensure that only those methods that propagate `$EnableException` further down the path are used, i.e. `1`, `3`, `4.1` and `5`. All other methods of calling the function will result in `$EnableException` not having proper value. 
## Steps to Reproduce
Just one of the examples.
Have one of the backup files corrupted. Then: 
```powershell
Restore-DbaDatabase -SqlInstance $Instancename  -Path $BackupPath -MaintenanceSolutionBackup -DatabaseName $DBNAME  -NoRecovery -withreplace -continue -EnableException
```

## Expected Behavior
Throws loud and clear

## Actual Behavior
Shows a warning without throwing:
```
WARNING: [09:15:09][Get-DbaBackupInformation] Failure reading backup header | D:\xxx_Backup\xxxx_Logs\xxxxxxx$xxxx_xxxxx_LOG_20190115_002000.trn appears to be from a new version of SQL Server than DRxxxxxxDB1\xxxDR1, skipping.
Process Exit Code 0.  The step succeeded.
```
## Action items
1. Define standards on how we use $EnableException
2. Implement those standards to the existing code base with minimal impact

## Options discussed in Slack - let's fire up the discussion 🔥 
- Define `$EnableException` in a `$script` scope somehow and ensure it stays the same throughout execution of different functions
- Use one of the options described above that comply with proper handling of `$EnableException`

**Comment by wsmelton** [comment]
> Many of the functions expect that the value of $EnableException variable will be automatically propagated to all the other functions called from within the original function.

This is actually not 100% as it goes against our standards. Any call to a public function in another public command should **always** include the `-EnableException` so that command errors properly within the parent function, and is caught in the catch block. That means they should also always be within a try/catch block. Any function that is not doing this should be updated as such.

An example of this (and the proper way of doing this to our standards) is with `Invoke-DbaQuery`:

https://github.com/sqlcollaborative/dbatools/blob/56dc285a1770d8e512e1c77129ff81b247d97946/functions/Invoke-DbaQuery.ps1#L243-L247

Areas in that same command that do not conform properly is the call to `Connect-DbaInstance` this should include the `-EnableException` because it is a public function and will ensure the catch block is fired properly:

https://github.com/sqlcollaborative/dbatools/blob/56dc285a1770d8e512e1c77129ff81b247d97946/functions/Invoke-DbaQuery.ps1#L307

**Comment by wsmelton** [comment]
The reason `Restore-DbaDatabase` does not throw properly is because all of the sub-calls to other public functions does not set the `-EnableException` properly. This should have been caught during reviews, but those PRs get merged before I get to it 😁 .

**Comment by potatoqualitee** [comment]
i never knew to know!

**Comment by nvarscar** [comment]
One of the most common examples would be calls to Get-DbaCmObject, which NEVER get this `EnableException` thingy. This, however, is mitigated by people using `if ($result)` or something along those lines.

**Comment by wsmelton** [comment]
What I stated previously still stands. If someone is using `Get-DbaCmObject` then it should include `-EnableException` so it throws the error and then within your try/catch handle that error as needed.

Use of `if ($result)` can give false positives with how some of our public commands return an object, even when nothing happened. That would cause `if ($result)` to always be true.

**Comment by wsmelton** [comment]
An example on the `Update-DbaInstance` that applies to this thread in how we should be doing error handling...

This line calls an internal function:

https://github.com/sqlcollaborative/dbatools/blob/cfbb6422be0ff7d8f1243b4fc8c9cfb4831c47ee/functions/Update-DbaInstance.ps1#L289

Within the internal function `Get-SqlInstanceComponent` it is calling another internal function but uses `Stop-Function`:

https://github.com/sqlcollaborative/dbatools/blob/cfbb6422be0ff7d8f1243b4fc8c9cfb4831c47ee/internal/functions/Get-SqlInstanceComponent.ps1#L300-L304

For proper error handling, as we intended would be the following changes for each command:

- The call to `Invoke-Command2` is correct to have the try/catch block, but it should be using `throw` instead of `Stop-Function`
- The call to the internal command within `Update-DbaInstance` should have that call wrapped in a try/catch and utilize `Stop-Function` to output the error using the message system.

**Comment by wsmelton** [comment]
In essence this:
https://github.com/sqlcollaborative/dbatools/blob/cfbb6422be0ff7d8f1243b4fc8c9cfb4831c47ee/functions/Update-DbaInstance.ps1#L289-L292

Would likely be best changed to this:

```powershell
try {
     $components = Get-SQLInstanceComponent -ComputerName $resolvedName -Credential $Credential 
 } catch { 
     Stop-Function -Message "No SQL Server installations found on $resolvedName" -Continue 
 }
```

Based on user input that had issue running this command they are seeing the Stop-Function message coming from the internal call to `Get-SqlInstanceComponent` and then red text is being thrown out.

`Stop-Function` should not be used to throw messages when a variable does not have content, at least in this scenario the reason it won't have content is if the call to that internal command throws an error. You might still have an `if` statement to validate the variable collected information even on a successful call, but it would be based on what object is returned when it finds something compared to when it does not.

**Comment by nvarscar** [comment]
I'll close this one since it doesn't feel like it needs further discussion
