### ISSUE TITLE
Copy-SqlDatabase unable to backup to file share where CNAME is used

### ISSUE THREAD

**Issue by arnoldn** [sqlcollaborative/dbatools#500]
Not sure this is a Bug/Enhancement request

Having just used Copy-SqlDatabase (great, BTW) I encountered an issue where using -BackupRestore to a network share was failing during the Start-SqlFileTransfer function.  The error was 

`This sometimes happens with cloned VMs. You can try again or use Backup and Restore`

The cause of the issue here was that the UNC path was using a DNS CNAME instead of the NetBIOS name of the target server.  According to MS [https://blogs.msdn.microsoft.com/sqlserverfaq/2009/12/15/why-do-we-need-spn-for-file-server-nas-ras-file-share-system-dns-alias-cname/](url) an SPN is required to be set up on the file share server _using the alias name_ before for the SQL Server service account can access it.  

After we configured the SPN, I was able to use the alias name in the UNC path.  I'm not sure if there's a way to check for this in PS prior to attempting the file transfer, but wanted to report my findings.  Perhaps expanding the error message text?

- Powershell Version: 5
- OS Version: Server 2012 R2

**Steps to Reproduce**
Attempt Copy-SqlDatabase with -BackupRestore and specify -NetworkShare to UNC path with a DNS CNAME as the host (\\aliasName\share)

**Action Results**
File transfer stops, function aborts

**Comment by wsmelton** [comment]
Thanks for reporting this one. I think it is more an enhancement than a bug as validating the server name as NetBIOS or CNAME (alias) is more networking thing. Could be the same thing that the server name passed in is a DFS share.

**Comment by ctrlbold** [comment]
Yeah, we can update the error message to mention CNAMEs, too. I used to use CNAMEs all the time, but switched to A records after bites like this (there was SharePoint or IIS issue too, perhaps with Kerberos?)

PS 5 has some nice DNS cmdlets, but we use 3 and could potentially find it by using [Net.Dns]::GetHostEntry("nfs.base.local") and checking to see if it matches with HostName -- so far, CNAMEs have returned diff hostnames and A records (that are really aliases) have returned the same hostname.

```
PS C:\github\dbatools> [Net.Dns]::GetHostEntry("nfs.base.local") #CNAME

HostName        Aliases AddressList
--------        ------- -----------
dc.base.local {}      {10.0.1.100}

PS C:\github\dbatools> [Net.Dns]::GetHostEntry("nas.base.local") # A Record

HostName       Aliases AddressList
--------       ------- -----------
nas.base.local {}      {10.0.1.100}
```

Ultimately, I think it'd be a better error message and not necessarily a check since we'd have to know which domain they resolved it to, etc. And ultimately, it is a networking/Windows thing. 

ps, thanks @arnoldn for the damn fine bug report -- you got kudos in the channel 👍
