### ISSUE TITLE
Get-DbaProductKey with Windows Credentials and another domain

### ISSUE THREAD

**Issue by pkotov87** [sqlcollaborative/dbatools#5001]
Hello all!

Wenn I try run Get-DbaProductKey on my Machine (DOMAIN A) from remote Server (DOMAIN B - no trust) whit Windows Credentials DOMAIN B\User I get UserName or Password wrong.

Does anyone have any idea how to fix this?

Regards,
Paul

**Comment by pkotov87** [comment]
Hello all!

I am now trying to create the object server on the remote server. It works for me.
https://github.com/pkotov87/dbatools/commit/c423d38a42968ec1e1be2d6d3ef0eabce82db118#diff-504b9e67fa685cc28768ffba1fe4b105

Regards,
Paul

**Comment by potatoqualitee** [comment]
hey @pkotov87 - can you please fill out the bug report in full? if you can also add the results of -verbose it'd be appreciated. please also make sure that you have updated to the latest version of dbatools - we don't use connect-sqlinstance anymore, really.

also what happens when you connect-dbainstance to that remote machine?

**Comment by potatoqualitee** [comment]
i think this is the one where we fixed the issue a while back. please feel free to reopen with details if you continue having issues after downloading the latest release.
