### ISSUE TITLE
Expand-SqlTLogResponsibly grew my TLog all at once to 150GB.

### ISSUE THREAD

**Issue by scinobe** [sqlcollaborative/dbatools#503]
Bug?

**Steps to reproduce***

I executed Expand-SqlTLogResponsibly with a target size of 150,000MB and a growth increment of 8192MB.  After a long pause, I checked Activity Monitor and saw the command had issued a resize on the file of 150,000MB at all once.  I had to kill the process.

**Action Results**
A growth of the log file to 150GB occurred in one command.

**Expected Results**
My expectation was that it would grow 8GB at a time until it reached 150GB.

**Additional comments**
The information on the cmdlet doesn't actually describe how it works, so maybe I'm just mistaken in its implementation.

**Comment by ClaudioESSilva** [comment]
@scinobe Thanks for reporting this problem.
Can you please paste here the full command that you have executed? 
I want to run the exactly command to see if I can reproduce the problem.

Regarding your statement on "Additional comments" can you be more precise?

**Comment by scinobe** [comment]
@ClaudioESSilva  

Hi, I used this command:

Expand-SqlTLogResponsibly -SqlServer myDBServer -TargetLogSizeMB 150000 -IncrementSizeMB 8000 -Databases myDB

I was prompted to use 8192MB instead of 8000MB, so I said yes.  Activity Monitor showed the log file was being expanded to 150000MB.  Powershell said that it had 1696MB remaining.  The file system showed the log file at full size, while it was expanding.

My additional comments simply mean that the documentation doesn't explain exactly how the function is supposed to work, so I may have made inappropriate assumptions about how the Log file would be expanded.  It's not important to the overall problem.  My expectation was that it would loop at 8,000MB increments until it reached a final size of 150,000MB.

**Comment by ClaudioESSilva** [comment]
@scinobe Thanks for the command.
I found the issue, and it is already addressed on PR: https://github.com/sqlcollaborative/dbatools/issues/514

I found other minor issues and correct them. You can read all the fixes here https://github.com/sqlcollaborative/dbatools/pull/514/commits/0804f630829739741be1281705d738c9c179f729 .

When it's released we'll let you know.
In the meanwhile, would you able to test the fix? 😄 

Regarding the additional comments it is what you said. The expected behavior is that one. Grow in chunks until reach the wanted target size. I have updated the help 😃.

**Comment by scinobe** [comment]
@ClaudioESSilva  Thanks for the information.

I am getting an error when executing the command now.  It states as follows:

Logfile [<dbname_log>] on database <myDB> not processed.  Error:  Cannot bind argument to parameter 'Path' because it is null..

I am using Windows 7.  I noticed in the change log there was a modification to add a slash to the path name if it is missing.  Maybe that is the problem?

Here is the command I ran:

Expand-SqlTLogResponsibly -SqlServer <dbServer> -TargetLogSizeMB 1000 -IncrementSizeMB 250 -Databases <dbName>

It was working this morning before I updated the function.

**Comment by ClaudioESSilva** [comment]
@scinobe Have committed a new version. Please use this https://github.com/sqlcollaborative/dbatools/blob/50cdf1389ea8c9142a15f02320b4efdb377ff251/functions/Expand-SqlTLogResponsibly.ps1

Yes, I have to add a validation to add a back slash to the path, otherwise when using Spli-Path and not the root the backslash is removed. That way the validation of free space compared with Get-DbaDiskSpace output will end on the root and not on the lun path.

I missed the ELSE on the validation. This way variable would be empty and therefore give that error.

Thanks!

**Comment by scinobe** [comment]
I've re-tested the code and it works beautifully.  Thank you!
