### ISSUE TITLE
bypass resolve-dbanetworkname

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#5101]
![image](https://user-images.githubusercontent.com/8278033/53041030-3705d500-3483-11e9-9c3d-197b1c760f19.png)

**Comment by wsmelton** [comment]
> @nvarscar enter-pssession works fine if i enter ip address and fully qualified to server name.  If i enter just servername thw error i get is the winrm error. When i enter the fully name to get-dbaservice commamd i get that no services found in relevant namespaces on

Based on this comment the user needs to be using the FQDN, or our commands need to be using that.

We have 75 functions that reference the resolve command, and all that I see explicitly using the `FullComputerName` property. So if that configuration goes in place we have to update all 75 commands to pick up whether or not the resolve should be called at all. Another option would be to have it determine whether or not we use hostname, IP or the FQDN and let the resolve command still be called.

If a user wants the FQDN, which is what it seems Kbarb needs, then they can `Set-DbatoolsConfig -Name resolve.property -Value FQDN`. We adjust `Resolve-DbaNetworkName` to have a special property for our internal calls and based on the value of that configuration is what true property value would be populated in it. At least that is off the top how I think it could work and be more configurable, the default value was be set to `FullComputerName` since that is what it does now.

**Comment by niphlod** [comment]
yup, the main deal is always the same: mssql doesn't provide the FQDNSDomainName in any place.
So, either you pass in the FQDNSDomainName, which maps finely to both SQL and the underlying server, or when your FQADDomainName doesn't match your FQDNSDomainName, and/or client domain suffixes aren't sufficient (pun intended), we're truly impossibilitated to do anything 'cause netbios ain't gonna work.
Don't get why it's a problem with dbmail though ???
Resolve-* (to get FullComputerName) should come into play just when the function needs to play with both mssql and the underlying server.

**Comment by potatoqualitee** [comment]
good call, ill return an object with all fields populated with the input
