### ISSUE TITLE
Add-DbaAgDatabase and Worker Threads

### ISSUE THREAD

**Issue by BeginTry** [sqlcollaborative/dbatools#5200]
## Steps to Reproduce

```sql
/*
    You would need the following:
    •An Always On Availability Group
    •Multiple databases (perhaps 5 or more?) on the primary replica that are not already added to the AG.
*/
```

```powershell
foreach($Database in $DBList)
{
    Add-DbaAgDatabase -SqlInstance $PrimaryReplica -AvailabilityGroup $AvailabilityGroup -Database $Database.name -SeedingMode Automatic -EnableException
}
```

## Expected Behavior
Expectation is that if there are no exceptions thrown by PoSh, all databases would be successfully added to the AG, with databases in either the Synchronized or Synchronizing state on both the primary and secondary replica(s).......

## Actual Behavior
When adding multiple DBs to an AG in a loop, sometimes a DB shows as "Synchronized" on the primary replica, but "Not Synchronizing" on the secondary replica (along with warnings for the secondary). Additionally, you may see a worker thread error in the SQL log:
       
        The thread pool for Always On Availability Groups was unable to start a new worker thread because there are not enough available worker threads. <br/>
        This may degrade Always On Availability Groups performance.  Use the "max worker threads" configuration option to increase number of allowable threads.

## Environmental data
Not connected to the actual server as I entered this issue. I'll try to verify this data later. 

- PowerShell:  0.9.782
- SQL Server: SQL 2014? 
- [Add-DbaAgDatabase.txt](https://github.com/sqlcollaborative/dbatools/files/2963958/Add-DbaAgDatabase.txt)

**Comment by potatoqualitee** [comment]
This should be fixed in a PR coming tonight. Also, fyi you can do all dbs at once like this:

`Add-DbaAgDatabase -SqlInstance $PrimaryReplica -AvailabilityGroup $AvailabilityGroup -Database $DBList.name -SeedingMode Automatic -EnableException`

As for worker threads, that's something else it looks like:

https://webcache.googleusercontent.com/search?q=cache:jiUMCoXKkvIJ:https://blogs.msdn.microsoft.com/psssql/2012/05/17/alwayson-hadron-learning-series-worker-pool-usage-for-hadron-enabled-databases/+&cd=1&hl=en&ct=clnk&gl=be
