### ISSUE TITLE
GET-DBAOPERATINGSYSTEM

### ISSUE THREAD

**Issue by habibhammy** [sqlcollaborative/dbatools#5346]
Hi DBATOOLS Community,

I'm using this great DBA powershell module to put in place a report script that will gather several metrics from all SQL Server I have in the company. But sometimes the **GET-DBAOPERATINGSYSTEM** command just get stacked with out any output for hours ! ( just had to stop the run of my script after nearly 2 hours run on only this command ! ).
So my questions are:
1. **Do you have any idea why this command just got stack ?**
2. **Can a time out be specified to this command a how can it be set ?**

Here is how I'm using the command : 
`$OsVersion= Get-DbaOperatingSystem -ComputerName $servername | SELECT ComputerName , Version`

Many Thanks for your answers.

**Comment by potatoqualitee** [comment]
thank you for your report, @habibhammy. @wsmelton can you take a look?

**Comment by wsmelton** [comment]
What do you mean by `stacked` ?

I would take a gander that it is going to be environmental as we have never had anyone come back with this issue. If CIM made the connection successfully it could have made the session dormant waiting for an instruction, but we can't control that waiting period. It could have been the server was not able to handle the session or software running on the server effected it (e.g. AV). 

There is not enough detail on your situation to note that a timeout configuration would have even made a difference from CIM perspective. We cannot assume a timeout setting for "killing" the command from trying to run because there is no stateful check possible.

If you are continuing to have this problem on every server we will need logs and much more details on your environment to really serve any purpose.
