### ISSUE TITLE
Export-DbaInstance - add user defined types

### ISSUE THREAD

**Issue by asnest** [sqlcollaborative/dbatools#5376]
Found that this function doesn't script user defined types - and without them (if they exist) many procedures don't work.
Here they are -  `select * from sys.types where is_user_defined = 1`
Could you please add these types import to this function?

**Comment by asnest** [comment]
and column master/encryption keys are not scripted too. Can you add them too?

**Comment by sqllensman** [comment]
Hi @asnest 

What exactly is your expectation of the output that should be produced

User defined types do seem to be scripted, providing they are used in some other object. This is because the scripting options being used include option to script dependant objects.

However, this is actually very prone to error because, for example, if the same UDT is used in multiple tables in Model then the script for each table will include creation of the UDT.

**Comment by asnest** [comment]
I thought I made mistake with choosing this function. Database in Export-DbaInstance restores from backups - so all these objects are already in backup.
But how can I receive scripts for creating these objects (user defined types, column master/encryption keys)?
Get-DbaModule doesn't select these types objects.

**Comment by asnest** [comment]
But I just found another problem in sqlagent.sql file :)
When you backuping alerts, you don't backup alert categories - so all alerts with different categories then default, will not be created by this script.
Should I create new bug for it?

**Comment by asnest** [comment]
you can see all categories of alerts by EXEC msdb.dbo.sp_help_category @class = N'ALERT'
and add them by EXEC msdb.dbo.sp_add_category  @class=N'ALERT',  @type=N'NONE',  @name=N'[name]'

**Comment by sqllensman** [comment]
There a number of issues and requests around Export-DbaInstance.
I will try to incorporate them into a single update
