### ISSUE TITLE
Export-DbaUser

### ISSUE THREAD

**Issue by jkkoehler** [sqlcollaborative/dbatools#5378]
I recently used dbatool 'Export-DbaUser' and found when it creates a role for a user, the role permissions are not picked up.  The role is not useful without its securables.  Is that intended behavior?  Thanks for any info.

**Comment by wsmelton** [comment]
That is by design. When you script a user via SSMS the only object being scripted is the user itself and the explicit permissions it may be assigned. If it has inherited permissions via a role, it only exports the command to join it back to that role and not the inherited permissions. The command we have simply duplicates that same mechanism.
