### ISSUE TITLE
Copy-DbaDbTableData - Add Example for Query Parameter

### ISSUE THREAD

**Issue by kmramsey** [sqlcollaborative/dbatools#5503]
### Summary of new feature

The Copy-DbaDbTableData command has a -Query parameter that allows you to limit your work with this command with a query.  It appears that the -Query option does not have an example.  An example would be helpful because the parameter requires a three part database object in your from clause.

### Proposed technical details (if applicable)

Just add an example with -Query "select * from DatabaseName.Schema.TableName"

**Comment by ClaudioESSilva** [comment]
Hi @kmramsey,

This was added some time ago by @jpomfret -> [Example using -Query parameter](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Copy-DbaDbTableData.ps1#L174)

Thanks for your report.

**Comment by jragan** [comment]
It appears that this example has been removed and we're back to there being zero examples of -Query usage with Copy-DbaDbTableData

**Comment by jragan** [comment]
@ClaudioESSilva I believe this to be a bad example as, per @wsmelton in https://github.com/dataplat/dbatools/issues/4888#issuecomment-451035274 it will not work as it does not include the source -table parameter. Which is all very confusing because it would appear the -query option is almost completely non-functional (haven't seen an example where it actually works - only lots of responses that it won't work for the average scenario most people want it to work for)
