### ISSUE TITLE
[Architecture Decision] Split dbatools into a group of smaller modules much like Az PowerShell

### ISSUE THREAD

**Issue by kilasuit** [sqlcollaborative/dbatools#5676]
This is a mere suggestion so feel free to discard this because it likely will be a fair amount of rearchitecting to achieve

I think that dbatools has reached a point where it actually makes sense to split the module in a similar manner to the Az PowerShell module where dbatools itself actually wouldn't contain any commands but would have multiple smaller modules that are importable independent of all other components that comprise of dbatools.

This also would help improve aspects of module loading which since psv3 you can make use of the ModuleAutoLoading system that will load a module when a command is first run in a session when the command cache already has an entry for that command and the subsequent module it's contained within which also means you only need to import the small subsets of the overall dbatools module in at any given time, reducing both load time and console overheads.

How you would go about structuring it and changing your build & release pipelines would incur a larger investment in getting right but this would be an overall benefit going further as dbatools grows as you would actually have many modules released to the gallery potentially with dbatools being a `meta module` that binds them all in a singular download as it is today

Just a thought that came up off the back of this AWS PowerShell thread https://twitter.com/austoonz/status/1135688165073739776

**Comment by shaneis** [comment]
Interesting idea... I'm not even sure how feasible this is but I will say this is not the first I've heard of people asking if they can only get a subset of the commands e.g. the commands dealing with SQL Server Agent 

🤔

**Comment by sanderstad** [comment]
It would require a significant amount of work and testing to separate the commands.
It is going to be difficult in some scenarios because  i.e. the migration commands use lots of commands.
You would still need to load the majority of the smaller modules toblet it work.

Not shooting this down, just saying what I see could potentially be a problem

**Comment by potatoqualitee** [comment]
Interesting thread/issue. I've explored this before and at this point, there are no plans to split dbatools into submodules due to speed & logistical reasons and my personal preference. @StartAutomating has plans to explore implementing splitting the module by using `Import-Module -ArgumentList`. That I am open to.

**Comment by potatoqualitee** [comment]
will close but keep an eye out in a few months for updates
