### ISSUE TITLE
Commands from another OS Project 

### ISSUE THREAD

**Issue by SirCaptainMitch** [sqlcollaborative/dbatools#585]
Is this a *feature* OR *bug*:
https://trello.com/c/V0lSwkaK

**Additional comments**
Did aground this http://gemautomation.codeplex.com/SourceControl/latest#SQLServer/

**Comment by wsmelton** [comment]
I like the commands listed in this module (from that CodePlex site), just the "Get" commands: http://gemautomation.codeplex.com/SourceControl/latest#SQLServer/libSQLServerStatistics.psm1

I think most of these would be well received.

**Comment by potatoqualitee** [comment]
we need to download this project and stash it somewhere, perhaps in our repo

**Comment by wsmelton** [comment]
Looking over the project and what that psm1 file and while the command names they have would be something we want the code itself they use does not match up at all to how we do business now.

Trying to download the archive project now so I can attach the files for at least the SQL Server part, but they must be throttling bandwidth on CodePlex now because just a 190MB file is taking forever to download on my system.

**Comment by wsmelton** [comment]
[SQLServer.zip](https://github.com/sqlcollaborative/dbatools/files/3016041/SQLServer.zip)
[Windows.zip](https://github.com/sqlcollaborative/dbatools/files/3016043/Windows.zip)
