### ISSUE TITLE
Get-SqlRegisteredServerName - includes CMS even when doing a -Group

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#588]
Is this a *feature* OR *bug*:
bug (small one)

**Steps to Reproduce**
Get-SqlRegistseredServerName -SqlServer sql2014 -Group MyGroup

**Action Results**
MySqlServer
sql2014

**Expected Results**
MySqlServer

**Additional comments**
remove the addition of the CMS itself when -Group is used.

**Comment by niphlod** [comment]
aahem ???? 

By default, the Central Management Server name is included in the list. use -NoCmsServer to exclude the CMS itself

**Comment by ctrlbold** [comment]
Yes, but I don't think it should work like that by default when -Group is specified. Also, that param has to be renamed, gross D:

**Comment by niphlod** [comment]
Ok! Then it's more an enhancement than a bug :-P

Il 20 gen 2017 19:38, "Chrissy LeMaire" <notifications@github.com> ha
scritto:

Yes, but I don't think it should work like that by default when -Group is
specified. Also, that param has to be renamed, gross D:

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/588#issuecomment-274146414>,
or mute the thread

**Comment by niphlod** [comment]
this is actually easy but it'll "break" current documented behaviour. Can we agree on what needs to be changed and assign it to 1.0 (since changes will break previous behaviour) ?

**Comment by potatoqualitee** [comment]
this is going away but people can use that other switch ;)
