### ISSUE TITLE
Install-DbaInstance Bug/Enhancement

### ISSUE THREAD

**Issue by scinobe** [sqlcollaborative/dbatools#5914]
When specifying the InstancePath, I attempted to use the root of a drive (G: and G:\) with the assumption that the default path would be created for me... 

G:\MSSQL13.MSSQLSERVER\MSSQL\Data\

However, I got an error stating invalid characters in the InstancePath - G:""
It would be very useful to be able to only enter the root of a data drive in order to have the install continue, if possible.  But the failure of the install indicates that we probably need some kind of error / input check on the drive paths.

Another suggestion would be to allow the user to specify the InstallUpdates flag and provide the path to the updates folder so that the install completes with all patches already applied and negate the need to run Update-DbaInstance separately.  

Config File:
UpdateEnabled="True"

Parameter:
 /UpdateSource="./path/to/Updates"

Otherwise, this procedure is amazing!

**Comment by potatoqualitee** [comment]
Thank you for the report! I love that you referred to it as a **procedure** ala 1995 when we used to hang out every day in gym class.

**Comment by scinobe** [comment]
I have a lot going on right now :-P

**Comment by nvarscar** [comment]
1) InstancePath (and most other parameters) literally translates to the setup parameters of the native SQL Server installer. I believe, it should be possible to install to the root of the drive - try specifying the path like this: `G:\`. However, I would not recommend it due to disk ACLs being slightly different by default than the folder, which might lead to surprises further on.
As for validation, I can't find any article that would describe how the path should be validated in SQL Server installation. I don't think it's worth the time to validate obvious things, like disks that don't exist; mostly, because installation will eventually fail anyways and people are supposed to know what they're doing.
2) You can add patches to the installation by using custom configuration parameters as follows:
```
Install-DbaInstance ... -Configuration @{ UpdateEnabled="True"; UpdateSource=".\Updates" }
```
Hope that helps.
