### ISSUE TITLE
Handling XE with functions like Get-DbaXEventsData

### ISSUE THREAD

**Issue by MartyMcFlaye** [sqlcollaborative/dbatools#596]
Is this a feature OR bug: feature

**Additional comments**

It could be nice to have a Get- function to extract data from different types of XE target.

I already started to write some part (extracting information from a file target, improvements needed) but before that it could be a good idea to discuss about it

edit: I just don't know how to label it as enhancement or question ... sorry about that :(

**Comment by PowerDBAKlaas** [comment]
There is a Get-DbaXEventsSession, that lists the XEvents Sessions.

Maybe Get-DbaXEventsData would make clear you're getting the actual target data?
At least when it can handle different types of target. In that case there would be a switch -TargetType.

If not, Get-DbaXEventsFileData and ....RingData or something would be appropriate. I'd prefer one function with switches, though.

**Comment by MartyMcFlaye** [comment]
Good point, i'll rename the function.

Is "Dba" a module prefix or should I name it directly?

Regarding the -TargetType switch, @wsmelton mentionned that it would make the function very hard to write the test function. And I'm not very familiar with Pester for the moment, but it will change :)

**Comment by ctrlbold** [comment]
hey @MartyMcFlaye -Dba is the official module prefix. We'll be moving entirely away from -Sql in 1.0

**Comment by wsmelton** [comment]
I'll leave it to @ctrlbold to decide...but having a function like `Read-DbaXEventsTarget -Type "File | RingBuffer | etc."` seems more daunting to build a Pester for than simply having one function for each target type (or at most the commonly used):

- `Read-DbaXEventFileTarget`
- `Read-DbaXEventRingBuffer`
- `Read-DbaXEventHistorgram`
- `Read-DbaXEventEventPairing`

One thing to also consider is [XE exist in Azure SQL](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-xevent-db-diff-from-svr) so do we add that support in these commands or leave Azure SQL out as we have been for most commands?

**Comment by Stuart-Moore** [comment]
Or have an internal function for all 4 of those cases and have an exposed
function thats just a case statement around those 4

Also easy to extend at a later date.

On 27 Jan 2017 3:00 p.m., "Shawn Melton" <notifications@github.com> wrote:

I'll leave it to @ctrlbold <https://github.com/ctrlbold> to decide...but
having a function like Read-DbaXEventsTarget -Type "File | RingBuffer |
etc." seems more daunting to build a Pester for than simply having one
function for each target type (or at most the commonly used):

   - Read-DbaXEventFileTarget
   - Read-DbaXEventRingBuffer
   - Read-DbaXEventHistorgram
   - Read-DbaXEventEventPairing

One thing to also consider is XE exist in Azure SQL
<https://docs.microsoft.com/en-us/azure/sql-database/sql-database-xevent-db-diff-from-svr>
so do we add that support in these commands or leave Azure SQL out as we
have been for most commands?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/596#issuecomment-275684861>,
or mute the thread

**Comment by Stuart-Moore** [comment]
Would also give the option to put in some logic to choose the correct
internal function at a later date.

**Comment by MartyMcFlaye** [comment]
Thanks for your replies! 

In the meantime, I realized that those kind of functions already exists, but you need to install SSMS client libraries in order to use it.

From what I understood, in dbatools, we need to rely on no extra libraries beside .Net classic ones?

**Comment by PowerDBAKlaas** [comment]
I was thinking the same as @Stuart-Moore .
Admitted, I'm only seeing an abstract, very hazy image of it, now. 😊 But it could give us the best of both worlds if it works.
I think the greatest added value is in making hard prodedures easy for the DBA. This looks like a great opportunity for that.

Another idea; could we think about a small overview first. What can we do with or want to know about XE?

like:
- list existing sessions ( I did the easy part  😄 Get-DbaXEventsSession)
- create a XE session
- add events
- start / stop a XE session
- read data
- use templates or create 
- have our own predefined sessions? I collected some in T-SQL: Get-XEfailingQueries, Get-XESystemHealthSession, Get-XEBadPageSplits,...

If we do this first, and distill which functions we need and can make, what we can combine in one,... , before we start writing, we'll make sure we're not creating overlap and are not left with holes in our subset.
Maybe a guide like Erin's or Jonathan's can be a starting point.

**Comment by ctrlbold** [comment]
I don't know much about XE's but know that it would be extraordinarily amazing to make them more approachable. I like where @PowerDBAKlaas and @Stuart-Moore are going with this!

**Comment by wsmelton** [comment]
I would say the easiest thing for defining a session is to simply allow a script block, maybe JSON or XML.

We likely could come up with some "standard" session definitions, but having one work where it will take ANY event/action/filter I think is more than what is needed.

One example, Tiger Team has one published for troubleshooting AG latency, so that can be one we include/reference. 

One other thing to consider is XE can change between major versions of SQL Server. Session definition I use in 2012 will not work in 2008, it should work in 2012+ but that would require extra work of testing. This would be my main reasoning behind having any create function just accept the definition the user wants, but we build a library of a standard list of definitions (maybe a function by itself). That would give the users the ability to see "how" to build the definition, and how to pass it in. ???

👍 for @MartyMcFlaye great idea...very good discussion.

**Comment by PowerDBAKlaas** [comment]
@wsmelton @MartyMcFlaye @Stuart-Moore @ctrlbold 
I see great potential in these functions.
Can we all sleep on it and create some framework first?
We're quite busy with the other stuff the following weeks, maybe after that, XEvents can be our decoy, sign board, (someone who speaks proper English fill in the...)  ... for a next version?

**Comment by wsmelton** [comment]
Total agree, the breadth these functions will have it is best to hold off until after we get the standards settled. Then we can start working on the framework to possibly be in place for 1.0 (or 1.1, or 1.00.1, or 1.00.001).

**Comment by wsmelton** [comment]
Closing this as I believe all the XE commands that have been added meet the requirements discussed.
