### ISSUE TITLE
Could you please include the minimum DB permissions required for users to execute the commands

### ISSUE THREAD

**Issue by firthro** [sqlcollaborative/dbatools#6011]
I wish to grant the team who patch SQL Server the righr permissiosn to evaluate the health of the server before and after using DBATools.  To that end is it possible to include the minimum permissions for commands such as Get-DbaAvailabilityGroup , please.

**Comment by wsmelton** [comment]
I'm afraid that is not realistic for us to accomplish. We utilize SMO and in order to know the exactly list of permissions required to run any given commands would take an enormous effort.

In most situations SMO is querying DMVs and majority of those require permissions like `VIEW ANY DEFINITION` or `VIEW ANY DATABASE`. I can only suggest starting with those and testing through each one.

**Comment by firthro** [comment]
Thanks for the quick reply.

I had applied the basics, added the groups as user to every database, plus the below.  I’ll try further.

USE master
GRANT VIEW SERVER STATE TO [xyz\group]
GRANT EXECUTE on sys.xp_readerrorlog  TO [xyz\group]
GRANT EXECUTE on sys.xp_enumerrorlogs TO [xyz\group]

USE [msdb]
GO
EXEC sp_addrolemember N'SQLAgentReaderRole', N'[xyz\group]
'
EXEC sp_addrolemember N'db_datareader', [xyz\group]
'
GO

Kind Regards
Rob
