### ISSUE TITLE
New Commands: Enable/Disable-DbaHideInstance

### ISSUE THREAD

**Issue by g-kannan** [sqlcollaborative/dbatools#6026]
### Summary of new feature
Script to check and hide SQL Server DB engine

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/hide-an-instance-of-sql-server-database-engine?view=sql-server-2017

### Latest version of dbatools as of writing
1.0.21

* Please provide the latest released version of dbatools module.

**Comment by sirsql** [comment]
What enhancement does this provide? Hiding an instance provides approximately zero in improved security as the port SQL is listening on still shows as listening, it literally just stops the browser service from announcing that port.

**Comment by potatoqualitee** [comment]
While it's unlikely that I'll personally create the Enable/Disable commands (For anyone who would like to create the command, you can base it off of `Enable-DbaForceNetworkEncryption` and it'd be called `Enable/Disable-DbaHideInstance`.), I think it's a good practice to accept a PR for the commands if Microsoft currently supports it. 

For this particular case, some environments may require hiding an instance because of organizational policy and the DBA has no say. In that scenario, automating the task would make things a lot easier for them.
