### ISSUE TITLE
Copy-DbaDatabase fails with Backup Failed | Invalid column name 'State'

### ISSUE THREAD

**Issue by dennisa95** [sqlcollaborative/dbatools#6092]
- Slack Community Channel: https://sqlcommunity.slack.com/messages/C1M2WEASG/ (get an invite: https://dbatools.io/slack/)
- Documentation within the module: `Get-Help <command>`
- Database Administrator on Stack Exchange network, dbatools tag: https://dba.stackexchange.com/questions/tagged/dbatools
- StackOverflow dbatools tag: https://stackoverflow.com/questions/tagged/dbatools

I'm trying to migrate databases in an instance that has a Japanese collation to a new instance on a  new server. I can't get dbatools commands to backup theses databases.  It works for other instances on the same cluster that have the default collation.

**Comment by Stuart-Moore** [comment]
Could you let me have the exact collation you're using please. There's a couple of Japanese ones, and the one I'm using appears to be OK

**Comment by dennisa95** [comment]
Stuart,
This is the collation that is being used: Japanese_CS_AS
Dennis

**Comment by Stuart-Moore** [comment]
Thanks Dennis.

Looks like it's a Case Sensitivity issue that Shaun fixed in https://github.com/sqlcollaborative/dbatools/pull/6032/

That should be in the latest published version of the module (1.0.53).  If you're not running that, could you update and try it again please.

If you're already on that version, let me know as it'll be something different.

Working ok with my test instance:
![image](https://user-images.githubusercontent.com/5613670/66896060-167b2400-efec-11e9-9cf7-0acac51fa4f7.png)

**Comment by dennisa95** [comment]
Stuart,
Thanks for the update.  I downloaded the latest version and installed it on
my server.  That fixed my issue and worked like a charm.
Is there a command to find out the version of dbatools that is installed?
Dennis

**Comment by Stuart-Moore** [comment]
You're welcome. The easiest way to check is with:
`Get-Module dbatools -ListAvailable`

By default PS will load the newest version
