### ISSUE TITLE
Slowness on Export-DbaDbTableData

### ISSUE THREAD

**Issue by TheHandler92** [sqlcollaborative/dbatools#6093]
Hello

when i'm using this function, the export is working but it's very, very, very slow
In comparaison i'm also using this script here : https://gist.github.com/vincpa/1755925
and it does the same job but it tooks less than 5 min to export ALL my table ( approximatively 100 Tables / 1Go space )

But with your function, for only 9 tables it tooks almost 1 hours.

I have tested it on different computer and servers to eliminate the hardware issue
even locally on the DBserver, it's very slow

Example used : 

`Get-DbaDbTable -SqlInstance $server -Database $database -Table [$schema].$table -SqlCredential $Credential | Export-DbaDbTableData -FilePath C:\$outpath\$table.sql
`

**Comment by wsmelton** [comment]
The link you provided exports objects, not data the way I read it.

**Comment by TheHandler92** [comment]
hello 

it exports the data also

Kind Regards

**Comment by wsmelton** [comment]
You will need to show how because this tells me it does not....

`$scripter.Options.ScriptData 	= $false`

**Comment by wsmelton** [comment]
Out command does the same thing except we set `ScriptData` to `$true`.

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaDbTableData.ps1

**Comment by TheHandler92** [comment]
yes indeed, i have changed the original script from the link to $true

Of course your script is doing the same but at a slower speed, much slower.
And i don't understand why

**Comment by wsmelton** [comment]
So every time you run the command, from a new console, on your 9 tables it takes 60 minutes?

**Comment by TheHandler92** [comment]
yes
I have tested with a chrono this morning with one table only.
This table is about 11 Mb so nothing fancy.
With the help of the first script, it tooks about 2 secondes
With the dbatools it tooks about 30 min
This test has been done on the DBserver itself to avoid any network bandwith issue.

**Comment by wsmelton** [comment]
Well, I'm not too sure what we can do about that because it is your environment. You will have to find out where it is taking so long and let us know.

I have moved millions of rows with the command and it took a few minutes.

**Comment by wsmelton** [comment]
The only thing I could see is if you are using that gist, you would be using a different version of SMO than our module.

https://gist.github.com/vincpa/1755925#file-psmo-ps1-L32-L35

The linked lines of code are going to bring in SMO from your GAC of your machine. Those are not likely to be the same version of SMO. That is environmental and out of control. We package SMO and a specific version of SMO with the module. In that same regard the gist is only 80 or so lines of code (not counting comments), where our function is over 300 lines. We do more validations and various operations that don't make the two comparable code directly.

As well, you stated that one table took 30 minutes, but 9 took less than an hour (60 minutes)...that does not completely add up to me. Either way though, I can't duplicate that test because I will not have the same hardware, workload or data. In order to be of any use you will need to collect trace information or output that shows where the command is pausing and taking the time to work (whether that is in PS or SQL Server side).

If you can do that and then submit as a bug report we can look at what can be done.
