### ISSUE TITLE
Export-dbauser creates many files but only the last one has everything

### ISSUE THREAD

**Issue by SQLAmanda** [sqlcollaborative/dbatools#6163]
Export-dbauser creates multiple files, many times the same but sometimes different. The only file that includes everything, consistently, is the last file.
I had a user who existed in 2 dbs, in 3 roles, but had an extra db level perm. before i put the -excludeGoBatchSeparator in i got a file with just GO in it for every database on the system. Then, i got 1 empty file, 3 files for the first database, and 3 files with both databases.
Using 1.0.50, because i downloaded via zip and that's what was offered.
syntax: Export-dbauser -SqlInstance MyInstance -User Domain\user -ExcludeGoBatchSeparator

**Comment by wsmelton** [comment]
Fairly sure we had this reported... May not be exact.

**Comment by ClaudioESSilva** [comment]
Hey, I already digged on this and the problem is on the output file path generation.

https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaUser.ps1#L177

This is being calculated for each database. If `-Database` is not being used or used but more than one value this will probably end in more than one output file.

In my opinion we can output just one file per instance (will include all/specified databases). We can always run multiple times, 1 per database if we want 1 file per database (the other way around would not be possible). 

@potatoqualitee @wsmelton do you agree?

**Comment by wsmelton** [comment]
I would prefer we match the logic used in `Export-DbaLogin` to make them all consistent.

**Comment by wsmelton** [comment]
The focus on what file is created should be based on the object the command is processing, which are users and not databases. I would say if only Path is provided then you create one for each user (not database) and then if FilePath is provided it all goes into one file. 

This is the logic I thought Export-DbaLogin was following but it is not applying correctly either.

**Comment by ClaudioESSilva** [comment]
Just to give an update. I'm working on this

**Comment by ClaudioESSilva** [comment]
PR #6350 fix this one. Will be available on next release.
If you find something wrong let us know.
