### ISSUE TITLE
Is Write-DbaDbTableData really that slow?

### ISSUE THREAD

**Issue by kort3x** [sqlcollaborative/dbatools#6510]
Hi,

I use Write-DbaDbTableData looping through custom objects (10-15 properties) to store them and it performs really bad for me.
A loop with 500 inserts takes about 25 seconds and more.

It is a slow box in a test environment but the same loop takes about 3 seconds when I use Write-SqlTableData and less than a second with Invoke-Sqlcmd.

#### PowerShell version:

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.2.9200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### dbatools Module version:

Name    : dbatools
Path    : C:\Users\xxx\Documents\PowerShell\Modules\dbatools\1.0.107\dbatools.psd1
Version : 1.0.107

#### culture

LCID             Name             DisplayName
----             ----             -----------
1031             de-DE            Deutsch (Deutschland)

#### SQL Server:

Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Express Edition (64-bit) on Windows Server 2012 Datacenter 6.2 <X64> (Build 9200: ) (Hypervisor)

#### Language
Deutsch

**Comment by wsmelton** [comment]
> It is a slow box in a test environment but the same loop takes about 3 seconds when I use Write-SqlTableData and less than a second with Invoke-Sqlcmd.

Show your work please....

**Comment by wsmelton** [comment]
> Write-SqlTableData and less than a second with Invoke-Sqlcmd

We do not own nor have access to compare what internal logic or processing is going on in these commands. So you will need to show more evidence of how you are timing the executions, sample data, more definition around "slow blox in a test environment".

**Comment by kort3x** [comment]
I have no idea how to post my actual stuff in a meaningful way.

But here is a mockup using FileInfo objects i quickly threw together:
https://gist.github.com/kort3x/e6c54bea927b087f0d8dbc11e5b32533

Don't judge me on my hacky SQL query. I am really bad at this. That's why I wanted to use Write-DbaDbTableData in the first place. :)

Results on my box:

```
PS C:\dev\pwl> .\compareWriteToDB.ps1 -Method SqlCommand
Object count: 2461

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 11
Milliseconds      : 281
Ticks             : 112810410
TotalDays         : 0,000130567604166667
TotalHours        : 0,0031336225
TotalMinutes      : 0,18801735
TotalSeconds      : 11,281041
TotalMilliseconds : 11281,041


PS C:\dev\pwl> .\compareWriteToDB.ps1 -Method DbaDBTableData
Object count: 2461

Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 58
Milliseconds      : 127
Ticks             : 1781276265
TotalDays         : 0,00206166234375
TotalHours        : 0,04947989625
TotalMinutes      : 2,968793775
TotalSeconds      : 178,1276265
TotalMilliseconds : 178127,6265
```

**Comment by kort3x** [comment]
Results in v7 and v5.1 are identical

**Comment by kort3x** [comment]
had an error in the gist.
Should be fixed now

**Comment by wsmelton** [comment]
Why are you looping over each record to insert vs just passing in the whole object to our command?

Looping is going to always be slower:

![image](https://user-images.githubusercontent.com/11204251/80923101-01c36b00-8d47-11ea-8322-40673a516636.png)

Compared to not looping and passing in the whole object:

![image](https://user-images.githubusercontent.com/11204251/80923113-169ffe80-8d47-11ea-8038-bd6a1b5370f1.png)

**Comment by kort3x** [comment]
In my mockup everything is written to the same table.

In my actual stuff every object is analyzed and then written to a fitting table.

**Comment by wsmelton** [comment]
Is that supposed to explain something more on why you are looping through records instead of passing the whole object?

The command overall is not performing "slow" that I'm able to determine.

If you can provide more evidence to contradict that or offer where it can be improved please do open a new issue with those findings.

**Comment by kort3x** [comment]
I strongly believe I provided enough "evidence" and I think you are missing or ignoring the point.
Just compare the numbers in my example:
- Using your cmdelt takes 3 minutes to write to the database.
- Using my hacky Invoke-SQLcmd takes 11 seconds.

If this is not a strong case for  Write-DbaDbTableData being slow I don't know what is.

Guess I got my answer and will not use dbatools.
So much for "the community's powershell sql module".

**Comment by wsmelton** [comment]
The issue with your numbers is you are not using the strength of PowerShell or SQL Server to perform you work. Provide an example of your timing that follows the example I provided using a set based/batch method and you will see your timing improve.

This is not the proper way you insert data into a database:

```
if ($Method -eq "DbaDBTableData"){
    Measure-Command{
        foreach ($item in $data) {
            Write-DbaDbTableData -InputObject $item -SqlInstance $serverInstance -Database $Database -Schema $Schema -Table $Table
        }
    }
}
```

This would be the proper use of our command:

```
Write-DbaDbTableData -InputObject $data -SqlInstance $serverInstance -Database $Database -Schema $Schema -Table $Table
```

In comparison my timing is *also creating the table* not just inserting data. As well, our command does not simply throw the data into the table itself, we go through and validate the object your passing in. This is why it is invalid to compare our command with `Invoke-Sqlcmd`, you will always (and I mean *always*) see faster timing passing T-SQL directly into SQL Server for inserts. That is basic logic because you are putting all the work on SQL Server at that time. This is no different than choosing to use SSIS over PowerShell to perform ETL processing.

If you do not chose to use the module that is your choice. If you also want to provide snide comments around responses because they do not provide the answer you want, without considering other points of view....that is your free choice. Either way you have not shown evidence that warrants calling the command "slow".

**Comment by kort3x** [comment]
I give you that my usage is not the best way to use your cmdlet. You are absolutly right about that and I know that passing the the whole batch would be more performant.

And I also give you the "snide comment" thing. Sorry about that. I also realized that my title might be considered harsh in English - guess that's me being too German and a case of culture clash.

Still, in both my timings I am doing the same stuff. Even if my implementation is not the best way to do it you should not ignore the numbers.

> In comparison my timing is also creating the table not just inserting data.

In both my timings the table already existed.

> our command does not simply throw the data into the table itself, we go through and validate the object your passing in

I would propose a parameter like "-SkipValidation" if that's what's causing this. Let me just throw something at the server and see if it sticks.

> you are putting all the work on SQL Server at that time

I would argue that's where it belongs.

**Comment by wsmelton** [comment]
> I would propose a parameter like "-SkipValidation" if that's what's causing this. Let me just throw something at the server and see if it sticks.

We can't really do that easily. Part of what we are doing in that process is matching up data types for the data object being input. This has to be done in large part because the command is written around SqlBulkCopy. The main premise behind the command being developed was for writing large sets of data. Which the overhead of all that likely won't make it a good use case for RBAR type activity.
