### ISSUE TITLE
[Bug] - shortlinks on dbatools.io/command-name no longer work

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#6518]
ugh, not sure when this happened but i gotta fix it

**Comment by wsmelton** [comment]
@MikeyBronowski we have redirection setup on dbatools.io that should be redirecting the request to the docs site, that is what I believe has broken.

Unless @potatoqualitee wants to I don't believe the fix for this issue is going to be updating all our links to the absolute link of the docs.dbatools.io site.

**Comment by andreasjordan** [comment]
Works now, closing.
