### ISSUE TITLE
Dbatools and AWS RDS

### ISSUE THREAD

**Issue by chambrick** [sqlcollaborative/dbatools#6520]
It was suggested that I create an issue to initiate a discussion.  I know that dbatools has some parameters to work with Azure but I would love to see how maybe I could be of any help to further the use with AWS RDS.  I am not the strongest coder but would be eager to learn how I could contribute to this part of the dbatools if it would be helpful.  I would really like to do a sql presentation on how dbas could use dbatools with aws to try to encourage further learning.  Would love to hear any thoughts or comments the dev team or contributors have.  Thanks.

**Comment by wsmelton** [comment]
What against AWS RDS SQL Server is not supported?

AWS RDS SQL instances are strictly just SQL Server running on an EC2 instance in the background. So for the most part code we have should actually work fine, short of a few things like file system or OS level access (e.g. port configuration, etc.).

**Comment by chambrick** [comment]
Yes you are correct about AWS RDS somewhat.  This might be a poor analogy but sort of like running a managed instance in that you can have multiple databases, you can use SQL Agent, etc but there are limitations such as some of SQL Agent like alerts, operators and dbmail are not accessible.

I was just wondering more about say adding in support for AWS similar to the way you have with some Azure abilities.

For example with the Backup-DbaDatabase command you have 2 Azure Parameters ( [-AzureBaseUrl <String[]>] and [-AzureCredential <String>] ) and I was just wondering if there was any plans to help support AWS type parameters and thought if I could help be a part of that I was offering.  But the hard part is Google Cloud is coming up in some popularity and so where do you draw the line.

So my submitting the issue was more along the lines of just seeing what expanded options there might be, or if there has been any discussion of being involved with AWS future options and plans.  Hopefully this makes sense.

**Comment by wsmelton** [comment]
The Azure parameters we have for the backups and restores are tied to the Backup To URL feature in SQL Server itself. We don't support touching Azure resources directly such as Azure Storage accounts. We simply piggy back off what SQL Server allows.

**Comment by wsmelton** [comment]
The line is drawn around cloud support or features against cloud when there becomes a heavy dependency around needing other tooling for the code to run at all.

GCP for example requires authentication around service keys. To support that requires use for the Cloud SDK from Google. We won't allow writing commands around those tools because it puts more on us to maintain, test and all to put out something that is sufficient and consistent on usage.

We have wrappers around some 3rd party things that simply don't run if they don't exists. We have been able to make those fail gracefully in that manner.

I see it as being case by case. If you make a case for something, we have enough interest and someone willing to help maintain for the future...then we can look at how it can be added.

The backup and restore commands themselves are very well guarded now because of their popularity...they are bread and butter for some DBAs use cases. I have not supported AWS RDS for months now so have forgotten some details on how those backups or restores are done. If you want to provide a code example or just process tree of how that is done wrapper scripts could be an option to include.

We have a few commands that support AWS and Azure (I think) in the same command. Getting the OS info command I added hitting the local ending in EC2 instance for the metadata. That is native to Windows use case since it uses a command that if built in, not 3rd party.

**Comment by chambrick** [comment]
Shawn,

I really do thank you for taking the time and effort to help me understand what is taking place and how you guys are moving forward.  I can imagine the cloud support would get rather complex and you guys need to draw the line clearly so I appreciate that.  I will just kind of start playing around to see what functions will and won’t work with AWS RDS.  Some are obvious based on feature support and some are not so cut and dry.

Thanks again,

Corey Hambrick

**Comment by wsmelton** [comment]
I think it would be good as you find commands that have issues or just flat won't work that we come up with support switch or logic like we do for some Azure SQL stuff.

That way we can educate folks on what you can and can't do against the cloud product of SQL Server.

So if you find those we can build a list via issues. We can add a label for AWS RDS or something to easily identify.

**Comment by chambrick** [comment]
I will do.  Thanks again.

**Comment by potatoqualitee** [comment]
Yeah, we might revisit this in dbatools 3.0 but RDS presents a challenge because a lot of us that work on dbatools have Azure accounts to test, but not RDS. And azure is also desirable because there's just so much SQL support there. It would be a huge time investment to ensure things work across 3 clouds and my only hope right now is that dbatools 2.0 will support Azure even better.

So closing this for now, but perhaps in a few years we can revisit, so sorry 😭
