### ISSUE TITLE
-SQLCredential is not passing the credential in Get-DbaDatabase

### ISSUE THREAD

**Issue by aileenbruce** [sqlcollaborative/dbatools#6533]
$cred = Get-Credential -credential mycredential
Find-DbaInstance -ComputerName xdcomputer -ScanType SqlService -SqlCredential $cred | Get-DbaDatabase

it does not pass mycredential it uses my windows login instead
I am using version 1.0.108 of dbatools

I am just trying to get a list of instances and databases on a server

It returns nothing. It works on my local machine using my local credentials  only issue is when it goes to remote machine it sends my windows login which does not work on that database server.
I had a person whose windows login on that machine is allowed on that database.  He tried for me using above script and got results.  He also looked in the logs and saw that it was trying to connect with my windows credential not the SQL credential I was putting into -SQLCredential.

last issue I saw around this type of issue was in 2018 fixes #4342

**Comment by wsmelton** [comment]
That would be by design. Check the help of the command and you can see the details around how the `SqlService` scan type works and what it needs.

You would need to pass your `$cred` object to `-Credential` and not `SqlCredential`. The `-SqlCredential` would be reserved for use with `SqlConnect` scan type.

**Comment by aileenbruce** [comment]
So in changing this to Get-DBADatabase -SqlInstance xdcomputer\mssql2016prod -SqlCredential abac\ile  It passes the windows login not the credential I put in.
Get-DBADatabase does not allow passing in just -credential  So how do I get this to pull the correct credential.

**Comment by aileenbruce** [comment]
Also this command works on Windows 10 after further research but not on Server 2016.

**Comment by wsmelton** [comment]
`Get-DbaDatabase` does not contain a parameter for `-Credential` so trying to pipe `Find-DbaDatabase ... -Credential` will not be supported because PowerShell cannot bind the parameters in piping.

You need to split the two calls out if you have to deal with credentials for different command types. Rework how you are trying to gather the information.

**Comment by aileenbruce** [comment]
I used -SQLCredential in the example I provided it passes my windows login credential instead of the SQLCredential I am providing.  It is doing this on Windows Server 2016 but works fine on my local Windows 10 workstation.

taking Find-DbaInstance completely out of the equation and running just Get-DbaDatabase results in the same issue of login failure for user with my windows login not my SQL login.

**Comment by ClaudioESSilva** [comment]
Hi @aileenbruce,

The `-SqlCredential` parameter only accepts an object of type `PSCredential`

You need to use it like this:

``` powershell
# You will be prompted for password
$cred = Get-Credential abac\ile
Get-DBADatabase -SqlInstance xdcomputer\mssql2016prod -SqlCredential $cred
```

Does this works for you?
