### ISSUE TITLE
[Documentation] CBH for New-DbaXESession lacks examples

### ISSUE THREAD

**Issue by wsuhoey** [sqlcollaborative/dbatools#6536]
### Summary of new feature

The Comment Based Help (CBH) for New-XESession needs more examples.
It would be helpful if it some examples were added for:
.AddTarget
.Alter
.RemoveEvent
.RemoveTarget
etc.

### Proposed technical details (if applicable)
¯\_(ツ)_/¯
### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
1.0.109

**Comment by wsmelton** [comment]
I would not see that as help, but expanding the command to offer the ability to pass those in as parameters.

I think the command as-is was just a initial version to get the functionality available in our module. I think now is time to expand it. 

References to remove would not be usable in this command because you are creating a "new" XE session, there would be nothing to remove. You can do the remove method using the Get command, but maybe that needs to be a new command for `Set-DbaXeSession`.

**Comment by potatoqualitee** [comment]
Yeah this is a super advanced command in that creating sessions from scratch is near impossible which is why I put a lot of emphasis on our XETemplate commands. Will close because `New-DbaXESession` is only for people who really know what they are doing and won't benefit from any example I can come up with.
