### ISSUE TITLE
Support for non default ports when querying cmdlets related to Availability Groups.

### ISSUE THREAD

**Issue by amon09** [sqlcollaborative/dbatools#6604]
### Summary of new feature

Currently if I run `Get-DbaDbBackupHistory` cmdlet against an instance that contains availability groups, it would fail to get results from all replicas. For example, for a default Sql Server instance, the replica name would be `SERVERNAME` and for a named instance it would always be `SERVERNAME\INSTANCENAME`. If the default instance does not listen on `1433` or if the browser service is disabled/UDP 1434 is blocked(for named instances), the cmdlet will fail to return results for all replicas. 

```
$AvailabilityGroupBase = ($server.AvailabilityGroups | Where-Object { $_.AvailabilityGroupListeners.name -eq $agShortInstance })
$AgLoopResults = Get-DbaDbBackupHistory -SqlInstance $AvailabilityGroupBase.AvailabilityReplicas.name @PSBoundParameters -AgCheck -IncludeCopyOnly
$AvailabilityGroupName = $AvailabilityGroupBase.name
Foreach ($agr in $AgLoopResults) {
    $agr.AvailabilityGroupName = $AvailabilityGroupName
}
```

Similarly there are other cmdlets, for e.g `Sync-DbaAvailabilityGroup` that could potentially run into the same issue (unless we use the `-Secondary` parameter explicitly in this case).

```
if ($InputObject) {
      $Secondary += (($InputObject.AvailabilityReplicas | Where-Object Name -ne $server.DomainInstanceName).Name | Select-Object -Unique)
 }

 if ($Secondary) {
     $Secondary = $Secondary | Sort-Object
     $secondaries = @()
     foreach ($computer in $Secondary) {
         try {
             $secondaries += Connect-SqlInstance -SqlInstance $computer -SqlCredential $SecondarySqlCredential
                } 
```

### Proposed technical details (if applicable)

I'm sure there is a better elegant way to achieve this, although the following changes for `Get-DbaDbBackupHistory` works well for me because we use a common non-default port per cluster. I would assume there are people who may have unique ports per instance within the cluster itself though.

```
$port = (Get-DbaTcpPort -SqlInstance $instance).port
if ((($server.AvailabilityGroups.count -gt 0) -and ($server.AvailabilityGroups.AvailabilityGroupListeners)) -and ($agCheck -ne $True)) {
...
$AvailabilityReplicas = $server.AvailabilityGroups.AvailabilityReplicas.name | ForEach-Object {-join ($_, ",$port")}
```

Note, I added an additional condition `-and ($server.AvailabilityGroups.AvailabilityGroupListeners)` here because an availability group can still exist without a listener and in that case the cmdlet will throw an exception because the listener passed down will be `NULL`

### Latest version of dbatools as of writing

1.0.113

**Comment by amon09** [comment]
Before and after making the changes:

![image](https://user-images.githubusercontent.com/16796927/85284135-47c9bf00-b4ac-11ea-908c-b716a72863f7.png)

**Comment by wsmelton** [comment]
This would break if the individual running the command session does not have local rights to query the server.

**Comment by wsmelton** [comment]
Main reason just background of why we are missing this support is because of SMO and SQL Server not providing native support of it.

DSC for SQL Server and sqlserver module all have the same problem.

Adding on trying to find the port via SQLWMI methods require expanding the command to require an additional credential to be supported. The average environment the DBA won't have local admin rights to find that port.

A preferred method would be to use a native method in SQL, possibly via T-SQL. This way we can simply reach out to figure out the port with additional permissions being considered.

**Comment by amon09** [comment]
That makes sense. Thanks Shawn. I'll take another stab at it.

**Comment by andreasjordan** [comment]
If you don't mind, I will use this issue to sort some thoughts about this.

Almost all commands have a parameter `-SqlInstance` which is able to take hostname, instancename and port. So using non default ports is no problem.
But `Get-DbaDbBackupHistory` is calling itself recursively in conjunction with availability groups. For these calls, the parameter `-SqlInstance` is not taken from user input but automatically from `$server.AvailabilityGroups.AvailabilityReplicas.Name`.
There is one similar case that I know: `Add-DbaAgDatabase` is using `($ag.AvailabilityReplicas | Where-Object Role -eq Secondary).Name` if the parameter `-Secondary` (`[DbaInstanceParameter[]]` like `-SqlInstance`) is not provided. So when using non default ports for the secondaries, the user has to use the parameter `-Secondary`. Or let's say: The user has the ability to provide all information to work with non default ports.
Coming back to `Get-DbaDbBackupHistory` I think there has to be a way to provide all used `-SqlInstance` information from the commandline. Maybe a parameter `-AgInstance` (`[DbaInstanceParameter[]]` like `-SqlInstance`) which will be used instead of `$server.AvailabilityGroups.AvailabilityReplicas.Name`.

Let's have a look at commands that call `Get-DbaDbBackupHistory`, because they have to use this to get things right.
Every call of `Backup-DbaDatabase` runs `Get-DbaDbBackupHistory` at the end to get information about the just taken backup. This call should never ever run `Get-DbaDbBackupHistory` against other instances than the one where the backup was just taken. So it should use a parameter like `-OnlyThisInstanceAndNoRecursiveCallsPlease` which is there already because this is what the internal parameter `-AgCheck` does. I don't like the name because I think it's worded the wrong way round and should be named `-SuppressAgCheck` (maybe with an alias `-AgCheck` for backward compatibility). This parameter should then be used at `Backup-DbaDatabase`.
`Add-DbaAgDatabase` uses `Get-DbaDbBackupHistory` when `-UseLastBackup` is used. As the instance is definitly part of an availability group, the recursive calls would fetch the history from all replicas. But as we are just about to add the database to the replicas, there should not be a history of that database on any other instance than the primary. So this call should use the suppress parameter as well.

Reading all this again, I think that the suppress parameter in `Get-DbaDbBackupHistory` and using it in `Backup-DbaDatabase` is the key to fix the issues with `Add-DbaAgDatabase`. Having a parameter `-AgInstance` in `Get-DbaDbBackupHistory` would be a plus when using this command directly or in other commands like `Get-DbaLastBackup` in conjunction with availability groups. But for that the new parameter would have to be added everywhere `Get-DbaDbBackupHistory` is called.

**Comment by wsmelton** [comment]
> But Get-DbaDbBackupHistory is calling itself recursively in conjunction with availability groups. For these calls, the parameter -SqlInstance is not taken from user input but automatically from $server.AvailabilityGroups.AvailabilityReplicas.Name.

This is because users do not want to have to pass in every secondary replica for us to look up and try to build the AG backup history since backups can be taken across any replica. This was put in but in all likelihood really should just be reverted and ripped out; then a proper AG related command built to handle it better..or at least more efficiently for troubleshooting purposes.

> Coming back to Get-DbaDbBackupHistory I think there has to be a way to provide all used -SqlInstance information from the command line. Maybe a parameter -AgInstance ([DbaInstanceParameter[]] like -SqlInstance) which will be used instead of $server.AvailabilityGroups.AvailabilityReplicas.Name.

This goes back to the first point to a degree, in that DBAs do not always know or have a handy list of all the replicas in a given SQL Server Availability Group. This is why we look them up via the SMO object. For those that do have that information, along with the custom ports for each can just as easily call the backup history command for each replica and obtain the backup information needed; but this may be where coming up with an AG specific command for backup history is more suited.

@Stuart-Moore thoughts?

**Comment by andreasjordan** [comment]
I set up a tree to illustrate my ideas: https://github.com/andreasjordan/dbatools/tree/demoAgSupport
Changed AgCheck to SuppressAgCheck and used it in Backup-DbaDatabase so far.

**Comment by andreasjordan** [comment]
About `-AgInstance`: I think it's not necessary. To get the results from all replicas, just put all replicas in `-SqlInstance` and use `-SuppressAgCheck`. Or do I miss something?

**Comment by andreasjordan** [comment]
Hi @amon09 , as we have Get-DbaAgBackupHistory now, I will close this issue.
