### ISSUE TITLE
New-DbaAvailabilityGroup change parameter FailureConditionLevel default value

### ISSUE THREAD

**Issue by Ventilios** [sqlcollaborative/dbatools#6605]
### Summary of new feature

Currently the parameter FailureConditionLevel of New-DbaAvailabilityGroup defaults to 1 (OnServerDown). When deploying an Availability Group you might get unexpected results testing Availability Groups. Especially when comparing a deployment that followed the Microsoft documentation (Wizard or T-SQL). 
I would like to see the default FailureConditionLevel using the same default for this parameter as CREATE AVAILABILITY GROUP (T-SQL) - https://docs.microsoft.com/en-us/sql/t-sql/statements/create-availability-group-transact-sql?view=sql-server-ver15 - Failure Condition Level 3: 
>  "Specifies that an automatic failover should be initiated on critical SQL Server internal errors, such as orphaned spinlocks, serious write-access violations, or too much dumping. _This is the default behavior._". 

### Proposed technical details (if applicable)

Instead of the default that is currently applied `[string]$FailureConditionLevel = "OnServerDown"`, this should be changed to `[string]$FailureConditionLevel = "OnCriticalServerErrors"` (Failure Condition Level 3).

### Latest version of dbatools as of writing

I currently use Version 1.0.113.

**Comment by amon09** [comment]
This is a great catch. Hopefully it gets fixed soon. :)

**Comment by andreasjordan** [comment]
I vote for this as well! Can you please share your point of view on this @potatoqualitee @wsmelton ?

**Comment by wsmelton** [comment]
Add to the reaction 👍 if you would like to see the change. To me, it should stay where it is because level 3 will cause unnecessary failover of AGs in a given instance (and I've seen it happen). I'm not too concerned with what Microsoft has documented or what their wizard sets it to for this particular setting.

I mean do you really want failover to occur when some ignoramus sites there in a database on the instance (not in the AG) and causes a ton of stack dumps to get written to the log path for the instance? The "too many dumps" are not associated with the database in the AG, it is instance wide.

**Comment by andreasjordan** [comment]
Then we should add the defaults to the documention - only a few have a look at the source code.
Especially if the defaults differ from the default of the SQL commands.

**Comment by andreasjordan** [comment]
Maybe we can even tell the user why we have a different default. That would be a plus for dbatools over SQL.

**Comment by OliverUweHahn** [comment]
Sorry. I disagree with wsmelton.
I have many customers that are using AGs.
But, I have no customers where the default setting is a problem.
Regarding stack dumps. There has to be a reason for the stack dumps. 
And I am not sure if I would prefer to run on a primary node that throws stack dumps every now and then.
There is a common issue with unwanted failovers, if you are taking VM snapshots.
For that reason you may have to tune the cluster network thresholds.
Otherwise I would vote for the change. And I agree with andreasjordan. The users need to be aware of this non-default setting.
If there are many undocumented non-default settings, many users may doubt and rethink "oh - I need to understand the entire code behind to be able to use dbatools".
And that would be a shame. :-(

**Comment by potatoqualitee** [comment]
> If there are many undocumented non-default settings, many users may doubt and rethink "oh - I need to understand the entire code behind to be able to use dbatools".

This is such a tough one. While I agree that we shouldn't stray from defaults too much, I also think it shouldn't be off the table. Microsoft sometimes changes defaults between SQL Server versions, and there have been a number of vocal critics of some defaults (max memory comes to mind and tempdb setup before they fixed it), and we have an opportunity to address this with our toolset.

At the same time, we have 3 AG pros who do wish for this change and took the time to respond. @FriedrichWeinmann what are your thoughts? I'm leaning to changing it.

**Comment by OliverUweHahn** [comment]
@potatoqualitee : I completely agree! There are a few SQL Server defaults that are "sub-optimal". :-)
MAX MEMORY, TempDB and MAXDOP are truly candidates of default settings where DBATOOLS can do it better.

**Comment by FriedrichWeinmann** [comment]
Hm, from the sound of it, changing to `OnCriticalServerErrors` sounds reasonable.
We could make this a configurable setting, so that anybody who wants to have a different default setting for his organization can roll out that setting using config.

e.g.:

```powershell
[string]$FailureConditionLevel = "OnServerDown"
```

Would then become:

```powershell
[string]$FailureConditionLevel = Get-DbatoolsConfigValue -FullName DAG.Default.FailureConditionLevel
```

(plus the associated Set-DbatoolsConfig call for initialization and maybe a new configuration validation)

Would be a low effort change, want me to do that?

**Comment by potatoqualitee** [comment]
Heck yes, thank you @FriedrichWeinmann ! Thank you so much. So change the current default, then add a config for it 🏆  Can you also update the docs?

**Comment by andreasjordan** [comment]
Hi @FriedrichWeinmann - do you remember this?

**Comment by andreasjordan** [comment]
@potatoqualitee - I can open a PR for this. Where do you want the inital config to be set? There are currently some files with "Set-DbatoolsConfig". Do you want a new file for AG config or add it to an already existing file?

**Comment by potatoqualitee** [comment]
yep, you can open a new AG config, thank you 🙇🏼

**Comment by andreasjordan** [comment]
I'm not sure about the parameters of Set-DbatoolsConfig, so can @FriedrichWeinmann please have a look at the linked PR?
