### ISSUE TITLE
ConnectTimeout on every command? Because of Azure.

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#663]
### Is this a *feature* OR *bug*:

feature

### System Details
Add a connect timeout that's passed to Connect-SqlServer for ppl who use Azure. This will impact every command.

Or we can up the timeout to like 10 but it'll take a long time for things to fail.

**Comment by wsmelton** [comment]
Why would use of Azure matter with timeouts? Are you referring to Azure SQL?

I would say this bleeds into the configuration that @FriedrichWeinmann was/is working on. No reason to update every command necessarily to pass in one parameter just because of Azure. Just have it as a configured value that each command then reads in?

**Comment by potatoqualitee** [comment]
Done - removed non-defaulttimeout
