### ISSUE TITLE
Update-DbaInstance add option for /SkipRules=RebootRequiredCheck

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#6643]
### Summary of new feature
Microsoft has an undocumented option when performing patching/installs ---- "/SkipRules=RebootRequiredCheck" this skip rules allows you to install a patch even if a pending reboot is found on the machine.  We typically only reboot machines during their maintenance window, but if we miss that window and a new CU is released in between, we can still apply the patch by passing in the command line /SkipRules=RebootRequiredCheck

By providing this functionality, as for instance an optional flag such as -SkipRebootCheck then we have the option to use it or not.

The whole intent of this is that even if a reboot is pending on the machine, it may be for a variety of reasons and none of which may apply to your SQL Server.  If that is the case, then you can use the /SkipRules=RebootRequiredCheck to ignore any pending reboot and still apply a patch.

### Proposed technical details (if applicable)

here are some examples of how we use it in our shop:

```
-- installing a patch
"\\server\SQL Server Installs-Patches\2016\SP2\CU13\SQLServer2016-KB4549825-x64.exe" /SkipRules=RebootRequiredCheck

-- uninstall a patch
"D:\SQL Patches\2016\SP2\CU11\SQLServer2016-KB4527378-x64.exe" /ACTION=RemovePatch /InstanceName=INS1_D /SkipRules=RebootRequiredCheck

-- installing the base install with a config file, UpdateEnabled & SkipRules
"D:\SQL Patches\2012\setup.exe" /ACTION=INSTALL /IACCEPTSQLSERVERLICENSETERMS /CONFIGURATIONFILE="D:\SQLSERVER\Configuration Templates\SQL2012_ConfigurationFile_IIS1Dev.ini" /UpdateEnabled=True /UpdateSource="D:\SQL Patches\2012\all-patches" /SkipRules=RebootRequiredCheck

```

### Latest version of dbatools as of writing
1.0.112

**Comment by wsmelton** [comment]
This is not an fully undocumented feature. It is actually noted in a KB article: [KB2008982](https://support.microsoft.com/kb/2008982).

However, considering it is documented as an option that should only be used when Microsoft supports notes to use it, I do not believe we should offer it.

There are "undocumented" things we include in some commands but they are not passive in nature and generally to grab info and not to circumvent checks and balances done during patching.

If there is a desire to use this functionality for deploying patches without following proper support process from Microsoft, then I would advise just deploying the patch without use of our command.

**Comment by cmuncan** [comment]
Hi @wsmelton thank you for this info but I just posted to the slack channel https://sqlcommunity.slack.com/archives/C1M2WEASG/p1594240968229900 where I outline my findings and why this feature would be needed

**Comment by nvarscar** [comment]
I could offer to add an `-ArgumentList` parameter that would add any custom command line parameters to the .exe call. It would be up to user to decide whether to use them or not. Something like 
```powershell
Update-DbaInstance -ComputerName srv1 ... -ArgumentList "/SkipRules=RebootRequiredCheck"
```

**Comment by cmuncan** [comment]
I can 120% live with and agree with the optional parameter of `-ArgumentList`  hopefully this will be agreed upon and get deployed!  thank you very much

**Comment by wsmelton** [comment]
I'm aware of why you may need it (that is documented in this issue), but we can't provide the ability for a user to directly use something that Microsoft has explicitly documented should not be used unless instructed to by Microsoft.

We allow configuration of startup parameters but do not explicitly provide those that should or shouldn't be used as an example. So, I can accept providing a parameter that would allow the user to pass in whatever additional parameters that they want.

@nvarscar I would probably name it something like `-AdvancedParameter` then just state in the help to allow additional parameters to be *appended* to the command. Not sure if you may want it to be a hashtable or just string and accept whatever is there. (e.g. `-AdvancedParameter @{SkipRules='RebootRequiredCheck'}`). Especially since to there are supported values that can be passed to SkipRules and they are passed with a space delimiter.  So for multiple, it would be `-AdvancedParameter @{SkipRules='RebootRequiredCheck,VSShellInstalledRule'}` Then you would be able to simply convert to space delimiter instead of comma...just initial thoughts.

**Comment by nvarscar** [comment]
@wsmelton Hashtable would've been my go-to option if all of the parameters followed the `/key=value` format. However, I feel like some of them might be just `/key` or are provided with comma or space-separated values or maybe should be quoted - I don't think I would be capable of providing proper unwrapper that would support all the possibilities. Thus, string array would probably be a best option for this particular case.

**Comment by cmuncan** [comment]
Just wanted to provide my 2 cents on this.  There are options that follow both rules, `/key=value` and `/key`.  for instance the quiet flag is just `/Q` or `/QUIET` but `/SkipRules` is  `/SkipRules=value'.  I am certain that there are quite a number of undocumented options that can be set at the guidance of Microsoft and by having a string array to allow for both options might be best but I will leave it to your coding standards
