### ISSUE TITLE
[Bug] Set-DbaAgentSchedule - Unable to set daily schedule that recurs every N days

### ISSUE THREAD

**Issue by pgdanes** [sqlcollaborative/dbatools#6677]
#### SQL Server:

```sql
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 18363: ) 
```

```sql
us_english
```

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [ ] Still buggy in powershell.exe

#### Errors Received

Cannot set daily schedule to recur in daily intervals. For example 
"Occurs every 2 day(s) at 1:00:00 PM. Schedule will be used starting on 24/07/2020."

#### Steps to Reproduce

With existing daily schedule created:
`Set-DbaAgentSchedule -SqlInstance Local_SQL_Instance -Schedule TestSchedule -Job Test -FrequencyInterval 2`

#### Expected Behavior

![image](https://user-images.githubusercontent.com/11003459/88363912-0763a680-cdb4-11ea-8e52-ce0cd27dfe1b.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/11003459/88363852-fc107b00-cdb3-11ea-977e-ab0088c5bff8.png)

**Comment by MikeyBronowski** [comment]
Looks like the problem lies here

https://github.com/sqlcollaborative/dbatools/blob/8ce1a70d5a7bf70465b0f932a165a8d3c2a19c08/functions/Set-DbaAgentSchedule.ps1#L217-L226

Adding this one line should address that issue.
```
# Create the interval to hold the value(s)
switch ($FrequencyInterval) {
"EveryDay" { $Interval = 1 }
{$_ -ge 1 -and $_ -le 100}  {$Interval = $_}
default { $Interval = 1 }
}
```

Additionally, $FrequencyInterval does not allow for some values that are accepted via SSMS (I've checked in SSMS, and 100 would be the max for this type of schedule - daily).
https://github.com/sqlcollaborative/dbatools/blob/8ce1a70d5a7bf70465b0f932a165a8d3c2a19c08/functions/Set-DbaAgentSchedule.ps1#L140-L141

![image](https://user-images.githubusercontent.com/13431760/88393057-58c46380-cdbd-11ea-9933-ea621e2e1e7c.png)

At the same time, $FrequencyInterval can accept 127 too for weekly schedule.

**Comment by andreasjordan** [comment]
Sorry, has been lost from sight. Is this still a problem with the current version?

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if this is still an issue with the current version.
