### ISSUE TITLE
New Function for Invoke-SqlVulnerabilityAssessmentScan

### ISSUE THREAD

**Issue by cmuncan** [sqlcollaborative/dbatools#6759]
Add functionality to perform Invoke-SqlVulnerabilityAssessmentScan for all databases on multiple servers\instances.

We have introduced over 100 new servers & instances and need to come up with a programmatic batch method to produce the reports for all servers in 1 script.  Since we are using DBA Tools for currently doing patching, failovers, AG health checks, etc. we would like to use this feature also.

Is it possible to add this functionality?

**Comment by wsmelton** [comment]
duplicate: #6366

You will need to utilize the `sqlserver` module for that functionality. We are not able to support it due to lack of documentation from Microsoft.

As long as you import our module first, and then `sqlserver` into the session you should be able to use both modules together. There may be a few of our commands that have some issues being that `sqlserver` uses format files that can overwrite our output...you would just need to test and verify.
