### ISSUE TITLE
Table merge ETL ?

### ISSUE THREAD

**Issue by jeffchulg** [sqlcollaborative/dbatools#6768]
Hi,

I've seen that there is a function which inserts data into a given table, but I've not seen one that would take a table from a data source and perform a MERGE statement, so that it inserts new rows, updates those which have the same key and either sets rows as deleted or deletes when data cannot be seen on source.

Will this be implemented? If it's not in your plans, how can I start the implementation? Is there a contribution guideline or something?

Thanks in advance for your reply.

**Comment by wsmelton** [comment]
There are no plans to implement a command of that nature in the module.

SMO does not have that ability and it would be pure T-SQL, so why not just do that in SQL Server were it belongs? Or use proper ETL tooling such as SSIS?

**Comment by jeffchulg** [comment]
Well, the idea is that I want to centralized some data like DDL changes history from all my servers into a single, central, one (I think this is a common use case for some DBAs.). 

This could be achieved by getting all the rows from each server, insert it into a staging table (this can be achieved with dbatools) then perform the MERGE (in plain T-SQL, this can also be achieved with dbatools, I think)... 


BUT, this is not, to me, the best way to do it because it will require more space in T-Log and is inefficient. 

SSIS could be a solution for that, but it's not what I'm looking for...

**Comment by wsmelton** [comment]
You can use PowerShell to "merge" objects together into one, but they will never be performant compared to what SQL Server's engine will do. If what you want to do is done purely with T-SQL, why not just use `Invoke-DbaQuery`?

How you "merge" tables will vary by a number of variables that I don't see us being able to code around to cover every scenario. I see this as being we provide commands that allow a user to gather the metadata they need and then can execute their specific scenario.

**Comment by jeffchulg** [comment]
I think there is a misunderstanding, so I will rephrase:

I want to extract data from a first data source (so, it's a `SELECT` statement that I can run with `Invoke-DbaQuery`). I will get back a dataset in PowerShell.

I want this dataset to be merged with a table on a second data source, not the first one. To do so, I only have one choice and it's to look at each record, check if the primary key or the overall record data exists on destination and perform an action accordingly.

I'm pretty sure it's possible to generalize this action due to the dynamic power of Powershell because:
- we can fire a query to get back the entire list of column names for a table
- we can fire a query to get back the entire list of primary key columns for a table
- we can compare source and destination structure
- we can provide an object or an XML file or anything that will provide help to the function so that it can perform a column mapping and some defaulting.

The code might no cover every scenario in the beginning, but it could, with time and experience.

**Comment by niphlod** [comment]
well, let's separate two concepts, and albeit they usually do the same thing, let's call them "merge" and "upsert" for the sake of this reply.
 
a "merge" is something among the lines of "if it matches pkey update, if pkey is in source but not in dest, insert, if pkey is not in dest, delete".
an "upsert" is something among the lines of "if it matches pkey update, if pkey is in source but not in dest insert".

for the "merge" case, I hardly see a usecase where the source is a dataset and not a table.... think 1M rows as a dataset source. it would be too damn slow compared to, e.g., truncate dest and bulkcopy to dest (which dbatools has and is blazing fast already).
If the source is a table, it falls back to the "upsert" case.

for the "upsert" case, you're basically going to either build a RBAR (if you're cool, you compare PK first, then all the columns, then fire an update query for the matching set of PK that have non matching "all other columns" and insert query for the not matching... if you're lazy you fire for each source row a preemptive update and if no rows are updated you fire an insert) or a dynamically generated `MERGE` statement (with source a table you're fine, but with a dataset you'll have an annoying cte around "VALUES ('a'), ('b'), ('c')" ). 
RBAR is crazy slow (and anyone can write it the "lazy" approach in .... 10 minutes ?). Dynamically generated `MERGE` is cool when you think it but rather a PITA if your source is a dataset, because suddenly you need to serialize everything before issuing the command.

what @wsmelton is telling is that dbatools is usually a wrapper for something that already is in SMO, and SMO does not have anything regarding this area ("merge" for the reason above, "upsert" because it's just, well, faster in TSQL).

Last but not least, your example didn't suggest quite the scenario.... if you're aggregating DDL infos from multiple servers it sounds more like an "auditing" problem, in which case you just need to "append" to a "common centralized trace table", and if you are in the need of an "upsert" because you don't "mark" the source DDL as "shipped to central trace", you are just falling in the "upsert" department (and, as myself, in the "lazy" one too ;-) )

Let us know if you think to solve the problem in another way, if it solves a real-case scenario dbatools is not against it.

**Comment by jeffchulg** [comment]
Hi, my example of DDL trace is just an example... it's a MERGE that I need to keep it as general as possible:

 "if it matches pkey update, if pkey is in source but not in dest, insert, if pkey is not in dest, (mark as deleted OR delete OR do nothing)"

If you are aggregating from more than one source, you can't afford creating one staging table per data source and per table to run a truncate an insert.

But, no worry, I understood that this cannot be performed using dbatools, but I'm sure Powershell would do the job and that's why my first post included 

> " If it's not in your plans, how can I start the implementation? Is there a contribution guideline or something?".

**Comment by niphlod** [comment]
with multiple sources you're just pushing for an even harder case, which is to consolidate in memory a possibly huge dataset, which may require "merging" in memory before even attempting the "final merge to dest".

> If you are aggregating from more than one source, you can't afford creating one staging table per data source (i.e. server instance) and per source table to run a truncate an insert.

when you did that a few times, you learn to "augment" the source dataset with a "sourceidentifier" column and have it in the staging table for the exact purpose of avoiding the high cost of doing compares in memory, which is what SQL Server is extremely good at doing.
People also find out that a simple `IGNORE_DUP_KEY = ON` on the PK solves a lot of these kind of problems, if the need is just for auditing purposes (i.e. no need to update the matching set)

> But, no worry, I understood that this cannot be performed using dbatools, but I'm sure Powershell would do the job and that's why my first post included

dbatools doesn't have the capability, we're just trying to figure out if it *should* have that capability.

That being said, what's your idea ? An RBAR approach or a "create dynamically a `MERGE` statement and fire it" ?

**Comment by jeffchulg** [comment]
I already have an plain T-SQL SP ready that generates a MERGE statement for a given table, I would just have to integrate it in PowerShell and customize/generalize it or transpose it in Powershell...

That's why I wanted to know if this could be included in dbatools and how.

**Comment by niphlod** [comment]
like this one ? https://github.com/readyroll/generate-sql-merge 

What I'm not still grasping is: do you want the source to be always a table on the same instance of the destination table or do you want to support merge to a destination table from an in-memory resultset (e.g. one returned from Invoke-DbaQuery) ?

**Comment by jeffchulg** [comment]
I did not know this one existed... It's a stored procedure I've written from scratch...

To answer your question, the best solution should be to be able to run it even from a query. It's not that difficult to do if you can create a view from the query, even temporarily...

**Comment by niphlod** [comment]
> It's a stored procedure I've written from scratch...

Maybe you'll find out that one is handling more corner cases, or if yours is covering more, considering contributing there too 👍 

I think you need to put some time with a pencil-and-paper approach and then come back with:
- scenario
- goals
- approach
- features
and a basic stub of "it'll work this way".

.... think dest in on "centralserver" and source is a query from "remote server": do you wanna create a temp table on "centralserver" with all the data the source query from "remote server" is holding ? If so, users need to accept the burden of it, and the ones accepting it I think will vouch for a proper staging table.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
