### ISSUE TITLE
New-DbaEndpoint - Default name

### ISSUE THREAD

**Issue by wsmelton** [sqlcollaborative/dbatools#6805]
Right now we validate if a name was provided. If it was not then we are appending a date to make `endpoint_<currentdate>`.

https://github.com/sqlcollaborative/dbatools/blob/475158e77caee1c5589ca952bad663f2c7aba4ed/functions/New-DbaEndpoint.ps1#L114-L117

1. I can't stand when systems do this so do not believe we need to either. If a name was not provided, then fail the command.
1. We need to be validating that the name provided does not already exist. (I do not see us doing this in the current version unless I'm just reading over it.)

**Comment by andreasjordan** [comment]
Because the type defaults to DatabaseMirroring `[string]$Type = 'DatabaseMirroring'` and every instance can only have a maximum of one mirroring endpoint and the "default" name of this endpoint is "hadr_endpoint" (when created by the SSMS wizard for availabilty groups) I would suggest only failing if type is not DatabaseMirroring. But I agree with you that failing is better than an endpoint with an name not related to the purpose of the endpoint.
