### ISSUE TITLE
[Feature] Install-DbaInstance / Invoke-DbaAdvancedInstall - Restart service after changing port with Set-DbaTcpPort

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#6865]
### Summary of new feature

Install-DbaInstance can change the port after the installation and does this in Invoke-DbaAdvancedInstall via Set-DbaTcpPort here:

https://github.com/sqlcollaborative/dbatools/blob/f19e8248310602d15eaf5f2fd35aa22e478be956/functions/Invoke-DbaAdvancedInstall.ps1#L292-L295

But it does not invoke the needed restart of the service.

### Proposed technical details (if applicable)

We could just issue a Restart-DbaService.
But on the other hand we may want to change Set-DbaTcpPort to do the restart. Or just tell the user that a restart is needed.
But if Set-DbaTcpPort has a warning output that would also show up at Install-DbaInstance.

Maybe the best way:
Add a parameter like -RestartService to Set-DbaTcpPort. If set, restart the service, if not, display a warning.
Invoke-DbaAdvancedInstall can use this switch to silently restart the service.

@nvarscar : What do you think?

**Comment by wsmelton** [comment]
Why not just go the restart?

I mean if the command is supposed to install according to the settings we ask for, then set them and if restart is needed then just restart it.

You get this using DSC. It will the up restarting the service after install multiple times.

**Comment by nvarscar** [comment]
I chatted with @andreasjordan about this and it seems more appropriate for the Set-DbaTcpPort command to support service restart instead of building this into the Install-* command, as a restart is clearly required for the change to take hold and it would only make sense for the original function to support service restart after changing the port.

**Comment by wsmelton** [comment]
I disagree with doing it so Chrissy will have final say over it being implemented.

**Comment by nvarscar** [comment]
Adding a backwards compatible change that would improve user experience in more than one way should not be a problem just because the limited PS verb list got in the way. The command that changes the port should be able to restart the service if that's what's needed to apply the change.
The function can be renamed/aliased to become Update- or whatever verb you prefer if that's what bugs you.

**Comment by andreasjordan** [comment]
To do a first small step, I opened the linked pull request. If someone wants to work on Set-DbaTcpPort and maybe change it to Update-DbaTcpPort, I would be happy to help.

My last idea from slack:
"Then I would prefer the verb Update. Update-DbaTcpPort looks good to me. What about two switches: -Restart to restart the instance, -NoRestart to suppress the warning about the needed restart. So the warning is only displayed if both switches are missing. That would help people who wrap the command in a loop to not have all the warnings."
