### ISSUE TITLE
[Bug] Export-DbaInstance doesn't export all objects advertised

### ISSUE THREAD

**Issue by alevyinroc** [sqlcollaborative/dbatools#6918]
### Report

When using `Export-DbaInstance` without `-Append` set to `$true`, object "groups" that contain multiple steps like `agent` and `dbmail` only export files for the last item in the group.

For example, the file for SQL Agent only produces the Agent jobs. The other items (Categories, Operators, Alerts, Proxies & Schedules) are not exported because `Get-DbaAgentJob | Export-DbaScript` doesn't append, it overwrites (`$Append` is passed through from the `Export-DbaInstance` parameters but it's not set to `$true` by default).

A `-Append` switch was proposed in #5380 but  I think that's meant for a different use case than was implemented with the switch as we see it today.

#### Host used

- [X] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
No errors produced - unexpected behavior

#### Steps to Reproduce
`Execute-DbaInstance -sqlinstance MYINSTANCE -path c:\tmp`

#### Expected Behavior
All objects for AgentServer, ResourceGovernor, PolicyManagement, CentralManagementServer, DatabaseMail should be included in their respective script files.

#### Actual Behavior
Only the last item in each of the listed "groups" is exported to the script file.

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.124
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU6) (KB4563110) - 15.0.4053.23 (X64) 
	Jul 25 2020 11:26:55 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

```sql
us_english
```

**Comment by wsmelton** [comment]
If folks truly want it to Append the safer bet is to have this parameter set the scripting object property `$ScriptingOptionsObject.AppendToFile` to true because that takes precedence in the `Export-DbaScript` to the parameter itself being called.

**Comment by wsmelton** [comment]
So the use of Append is used in these calls:

- [Get-DbaCustomError](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L202)
- [Get-DbaServerRole](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L213)
- [Export-DbaCredential](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L224)
- [Export-DbaLogin](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L235)
- [DBMail](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L245-L249)
- [RegServers](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L260-L261)
- [Get-DbaBackupDevice](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L272)
- [Export-DbaLinkedServer](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L283)
- [Get-DbaInstanceTrigger](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L293)
- [Get-DbaInstanceAudit](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L321)
- [Get-DbaDbBackupHistory](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L310)
- [Get-DbaInstanceAuditSpecification](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L332)
- [PBM](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L354-L356)
- [Resource Governor](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L367-L370)
- [Get-DbaXESession](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L382)
- [Agent](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L394-L399)
- [Get-DbaAvailabilityGroup](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L432)

Then in all of these, we **are not** appending:

- [Export-DbaSysDbUserObject](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L421)
- [Export-DbaRepServerSetting](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L410)
- [Get-DbaEndpoint](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L343)
- [Export-DbaSpConfigure](https://github.com/sqlcollaborative/dbatools/blob/development/functions/Export-DbaInstance.ps1#L192)

So @potatoqualitee how about we rename the parameter to `AppendToFile` and then add a note of the objects that **are not appended or affected by this parameter** (e.g. Endpoints, SPConfigure, RegServer, and SysDbuserObjects)?

Then we use that to set the `$ScriptingOptionsObject.AppendToFile` and then the ones above that we **do not** append, just need to have an update added to set it back to `$false`. Then we can remove calling the `Append` parameter on the `Export-DbaScript` and for the backup history it just would become `-Append:$AppendToFile`.

**Comment by lancasteradam** [comment]
@potatoqualitee and @wsmelton, I uploaded another commit for review: https://github.com/sqlcollaborative/dbatools/pull/6957/commits/61739e51a9cc32785c2c783b51d9cd15202a60c9 

This alternative approach simplifies the Export-DbaInstance command and adds the ability to overwrite existing exports as discussed in #5380. 

While working on this alternative I had these use cases in mind:

1. Export files to a new timestamped folder. This is the default behavior and results in a simple historical archive within the local filesystem.
2. Export files to an existing folder and overwrite pre-existing files. This can be accomplished using the -Overwrite parameter.
This results in a single folder location with the latest exported files. These files can then be checked into a source control system if needed.

The way Export-DbaInstance is structured I don't see how a -Append is useful for a caller. The reasons are:

1. A separate folder is used for each server that is being exported from. In the default case a timestamp is added to the folder name so it is a fresh set of files each time.
2. Separate files are used for each object type (i.e. there is no way to create a single file with everything appended together).

Inside the code of Export-DbaInstance it does use -Append when calling Export-DbaScript while doing a multi-step object export such as db mail. This is necessary and is of course hidden from the caller. They don't need to pass in a param for this since the expectation is the command will produce a complete file as mentioned in #6918.

Overall it is an interesting scenario so let's collaborate to find the optimal way to solve this.

**Comment by wsmelton** [comment]
We should use Force parameter to overwrite files instead of Overwrite.
