### ISSUE TITLE
Incorporate faster sql bulk copy uploads to Write-DbaDbTableData

### ISSUE THREAD

**Issue by ccastillo-id** [sqlcollaborative/dbatools#6922]
### Summary of new feature

* I use Write-DbaDbTableData to load CSVs up to our Azure databases. And it about an hour to load up a 1million+ row csv to upload. Is it possible to add a streamReader option to this function to read the CSV or just a faster way to read and upload?

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* 1.0.112

**Comment by wsmelton** [comment]
That would not be a viable option since the write command is not responsible for reading in files such as CSV. The data is brought into the session and then piped into the command. There is no data necessarily to "stream" from that perspective.

For your exact use case, I would recommend looking at [Import-DbaCsv](https://docs.dbatools.io/#Import-DbaCsv) as that is coded to use the stream reader class for directly pulling the CSV files.

**Comment by andreasjordan** [comment]
I will close this for now, but you can reopen it if you have further questions.
