### ISSUE TITLE
[Feature] Add installer for dba-multitool

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbatools#6954]
### Summary of new feature

Hi 👋 all! I have a suite of utilities under the name [dba-multitool](https://github.com/LowlyDBA/dba-multitool) (formerly Express SQL). To be brief, they are:

> ... a suite of scripts for the long haul: optimizing storage, on-the-fly documentation, general administrative needs, and more. Each script relies solely on T-SQL to ensure it is secure, requires no third-party software, and can be installed in seconds.

As far as I know, no other projects cover the functional areas that my scripts do, so I think they would be a good value add to DbaTools. 

I've been working on these for over 2 years and don't have any plans to stop maintaining them.

### Proposed technical details (if applicable)

Mimic `Install-DbaFirstResponderKit` and the like to install them from the source repository. I have a single installer script that handles them all. 

They don't (generally) support versions < 2012, so a version check would be the only deviation from the existing installer patterns. 

### Latest version of dbatools as of writing

1.0.5 - Conroy

---

I am happy to make the appropriate PR if this request is approved 👍

**Comment by wsmelton** [comment]
The ability for our module to help in managing 1+n servers across an enterprise, and the databases associated it seems these scripts would serve a good purpose in being commands that allow a user to run the code across their enterprise. Having some wrapper script that called each procedure and handled parameters would allow users more access to your tooling.

I'm not sure if your procedure output could be turned into PowerShell objects for users to see, as it would have to conform to our standard output object. Your docs do not include any sample output that I could find to verify. I do like the lint testing you do with your scripts though, that's a nice touch.

Overall we do not have any strict guidelines (in writing) at this time on community tools being added for "install". So you are more than welcome to submit a PR for review of the installation command. The problem I see though is naming it since you have `dba` in the name of your "product" having `Install-DbaDbaMultitool` looks odd to me. If you are okay with just using `Install-DbaMultitool` I think that will work?

**Comment by LowlyDBA** [comment]
> I'm not sure if your procedure output could be turned into PowerShell objects for users to see, as it would have to conform to our standard output object. Your docs do not include any sample output that I could find to verify.

I've added output to the [documentation pages](https://github.com/LowlyDBA/dba-multitool/tree/development/docs). In the cases of `sp_helpme` and `sp_estindex` there are multiple (3+) result sets, so it might be a challenge to get those to fit in with the dbatools object styles in an exec wrapper. 

`sp_doc` would be relatively easy, I think, since it just returns a single row & column with all the markdown content. `sp_sizeoptimiser` has a single result set also, so would be straightforward to wrap.

I'm curious of people's thoughts on:

* a first PR containing _just_ the installer function versus one that also includes dedicated execution functions
* any concerns/comments about only being able to have 2 of 4 stored procedures having a corresponding execute function

 > The problem I see though is naming it since you have dba in the name of your "product" having Install-DbaDbaMultitool looks odd to me. If you are okay with just using Install-DbaMultitool I think that will work?

That works for me, if it does for ya'll. 👍

**Comment by wsmelton** [comment]
Just starting with an installer command is fine. We can see from there if anyone submits a request to have commands for the commands created.
