### ISSUE TITLE
Enhancement to Restore-DbaDatabase  With -force switch

### ISSUE THREAD

**Issue by lostsole** [sqlcollaborative/dbatools#6973]
### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.
Add -force to Restore-DbaDatabase  So we don't get this warning.
WARNING: [23:12:26][Restore-DbaDatabase] Failure | System.Data.SqlClient.SqlError: Exclusive access could not be 
obtained because the database is in use.

### Proposed technical details (if applicable)

implement the same function as you have in Restore-DbaDbSnapshot when enabling the -Force switch.
--> Stop-DbaProcess -SqlInstance $server -Database $db.Name

### Latest version of dbatools as of writing

1.0.130

**Comment by Stuart-Moore** [comment]
@lostsole  is that when running with `-withreplace`? That should kill everything in the database before restoring over the top using that exact piece of code you recommend (Invoke-DbaAdvancedRestore lines 186 thru 214)

This was designed as a safety measure to stop people shooting themselves in the foot

**Comment by lostsole** [comment]
Ok, This is good to know and yes it was running with -withreplace.

 

I think the issues happened as there is too much time between killing all the open Connections to the Restore as it looks like 2 separate Foreach loops.

As I Restored all database from the backup files based on the Backup directory.

 

When we migrated, I guess there was still Applications trying to connection the Database.

 

As where in the Restore-DbaDbSnapshot the Connection is killed and then it restored as we are only dealing with the One item vs multiple items.

**Comment by Stuart-Moore** [comment]
The each in the outer ForEach is for each of the dbs being restored. Each db is restored sequentially, so it only needs to knock one out at a time. That's good enough, as the inner one is just to loop through the restores for that database which keeps it in the restoring state so nothing else is coming in.

If your app servers are hammering the database, then there is always a chance that they will get a new connection into the db before the restore begins.  There's nothing 'We' can do about that as we can't control your apps. Personally I'd either take them offline, disable the logins or drop the databases before starting the restores to ensure everyone knew the state of play during a migration rather than having a Schrödinger's database situation.

**Comment by lostsole** [comment]
Thanks for the clarification.

And yes we did stop the applications but I guess the Application group missed stopping some of the connections.

As the last time they Migrated to a new server was over 5 years ago.

But now that I know that the -withreplace = to killing the connections before restoring.

 

Thanks

**Comment by Stuart-Moore** [comment]
Great. Going to close this, as we have a workaround and if that doesn't work then it's likely to be a local environment issue which we can't do much about yet
