### ISSUE TITLE
Remove-DbaAgDatabase with -confirm$false

### ISSUE THREAD

**Issue by tspannagel** [sqlcollaborative/dbatools#6980]
### Summary of new feature

It would be great if the Remove-DbaAgDatabase function could suppress the confirmation for bulk execution. Right now it always requires me to confirm every single action.
Currently the "-confirm" switch doesn't change anything. The documentatoin states that you need to supply this parameter to get asked for confirmation. But even without this switch you get asked. 

preferred use:
```
...
foreach($db in $databases){
 Remove-DbaAgDatabase -Database $db [...]
}
...
```
### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.
1.0.131

Thanks for this awesome tool!

**Comment by andreasjordan** [comment]
Have you tried `-Confirm:$false`?

**Comment by tspannagel** [comment]
Sorry for the late reply, i think i tried. I will look at it again! Thanks for the hint.

**Comment by wsmelton** [comment]
The majority of the destructive commands we have (aka remove functions) will have `ConfirmImpact = 'High'`.  Since this is also the default `$ConfirmPreference` setting as well you will be prompted even without providing the `-Confirm` parameter directly.


As stated already though the use of `-Confirm:$false` will prevent the prompts and in automated processes allow the command to perform the task non-interactively. 

Closing this issue but please reopen if that is not the result you are seeing.
