### ISSUE TITLE
[Bug] Copy-DbaLogin doesn't sync/copy 'enforce password policy' or 'enforce password expiration' 

### ISSUE THREAD

**Issue by anwioc** [sqlcollaborative/dbatools#7055]
### Report
We are using dbatools version 1.0.112.

We are running several AlwaysOn Clusters (2017 & 2019) and just discovered that Copy-DbaLogin cmdlet does not sync or copy the the password policy or expiration of sql login users.

If you set the password policy and/or expiration for an sql user and execute following command nothing happens:
copy-DbaLogin -source Server1\Instance1 -Destination Server2\Instance2

#### Steps to Reproduce

open on primary replica new query in ssms:

```sql
--set login attributes
use [master]
GO
ALTER LOGIN [testuser] WITH DEFAULT_DATABASE=[master], DEFAULT LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
```

after that, open powershell in admin mode and execute command:
```powershell
copy-DbaLogin -source Server1\Instance1 -Destination Server2\Instance2
```

check the user on the secondary replica - no changes.

### Environmental information

```
PowerShell Version        : 5.1.14393.3866
dbatools latest installed : 1.0.112
Culture of OS             : de-DE
```
#### SQL Server:
```
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)   Nov 30 2018 12:57:58   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

us_english
```

**Comment by wsmelton** [comment]
The login already exist on the replica instance?

**Comment by anwioc** [comment]
> The login already exist on the replica instance?

yes, the login already exists.

if you create a new user and sync it to the other replica, the login attributes are copied..

**Comment by wsmelton** [comment]
In order to accomplish that with the Copy command you have to use the Force parameter so it overwrites the login to update those properties. We only "sync" permissions the properties of login are not synced in that manner.

```
copy-DbaLogin -source Server1\Instance1 -Destination Server2\Instance2 -Force
```

Alternate you might look at `Sync-DbaAvailabiltyGroup` that we added some time back specifically for use with AGs and getting objects synced between replias.

**Comment by anwioc** [comment]
Thanks for your reply.
We don't use the -Force parameter anymore because one time it did force delete all users from secondary replica and cancelled all further copy action by itself.

After that we couldn't connect to the replica anymore and had to make a disaster recovery.
These are customer sql servers with SLA contracts and the outage was bad.

I hope you understand the circumstance.

**Comment by wsmelton** [comment]
The only scenario I'm aware of that will halt processing on the command is when you use Force we are dropping the login, but to do that we have to kill any active session it may have. If we are not able to kill the session the drop attempt will cause a message to be thrown that can kill the processing. If the logins are being used on the secondaries then no the use of the Force parameter is not going to consistently work for your servers.

The command itself is not going to sync the password policy and expiration settings on the login without the use of the Force parameter though. That is by design and not a bug.

The process you are showing to set these properties is out of scope for the Copy command (not the intended use case). I would recommend using `Set-DbaLogin` for that task and simply execute it against all the replicas.

**Comment by anwioc** [comment]
Thanks for your help.
I will consult with my team how we proceed.
