### ISSUE TITLE
[Bug] connect-dbainstance or invoke-invokedbaquery is taking upward of 40 seconds to connect

### ISSUE THREAD

**Issue by SquirrelAssassin** [sqlcollaborative/dbatools#7056]
#### Host used

-  powershell.exe

#### Errors Received

Something changed in this latest version, the connect-dbainstance takes upwards of 40 seconds to connect.  This is a problem because were running azure watcher tasks that have to complete in under 30 seconds.  

I switch back to the good old classes and everything is done in under 1 second.

Here is what I ended up doing that works within 1 second.  
    $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
    $SqlConnection.ConnectionString = "Server=$server;Database=$database; User ID = $Username; Password= $Password; TrustServerCertificate = True;Integrated Security=true;"
    $SqlCmd = New-Object System.Data.SqlClient.SqlCommand
    $SqlCmd.CommandText = $sqlquery
    $SqlCmd.Connection = $SqlConnection
    $SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
    $SqlAdapter.SelectCommand = $SqlCmd
    $DataSet = New-Object System.Data.DataSet
    $SqlAdapter.Fill($DataSet)
    $SqlConnection.Close()
    return $DataSet.Tables[0]

#### Steps to Reproduce

just run connect-dbainstance or test-dbainstance 

#### Expected Behavior

query completes in under a few seconds

#### Actual Behavior

query takes upwards of 40 seconds ... I thought at first it was invoke-dbaquery, then I thought maybe connection problem ... and it was.  

### Environmental information

```powershell
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.134
Culture of OS             : en-US
```

**Comment by wsmelton** [comment]
I'm afraid more tracing will be needed from your SQL Server instance and the environment because the timing of those two commands is mainly driven by the environment (network, DNS, auth process).

The `Connect-DbaInstance` for me works and I get a connection within 827ms:
![image](https://user-images.githubusercontent.com/11204251/103307632-2bb45680-49d6-11eb-8c02-4a44616ea49e.png)

It is that fast because of my network between my host machine and the SQL Server instance I'm trying to talk to.

A comparison between using SqlClient driver and SMO is not viable. `Connect-DbaInstance` does additional things to the server object as well SMO itself making the connection to SQL Server pulls details. You can view this by tracing the connection from your machine to a SQL Server instance.

**Comment by SquirrelAssassin** [comment]
You would have to give me something to test, or produce.

It’s very consistent against a sql cluster.   

I want to like this tool but every flipping time I attempt to use it for anything it breaks, 
 time, after time, after time, like clockwork.  Something in the code changes and breaks something else.  No checks are done.   What’s 1500 functions if none of them are reliable for more then a few months.  

I use the following .. works flawless
Function SQL-Query {
    param(
        $server,
        $database,
        $sqlquery
    )
    $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
    $SqlConnection.ConnectionString = "Server = $server; Database = $database; TrustServerCertificate = True; integrated security = sspi;"
    $SqlCmd = New-Object System.Data.SqlClient.SqlCommand
    $SqlCmd.CommandText = $sqlquery
    $SqlCmd.Connection = $SqlConnection
    $SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
    $SqlAdapter.SelectCommand = $SqlCmd
    $DataSet = New-Object System.Data.DataSet
    $SqlAdapter.Fill($DataSet)
    $SqlConnection.Close()
    return $DataSet.Tables[0]
}

**Comment by wsmelton** [comment]
I'm not following. You created the issue stating connections and queries are taking seconds or minutes to run.

SMO itself has overhead whether you are using our module or raw SMO. The SqlClient does much  less work because all it does is connect and run the command you provide, nothing else. Many of our functions include validations, checks, and some prep depending on the function. A basic connection using Connect-DbaInstance averages about 600ms for me in most environments. I use this module with product integrations at work and have not see customers having issues on connections as well.

If you are observing issues then report with the details to replicate the issue. If it is consistent and we are able to replicate it then we can move forward to try and address it. Just stating you are seeing x amount of the for x command to run does not give us enough details to work with.

We have integrations and unit test for most every function in the module (all 500+). These allow us to verify the code works to a degree. We can't replicate every user's environment but most of the main contributors maintain large environments and help verify in more detail in some areas. If they are able to reproduce the issue you are observing then we can work on addressing it.

We can't fix what we don't know is an issue. If your script using SqlClient works for your needs then I would advise using that in place of our module. I have touched some environments that use of the module just didn't work for the specific use case.

**Comment by SquirrelAssassin** [comment]
I stoped reading after line two.  I spent more time using this tool and figuring out it sucks then just writing it some other way.  Done with this tool.

**Comment by wsmelton** [comment]
...For those that find this later on.

It is advised when using our module to test before updating to the latest release. I commonly hard-code a version check for importing the module explicitly in my scripts; especially those provided as solutions to customers/clients. Use of the module in Azure Automation allows you to specify a version as well and stick to using that version. This prevents unnecessary issues when changes are made to the module that affects how your scripts or processes/workflows run.

Use of our module should be no different than how you treat upgrades of critical applications in your environment. This is true with any module or software.

Changes have been made to `Connect-DbaInstance` but I'm not aware of any of those causing issues with connection timing. Most of those changes have been out in the wild for 2+ months now. Since those changes have been in place there have been over 40k downloads of the various versions that have included the changes. I have not seen any issues pop up about it.
