### ISSUE TITLE
Set-DbaLogin - the -MustChange param requires check_policy and check_expiration to be enabled

### ISSUE THREAD

**Issue by lancasteradam** [sqlcollaborative/dbatools#7089]
### Report
Set-DbaLogin - the -MustChange param requires check_policy and check_expiration to be enabled

While working on #7004 it was noticed that the -MustChange param requires the policy related params to be set to true. The MS documentation has a mention of this:  https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-login-transact-sql?view=sql-server-ver15#remarks

Suggested code changes for this issue are here:

**Validation**
https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R221

https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R226

**Ensuring the policy params are set and the login object is refreshed**
https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R273

https://github.com/sqlcollaborative/dbatools/pull/7087/files/7127b1c70d9ad43de2d5fa412ab4e9ea485f57f5#diff-419523c18ac6bcaa3c3134c4b1996958ae756dbd7a59abec0193bfb8dc804381R284

#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received
WARNING: [15:31:44][Set-DbaLogin] Something went wrong changing the password for [SQLUser1] | The MUST_CHANGE option cannot be used when CHECK_EXPIRATION is OFF.

![Set-DbaLogin - MustChange param](https://user-images.githubusercontent.com/68036988/104859347-87894580-58d9-11eb-89c6-a108812a2cba.png)

#### Steps to Reproduce
$securePassword = ConvertTo-SecureString -String 'strong password' -AsPlainText -Force
Set-DbaLogin -SqlInstance $server -Login SQLUser1 -MustChange -Password $securePassword

#### Expected Behavior
Set-DbaLogin needs to ensure the must_change is handled correctly. 

Option 1: The command can validate the policy params and ensure check_policy and check_expiration are set to 'on'. A warning message can be returned to the caller describing that it was required to change the policy options.

Option 2: The command can enforce a two-step process. The first step the caller has to enable check_policy and check_expiration explicitly. Then, in the second step they can do the must_change.

#### Actual Behavior
An error is returned as noted above.

### Environmental information
PowerShell Version : 5.1.18362.1171
dbatools latest installed : latest from the development branch
Culture of OS : en-US

SQL Server:
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64) Nov 2 2020 18:35:09 Copyright (C) 2019 Microsoft Corporation Developer Edition (64-bit) on Windows 10 Pro 10.0 (Build 18363: ) (Hypervisor)

us_english

**Comment by wsmelton** [comment]
`if ((Test-Bound MustChange) -and ((Test-Bound PasswordPolicyEnforced -Not) -or (Test-Bound PasswordExpirationEnabled -Not))) {`

The fact that the settings are required to be enabled on the login is fine, but we can't enforce this by requiring them to provide the additional parameters in the same call. They may not know it's required and the password they are setting could not work if the policy is enforced.

```if (Test-Bound MustChange) {
                            Write-Message -Message "Setting check_policy and check_expiration to true for $l because the must_change option requires it." -Level Warning
                            $l.PasswordPolicyEnforced = $PasswordPolicyEnforced
                            $l.PasswordExpirationEnabled = $PasswordExpirationEnabled
                            $l.Alter()
```

In this area we cannot forcefully enable those properties on a login without the user explicitly requesting it. We can provide a more precise message because if both are enabled the only error SQL Server spits out is that one of the two is not enabled:
![image](https://user-images.githubusercontent.com/11204251/104860243-0db08680-58f0-11eb-93d5-0b87517778f0.png)

We can help in that regard if SMO requires them both to be enabled that we check for them to be, and if we find them not then spit out the warning as such and not attempt the change password call.

Something like:

- user submits MustChange
- Validate checks for policy and expiration are enabled on the login
- One or both are found not enabled: spit warning stating which ones are not enabled (Stop-Function with continue)
- continue processing on the next login object

**Comment by lancasteradam** [comment]
ok, thanks, I agree that sounds much better.
