### ISSUE TITLE
Update-DBAInstance doesn't apply security patches

### ISSUE THREAD

**Issue by vieiradaniel92** [sqlcollaborative/dbatools#7111]
Hi, there's been a recent SQL Server security patch provided by MS across most versions of SQL.

When running Update-DBAInstance (version 1.0.137), the local dbatools-buildref-index.json picks up the security patch but Get-SQLInstanceUpdate returns with "Already latest version".

Using SQL Server 2017 as an example. My server is version 13.0.5850, the security patch is newer at version 13.0.5865

Verbose output

VERBOSE: [16:32:39][Get-DbaCmObject] Configuration loaded | Cache disabled: False
VERBOSE: [16:32:39][Get-DbaCmObject] [<ServerName>] Retrieving Management Information
VERBOSE: [16:32:39][Get-DbaCmObject] [<ServerName>] Accessing computer using Cim over DCOM
VERBOSE: [16:32:39][Get-DbaCmObject] [<ServerName>] Accessing computer using Cim over DCOM - Success
VERBOSE: [16:32:39][Resolve-DbaBuild] Looking for 13.0.5850
VERBOSE: [16:32:39][Resolve-DbaBuild] We have 86 builds in store for this Release
WARNING: [16:32:39][Get-SqlInstanceUpdate] 13.0.5850 on computer [<ServerName>] is already the latest available.

Is the only workaround using the -KB param?

**Comment by wsmelton** [comment]
Security patches are not considered updates from the sense of "latest build" therefore we don't flag them as such. Microsoft references them in a similar fashion as being `CUx+GDR` (where x is the latest CU for the release of SQL Server).

Installation of security patches is done using the `-KB` parameter by design.

Reference #7092 discussion as well.
