### ISSUE TITLE
Configuration setting to bypass Initialize-CredSSP

### ISSUE THREAD

**Issue by kozloski** [sqlcollaborative/dbatools#7148]
### Summary of new feature

Create a configuration setting to bypass initialization of CredSSP authentication by `Initialize-CredSSP`.
Allow CredSSP authentication to be used, but only using the existing configuration already in place.

The reason I am proposing this is because CredSSP configuration is managed by Group Policy in my organization, and does not need to be managed by dbatools. If I run `Enable-WSManCredSSP` on my corporate workstation, it results in an access denied error.

I think this would be a reasonable way to allow users who aren't able to manage their own CredSSP settings a way to avoid unnecessary errors, or advanced users who *really* want to manage their own CredSSP settings to avoid configuration munging.

### Proposed technical details (if applicable)

Create new configuration setting something like `commands.initialize-credssp.bypass` : 

```
Set-DbatoolsConfig -FullName 'commands.initialize-credssp.bypass' -Value $false -Initialize -Validation bool -Description "Do not attempt to configure CredSSP authentication, use existing configuration as-is"
```

Then add a conditional in `Initialize-CredSSP`:

```
if ( ( Get-DbatoolsConfigValue -FullName 'commands.initialize-credssp.bypass' ) -eq $true ) {
    Write-Message -Level Verbose -Message "CredSSP initialization bypass (commands.initialize-credssp.bypass) is set to $true";
    return;
}
```
### Latest version of dbatools as of writing

1.0.139

**Comment by nvarscar** [comment]
This could be something more simple, like a switch to the command that would disable the forced CredSSP configuration.
Or even better, the command could actually _test_ CredSSP connectivity before trying to configure it.

**Comment by kozloski** [comment]
I like the test-before-config approach, it has value.
That would probably get me most of what I want.
Coupled with a switch parameter to the calling commands, that would do...

But the idea of being able to disable the function globally and tell dbatools to *never touch this thing* really appeals to me.

Adding parameters (I'm assuming to the functions that call Initialize-CredSSP, like `Install-DbaInstance` and `Update-DbaInstance`), I'd have to then remember which commands will try to initialize CredSSP, and possibly run the risk of the command failing, or my configuration being changed if I forget to supply the switch. Right now it's only two functions but that may change in the future.

This approach seems more complicated to me.

**Comment by wsmelton** [comment]
This needs to be a configuration item that the user explicitly enables, default it to false to never touch CredSSP configuration.

> Allow CredSSP authentication to be used, but only using the existing configuration already in place.

Exactly, many environments strongly control the use of CredSSP since it passes creds in cleartext. We should not modify the configuration of a client or server without the user explicitly allowing it.

**Comment by nvarscar** [comment]
> never touch CredSSP configuration

This would break backwards compatibility and force users to configure CredSSP manually, which is an overhead for a lot of the userbase.

This command was written to ease up those things, and I would not want it to go into the direction where users need to RTFM and perform extra actions before they can use it. Test before configure, allow users to disable CredSSP configuration globally - both can (and probably should) be implemented. But actually forcing users to manually configure CredSSP before using this command is an overreaction.

**Comment by wsmelton** [comment]
> This would break backwards compatibility and force users to configure CredSSP manually, which is an overhead for a lot of the userbase.

What purpose does either command need CredSSP to start with? We are only doing one hop (client to server, or I can almost bet most users including deployments I've done with this are running it locally on the given servers to install). However, I am not aware of any rule we have for maintaining backward support in any command for changes; we have already done this in some commands since the 1.0 release.

> manually configure CredSSP before using this command is an overreaction.

I have not hit an environment yet that required CredSSP with any module (exception of those that utilize PSSnapips still as Idera's does). I help customers in most cases disable 
 CredSSP because of the security risk it causes (which I might add so does Microsoft).

**Comment by nvarscar** [comment]
> What purpose does either command need CredSSP

Double hop to the network share with setup files.

**Comment by wsmelton** [comment]
Utilizing a PSSession config can remove the need for CredSSP just for that purpose. https://4sysops.com/archives/solve-the-powershell-multi-hop-problem-without-using-credssp/

I would consider this method less intrusive than changing trusted host configurations.

**Comment by nvarscar** [comment]
That method is already used as a failback when CredSSP is not functioning. Passing credentials as plain text through an unprotected connection should be a bigger security threat than a CredSSP protocol. Which is why there is a separate Confirm popup when the function is preparing to switch to that method.

**Comment by wsmelton** [comment]
Is-what-it-is then. Having the control at the module level we ensure more control from my use cases and make it something I'd recommend for customers I deal with now.

**Comment by kozloski** [comment]
To make myself clear: I'm not proposing any change to the current/default behavior here. Only a configuration option that I can use to opt-out of the default.
