### ISSUE TITLE
Obfuscate the password in the connectionstring

### ISSUE THREAD

**Issue by thierryvandurme** [sqlcollaborative/dbatools#7182]
### Summary of new feature

Saving connection object in variable displays password when using SQL authentication (only when displaying the variable right after connecting)
$sqlLogin = Get-Credential
$connection = Connect-DbaInstance -SqlCredential $sqlLogin -SqlInstance .... -SqlConnectionOnly
$connection
==> includes password in clear-text

### Proposed technical details (if applicable)

Would it be possible to obfuscate the password?

### Latest version of dbatools as of writing

1.0.137

**Comment by lancasteradam** [comment]
@thierryvandurme, that is expected behavior for SQL auth. After calling $connection.Open() the password will no longer be visible in clear text:

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/protecting-connection-information#use-persist-security-infofalse

https://www.codykonior.com/2018/11/03/smo-leaks-sqlcredential-passwords-in-clear-text/

Have you considered using Windows authentication in your script? This issue is specific to SQL authentication.

**Comment by thierryvandurme** [comment]
@lancasteradam Windows authentication is not an option in my specific case. But thanks for the reply and references!
