### ISSUE TITLE
[Bug] Copy-DBADatabase not continuing

### ISSUE THREAD

**Issue by kjwalker** [sqlcollaborative/dbatools#7195]
#### Host used

- [x] powershell.exe
- [ ] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```

Type     Name	Status	Notes
----	 ----	------	-----
Database DBNAME	Skipped	Already exists on destination.

```
 It is expected to exist as we are "continuing."

#### Steps to Reproduce

`Copy-DbaDatabase -Source OldProd -Destination NewProd -Database DBNAME -UseLastBackup -BackupRestore -NoRecovery`

New diff/tlog backups are taken in-between commands.

`Copy-DbaDatabase -Source OldProd -Destination NewProd -Database DBNAME -UseLastBackup -BackupRestore -NoRecovery -Continue`
	

#### Expected Behavior

Copy-DBADatabase to proceed with additional diff/transaction log restores.

#### Actual Behavior

Throws warning that the databases already exist.  

I suspect it is due to line 1136 in Copy-DbaDatabase:
                    `if (($null -ne $destServer.Databases[$DestinationdbName]) -and !$force -and !$WithReplace) {`
I was able to modify this line to restore the databases as expected:
                    `if (($null -ne $destServer.Databases[$DestinationdbName]) -and !$force -and !$WithReplace -and !$Continue) {`
**Cancel that** - the database it worked on may have been a fluke.  Tried to do others and it's now appearing to skip restoring the diff in an attempt to restore a more recent log backup than can be applied.  

### Environmental information

```powershell
PowerShell Version        : 5.1.18362.1171
dbatools latest installed : 1.0.141
Culture of OS             : en-US
```

#### SQL Server:

```sql
2016 SP2 CU16 Enterprise
```

```sql
us_english
```

**Comment by lancasteradam** [comment]
@kjwalker, I tried the scenario and I think your proposed fix is correct based on how this command is written. The -Continue documentation in [Copy-DbaDatabase](https://docs.dbatools.io/#Copy-DbaDatabase) says that it only does transaction log restores. Feel free to create a pull request with that fix.

In order to do the diff restoration you could use the Backup-DbaDatabase | Restore-DbaDatabase as mentioned in the description of [Copy-DbaDatabase](https://docs.dbatools.io/#Copy-DbaDatabase).
