### ISSUE TITLE
schemazen as a library

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbatools#728]
Adding "figure out building [schemazen](https://github.com/sethreno/schemazen/tree/master/model/Models) as a library in a reproducible manner" to @ConstantineK's todo 👍

**Comment by ConstantineK** [comment]
Did some further digging (because I love https://github.com/sethreno/schemazen) and it looks like there are a few show stopper bugs which has me a little uncomfortable adding it to dbatools at this point (non-default collations, rowguids, and a few minor things around how it handles various features.)

The project is really good and with a few additional fixes I think it would be dbatools ready. I have started submitting pull requests to the project, the maintainer seems like cool.

If possible I would like to keep this open as a reminder and goad to keep fixing issues in that project.

**Comment by ctrlbold** [comment]
awesome, thanks, ck! 💪

**Comment by wsmelton** [comment]
Closing this issue out as I'm not sure it is still on the ballet to be added to dbatools. As well I would state that the schemazen repo is abandoned considering it has had no changes in almost 3 years.

**Comment by wsmelton** [comment]
If it needs to be reopened by all means.
