### ISSUE TITLE
Migrate between workgroup servers

### ISSUE THREAD

**Issue by Sader82** [sqlcollaborative/dbatools#731]
### Is this a *feature* OR *bug*:

Feature

### System Details

- Operating system name and version: Windows 2003 R2

- Output of dbatools version:
0.8.1.6

- SQL Server version for source/target
Source SQL2005
Destination SQL 2014 of 2016

### Steps to Reproduce

Old server winth windows 2003 and SQL 2005, try to migratie to new server in workgroup

### Action Results

cmdlets are missing the -credentials switch for external windows credentials

### Expected Results

migratie of copy things between servers that are not in a domain

### Attached Logs or any exception errors

I'm not able to copy the error.....

The error is: "Connecting to remote server XXXXXX failed with the following error message: access is denied."
Windows eventlog shows the wrong credentials is the security log

**Comment by wsmelton** [comment]
@Sader82 the commands for migration include credential parameters where you can provide another login. You do not provide the command you tried but `Start-SqlMigration` includes two parameters to provide `SourceSqlCredential` and `DestinationSqlCredential`.

These would only be passing in the SQL Server credentials. If I recall, in order to connect between two servers in a workgroup environment the login you start the process under on the destination (_because PS3.0 and above is not supported on Window Server 2003 R2_) exist on both workgroup  machines with the same password it should let you authenticate.

However, I'm not sure that is needed because you can just as easily use a SQL Login. Which to use that you would call the command using the associated "SqlCredential" parameter.

**Comment by Sader82** [comment]
@wsmelton I think your right. The only problem is that I cannot test it because my colleague has taken over the migration for that server... :-(

**Comment by potatoqualitee** [comment]
This can now be handled using Backup-DbaDatbase, Copy-Item with a PSDrive then Restore-DbaDatabase. @Stuart-Moore would you be interested in making a blog post to describe this or should I make it an Issue and ask someone else?
