### ISSUE TITLE
[Bug] - Rename-DbaLogin won't rename logins not mapped inside a db

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbatools#7363]
#### Host used

- [X] powershell.exe
- [ ] ISE
- [X] VS Code
- [ ] Other (please specify)

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: You cannot call a method on a null-valued expression. 
                        ---> System.Management.Automation.RuntimeException: You cannot call a 
                        method on a null-valued expression.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreferenc
                        e(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(I
                        nterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstructi
                        on.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstructi
                        on.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          : newlogin
CategoryInfo          : InvalidOperation: (hooray:String) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Rename-DbaLogin,Stop-Function
ErrorDetails          : You cannot call a method on a null-valued expression.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.149\allcommands.ps1: line 88702
                        at Rename-DbaLogin<Process>, C:\Program 
                        Files\WindowsPowerShell\Modules\dbatools\1.0.149\allcommands.ps1: line 63732
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

#### Steps to Reproduce
Rename_DbaLogin -SQLInstance dbatools2 -Login sa -NewLogin newlogin

#### Expected Behavior
sa account to be renamed successfully without the need to remapped logins in the databases.

#### Actual Behavior
Failure because it tries to remap the users in the db but find no users in the db

### Environmental information

🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
Please provide the output of the below script

```powershell
[pscustomobject]@{
'PowerShell Version' = $PSVersionTable.PSVersion.ToString()
'dbatools latest installed' = (Get-InstalledModule -Name dbatools).Version
'Culture of OS' = (Get-Culture)
} | fl -force
```
PowerShell Version        : 5.1.17763.1852
dbatools latest installed : 1.0.149
Culture of OS             : en-US

#### SQL Server:
Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)   Mar 22 2021 18:10:24   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

us_english

**Comment by tboggiano** [comment]
You can use Set-DbaLogin and it work, but it seems this should work on both commands, I could be wrong though.

**Comment by andreasjordan** [comment]
This is not so easy - there are more issues with this command.

The reason the command is failing is a "bug" in line 125: `$user = $db.Users[$Login]`

So `$user` is only set, if the user in the database has the same name as the login in the instance. This is the case in most situations, so this was not reported earlier.
Because of the empty `$user` the use of `$user.Rename($NewLogin)` in line 131 fails.

In your case, while renaming the sa, there is no user named sa in the database. To really renaming the mapped user, we would need to use `.UserName` from the $dbenums. Sidenote: The variablename `$db` in line 123 is incorrect, as it is not a database but a mapping (Type: Microsoft.SqlServer.Management.Smo.DatabaseMapping), so `$map` or somthing like that would be correct.

In your case, the login "sa" is mapped to the user "dbo" in all of the system databases - I don't think you want them to be renamed to "sa" (would be impossible hopefully - have not tested that).

So the question is: What should the command do? Rename all mapped users (that are not .IsSystemObject) to the new name of the login? Or just rename mapped users (that are not .IsSystemObject) with the same name as the login to the new name of the login?

@potatoqualitee / @wsmelton : As soon as we have a decision, I can code a fix.

**Comment by wsmelton** [comment]
The command scope is for the Login rename only, there is no reason to touch the User databases because a rename does not change the SID for a SQL Login. Renaming a Windows Login requires the name provided has to be the SID that it matches in AD, which not sure if this has any effect on the users in the database or not.

![image](https://user-images.githubusercontent.com/11204251/121887804-d0a0c280-ccdc-11eb-83ff-d8d288f93173.png)

**Comment by andreasjordan** [comment]
But documentation says:
"Rename-DbaLogin will rename login and database mapping for a specified login. There are times where you might want to rename a login that was copied down, or if the name is not descriptive for what it does.It can be a pain to update all of the mappings for a specific user, this does it for you."

So update the documentation and the code to not touch users anymore?

**Comment by andreasjordan** [comment]
@potatoqualitee Can you have a look at this?

**Comment by potatoqualitee** [comment]
submitted a PR!
