### ISSUE TITLE
Connect-DbaInstance - Introduce a new property FullComputerName

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7427]
I like to have a short ComputerName as the typical first output property of dbatools commands. But on the other side, some of our commands need a full qualified name to use it in UNC paths or while connecting to a computer.

Therefor I would like to have a new property FullComputerName with a similar setup like ComputerName in #7426.

To achieve this, I propose the following code:

```
if (-not $server.FullComputerName) {
	# To set the source of FullComputerName to something else than the default use this config parameter:
	# Set-DbatoolsConfig -FullName commands.connect-dbainstance.smo.fullcomputername.source -Value 'server.ComputerName'
	# Set-DbatoolsConfig -FullName commands.connect-dbainstance.smo.fullcomputername.source -Value 'resolve.FullComputerName'
	# If the config parameter is not used, then the ComputerName of the input object is used.
	$fullComputerName = $null
	$fullComputerNameSource = Get-DbatoolsConfigValue -FullName commands.connect-dbainstance.smo.fullcomputername.source
	if ($fullComputerNameSource) {
		Write-Message -Level Debug -Message "Setting FullComputerName based on $fullComputerNameSource"
		$object, $property = $fullComputerNameSource -split '\.'
		if ($object -eq 'resolve') {
			$value = $null
			try {
				Write-Message -Level Debug -Message "Trying to use Resolve-DbaNetworkName"
				$value = (Resolve-DbaNetworkName -ComputerName $instance.ComputerName -EnableException).$property
			} catch {
				Write-Message -Level Debug -Message "Failed to use Resolve-DbaNetworkName"
			}
		} else {
			$value = (Get-Variable -Name $object).Value.$property
		}
		if ($value) {
			$fullComputerName = $value
			Write-Message -Level Debug -Message "FullComputerName will be set to $fullComputerName"
		} else {
			Write-Message -Level Debug -Message "No value found for FullComputerName, so will use the default"
		}
	}
	if (-not $fullComputerName) {
		$fullComputerName = $instance.ComputerName
		Write-Message -Level Debug -Message "FullComputerName will be set to $fullComputerName"
	}
	Add-Member -InputObject $server -NotePropertyName FullComputerName -NotePropertyValue $fullComputerName -Force
}
```

I would then change all the commands that use Resolve-DbaNetworkName to first test `$server.FullComputerName -ne $server.ComputerName` (or `$server.FullComputerName.Length -gt $server.ComputerName.Length`) and in that case assume that FullComputerName is a suitable value to connect to the computer or to be used in an UNC path.

I know that the use of "Resolve-DbaNetworkName" inside of Connect-DbaInstance only works if the current account has the necessary rights because we don't have a -Credential parameter, but that's fine. In other cases the user can first build `$server` and then in the next line use `$server.FullComputerName = Resolve-DbaNetworkName -ComputerName $server.ComputerName -Credential $cred`.

**Comment by andreasjordan** [comment]
This might also help working on #5988.

**Comment by potatoqualitee** [comment]
The resolve command can be slow as heck (best case, 550ms, worst case 15 seconds), so this should not be a default unless it uses `-Turbo`. Best case, Turbo adds 136ms.

**Comment by niphlod** [comment]
yah, it needs to be done only if strictly needed, i.e. needing to interact with the underlying server and not when playing with sql only. Turbo reports wrong data in some cases, so I won't add it by default

**Comment by potatoqualitee** [comment]
So true! I forgot your network resolves it wrong.

**Comment by andreasjordan** [comment]
I can remove the ability to use Resolve-DbaNetworkName - just wanted to show what can be possible.

**Comment by niphlod** [comment]
it if was laaaaazy instead, like it gets resolved only if you explicitely call up FullComputerName as a prop, then it may be a good thing.

**Comment by andreasjordan** [comment]
Do you know how to code a lazy property? We can not change the original class, but only add properties. But I just really wanted it for special situations and thus hide it behind a config. But if a user has an issue related to that we can ask to activate this config and test without shipping new code.

**Comment by niphlod** [comment]
recap for everybody:
the thing is, design-wise, a SQL instance doesn't know anything about the fqdn of the server it is running on. 
resolving it is expensive.
commands needing to interact with the underlying server should use always resolve-dba... because there's no other way around it.
skilled developers complained about the expensiveness of resolve-dba.. when not needed (i.e. they're sure netbios addressing works for them because they don't have disjoint domains or AD forests, and their "client" has default dns prefixes that work always in the best direction). 
So -Turbo was invented, and I think it is settable somewhere globally (again, was  created only for skilled developers).

Right now (if the whole rewrite was completed), resolve-dba.. should be **only** used for whatever function needs to interact with the underlying server, being passed a sql instance (those accepting ComputerName don't need it).

If we wanna "forget" the deal of having coders to remember that any time they wanna switch from sqlinstance to underlying server they have to use resolve-dba... and wanna put a FullComputerName prop on the instance itself, that spends time only when FullComputerName is "called", and refactor all code using resolve-dba.. to use that property, all is good in the world.

But doing it in (possibily) two places is IMHO wrong. e.g. if I do a Get-DbaLogin I absolutely don't need anything about the computer running the instance.
I kinda like the fact that we're "costantly" remembered that a SqlInstance is a very different thing from a ComputerName, but seeing the bugs pop up here and there, YMMV.
Unfortunately there's no way to have it correct and fast whenever you connect to a SqlInstance, and that remains a fact we can't do anything about.

**Comment by niphlod** [comment]
and just for fun, this snippet works for lazy properties https://gist.github.com/jstangroome/3522474 . not sure if PS3 can do it.

**Comment by andreasjordan** [comment]
So: What's the solution we can all agree on?
I don't need the `if ($object -eq 'resolve') { ... }` part, but I would like to have the FullComputerName property and I would like to change all commands that do `Resolve-DbaNetworkName` to first check if FullComputerName is larger that ComputerName and in that case just use FullComputerName.
Two pros:
* Speed up commands that do not need to run `Resolve-DbaNetworkName` in every case. Currently the result is only used once and is not saved.
* Be more flexible in what the commands use to connect to the computer.

Sample code:
```
$source = Connect-DbaInstance -SqlInstance SRV1\SQL2017
$source.FullComputerName = (Resolve-DbaNetworkName -ComputerName $source).FullComputerName
Copy-DbaDatabase -Source $source -Destination SRV2\SQL2017 -Database test01 -DetachAttach -Reattach -Verbose
```

**Comment by potatoqualitee** [comment]
Just tested @niphlod's code and it works in PS3 👍🏼

**Comment by niphlod** [comment]
@andreasjordan : on the "cache that" argument: clustered instances may disagree with you. Aliased ones too. Does it happen regularly ? no. Does it happen, sometimes ? yes.

I agree Resolve-Dba.. is slow, but please remember that a 2sec slowdown on resolve-dba.. on a Copy-DbaDatabase taking 30 sec to run a backup/restore or to detach/move/attach is negligible rather than popping out an error if you cached the computername and the instance failed in-between.

I don't necessary see the pro of having if on the $instance object (keeping in mind that Computers and Instances are two wildly different things is good from a code perspective), but if we wanna go down that path it still needs to be computed right before using its output to do whatever is needed to access the underlying server, every time.

**Comment by andreasjordan** [comment]
@niphlod You have very good points. So yes, caching is no good. And yes, the time is not the point. I had a look at the commands that use Resolve-* and I think it's totally ok there.

Will think about it one more night and potentially close it. Thanks for the feedback.

Maybe it's better to address the special cases inside of Resolve-DbaNetworkName with a lookup hashtable in the configuration to say: If `.ComputerName` is a key in the hashtable then do not resolve but return the object from the hashtable.
