### ISSUE TITLE
[Bug] DbaDateTime error via Get-DbaRunningJob

### ISSUE THREAD

**Issue by SQLGB** [sqlcollaborative/dbatools#7530]
#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

#### Errors Received

```
PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Cannot convert the "System.Object[]" value of type "System.Object[]" to type 
                        "Sqlcollaborative.Dbatools.Utility.DbaDateTime". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "System.Object[]" value of type 
                        "System.Object[]" to type "Sqlcollaborative.Dbatools.Utility.DbaDateTime".
                           at System.Management.Automation.LanguagePrimitives.ThrowInvalidCastException(Object valueToConvert, Type resultType)
                           at System.Management.Automation.LanguagePrimitives.ConvertNoConversion(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, 
                        IFormatProvider formatProvider, TypeTable backupTable)
                           at CallSite.Target(Closure , CallSite , Object )
                           at Get-DbaAgentJob<Process>(Closure , FunctionContext )
                           --- End of inner exception stack trace ---
TargetObject          : 
CategoryInfo          : InvalidArgument: (:) [], RuntimeException
FullyQualifiedErrorId : ConvertToFinalInvalidCastException
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaAgentJob<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.171\allcommands.ps1: line 19527
                        at Get-DbaRunningJob<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.171\allcommands.ps1: line 35282
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

#### Steps to Reproduce
Run Get-DbaRunningJob against any server with jobs which are running.

#### Expected Behavior
Output with no errors.

#### Actual Behavior
Output with errors.

#### PowerShell:
```PowerShell Version        : 5.1.14409.1005
dbatools latest installed : 1.0.171
Culture of OS             : en-US
```

#### SQL Server:

```sql
Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64)   Jan 25 2021 20:16:12   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 
```

```sql
us_english
```

**Comment by potatoqualitee** [comment]
I cannot repro. Can you close all of your PowerShell sessions and try again and let us know if it continues? And if so, also, can you paste how you're running the command with your server names redacted?

merci

**Comment by SQLGB** [comment]
I'm doing some additional testing to see if I can find a commonality between servers in my environment where the error occurs; it seems to happen on some but not all.  I'll share what I find.

**Comment by SQLGB** [comment]
I see the issue on 19 of 122 instances in my environment, but haven't yet found what those 19 instances have in common.  I did learn that it doesn't matter if any jobs are running at the time you run the command.  As far as running the command goes, it's just 
````Get-DbaRunningJob -SqlInstance MySqlInstance````

**Comment by potatoqualitee** [comment]
interesting!  🤔  i'll ping @wsmelton to see if he has ideas

**Comment by wsmelton** [comment]
> Cannot convert the "System.Object[]" value of type "System.Object[]" to type

This error would indicate that the query returns multiple job IDs, which when I tested was not happening since a job in SQL Agent can only run one instance of itself at a time. So how that is happening on the 19 servers is intriguing and what would need to be researched (comparing between a good one and one of those 19).

I had it get the job results for all jobs at once to prevent executing a query constantly against a server in a foreach loop.

https://github.com/sqlcollaborative/dbatools/blob/1af3b16dd1d507d26e00a54bb7c7570e38eb87b7/functions/Get-DbaAgentJob.ps1#L120-L130

When we prep the output I do a check for the job ID to see if it first exists in the dataset:

https://github.com/sqlcollaborative/dbatools/blob/1af3b16dd1d507d26e00a54bb7c7570e38eb87b7/functions/Get-DbaAgentJob.ps1#L154-L159

If it does then I pull that job:

```
[DbaDateTime]($jobExecutionResults | Where-Object JobId -eq $currentJobId).StartDate
```

The error would indicate this is returning multiple of the same `job_id`, which is where it should not happen. If we want to address it the adjustment would be to change the line above (156) to sort descending on the execution date and then get the first one in the result. The downside to this is it may cause an inconsistency in results on each run with a long running job (if you have it showing up multiple times).

One thing comes to mind is verify on those 19 servers the output of the query provided and see if they are jobs that hit some issue that caused them to not stop properly. I don't know if either of those msdb views could have a job not cleared or updated properly for some reason. To really research this one we would need to know how the configurations differ between those 19 to a good ones (build number, culture, etc.).

**Comment by potatoqualitee** [comment]
Worst case, we just do a `| Select -First 1`

**Comment by SQLGB** [comment]
I will check some of these things and update soon.  I forgot to mention earlier that this behavior is a recent change in my environment; prior releases of dbatools did not do this.

**Comment by SQLGB** [comment]
I ran Shawn's T-SQL query on a number of instances.  When run against any of the 19 affected servers, yes, there are duplicate records with the same JobId.  The duplicate JobId's have different StartDate values from one another or have a StartDate of NULL.  This does not seem to occur on the other servers.

**Comment by SQLGB** [comment]
The issue does not occur in versions of dbatools prior to 1.0.171.  I downgraded one of my installations to 1.0.170 and it does not occur with that version.

**Comment by potatoqualitee** [comment]
ohh i love the new release system. we can see exactly what was changed between the two https://github.com/sqlcollaborative/dbatools/releases/tag/v1.0.171

**Comment by wsmelton** [comment]
Do easy fix seems to be adjust filter in the loop to include excluding where start execution is null.

Can add that this afternoon
