### ISSUE TITLE
TEPP ([Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache) not updated

### ISSUE THREAD

**Issue by andreasjordan** [sqlcollaborative/dbatools#7618]
### Verified issue does not already exist?

Yes

### What error did you receive?

After initial fill of cache, there seems to be no more updates.

### Steps to Reproduce

```powershell
Import-Module dbatools

# Cache is empty:
[Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache.database

# Do not execute, only TAB complete after -Database to fill and display cache
Get-DbaDatabase -SqlInstance srv1 -Database 

# Cache is filled with 7 databases:
[Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache.database.srv1.Count

# Create new database
$null = New-DbaDatabase -SqlInstance srv1 -Name Test123

# Cache is still filled with 7 databases:
[Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache.database.srv1.Count

# Here I would like to see 8 databases, including the newly created.
# So does the cache gets updated after 3 minutes?

Start-Sleep -Seconds 180

# Cache is still filled with 7 databases:
[Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache.database.srv1.Count

# An extra minute?
Start-Sleep -Seconds 60

# Cache is still filled with 7 databases:
[Sqlcollaborative.Dbatools.TabExpansion.TabExpansionHost]::Cache.database.srv1.Count

```

### Are you running the latest release?

Yes

### Other details or mentions

After we know why the cache is not updated, we should also find a way to update part of the cache:
* Updating database after New-DbaDatabase or Restore-DbaDatabase
* Updating job after New-DbaAgentJob
* ...

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Current.

### SQL Server Edition and Build number

Not relevant.

**Comment by potatoqualitee** [comment]
I recall that i asked for caching not to occur because the way we'd implement it is that it would reach back to the server and people were not really happy that we were polling. The best we could offer is to re-poll in commands that change things but that will slow things down for tabbing that people may or may not use. Or perhaps we can set up a config that's the caching temperament like Aggressive (if we haven't already)

**Comment by potatoqualitee** [comment]
Listing as not a bug because it's as designed.

**Comment by andreasjordan** [comment]
I opened a draft PR to show an idea that works.

**Comment by potatoqualitee** [comment]
I dig! No extra calls back to the db as an added bonus!

**Comment by potatoqualitee** [comment]
You may want to consider making it a function with the cache name plus the new value, so it'll be easier to call over and over

**Comment by andreasjordan** [comment]
Yes, an internal function would be best. I first wanted to see if this is a way we want to go.
It would be needed in the main New- commands and maybe also in the Remove- commands. 
Plus Restore-DbaDatabase.

**Comment by andreasjordan** [comment]
Created Add-TeppCacheItem and used it in:
* Invoke-DbaAdvancedRestore
* New-DbaAgentJob
* New-DbaAgentSchedule
* New-DbaAvailabilityGroup
* New-DbaDatabase
* New-DbaLogin

Next step is to create Remove-TeppCacheItem and use it in the Remove- commands.

Feeback about naming of command and parameters is welcome.

**Comment by andreasjordan** [comment]
Ok, Remove- is added...

**Comment by potatoqualitee** [comment]
Nice! What do you think about `Update` instead of `Add`?

**Comment by andreasjordan** [comment]
The cache as a whole is updated, but the individual item is added. So I used `Add` and `Remove`.

I would use `Update` if we just pass in `$server` and `Type` and all the items are fetched from the Server SMO.

**Comment by wsmelton** [comment]
This is a big no-no unless the user has the ability to not allow this to happen. Users that have large environments or flat out don't even care about the cache are going to take a hit on the performance of this command now because we are updating a cache for a server that could have hundreds of databases on it.

A user can also disable TEPP using TabExpansion.Disable but if this internal command does not acknowledge it and still performs the work it defeats the purpose of the user control.

**Comment by potatoqualitee** [comment]
He doesn't do call backs -- he adds and removes single strings. I dig it.
