### ISSUE TITLE
Invoke-DbaQuery: Disallow specifying Database as $null

### ISSUE THREAD

**Issue by krokofant** [sqlcollaborative/dbatools#7719]
### Verified issue does not already exist?

Yes

### What error did you receive?

I got a misleading error because my input to the command (-Database $foo) is missing.
```powershell
Error connecting to [localhost]: Cannot change the owner of the master, model, tempdb or distribution database.
```

I was trying to connect to another database which was actually not defined correctly.

### Steps to Reproduce

```powershell
$null -eq $foo # True
Invoke-DbaQuery -SqlInstance localhost -Database $foo -Query "dbo.sp_changedbowner @loginame = N'sa', @map = false" -EnableException
```

### Are you running the latest release?

Yes

### Other details or mentions

Is it reasonable to add a check to disallow explicit $null input for -Database? Or should I just write more fool proof code on my end? 😅

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64)
Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19042: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Hey @krokofant - thank you for the issue! I'm leaning to keeping it as is. I know in my own workflows, there are times that I may bind a null database value because otherwise, I'd have to do

`If ($Database) { Invoke-DbaQuery -Database $database } else { Invoke-DbaQuery }`

This would also be a bit of a breaking change, as it'd have the potential to break if people expect to be able to bind to null. In addition, most or all of our database-related commands have the same behavior, so it'd be a deviation from the standard. I'm open to feedback from the designer @niphlod but for now, I would indeed suggest testing for the value prior to running the query.

**Comment by krokofant** [comment]
@potatoqualitee Thanks for the response. What you say seems reasonable and too much work for too little gain. 🙂
