### ISSUE TITLE
Get-DbaDatabase - No*Backup* Params Output Db If Mismatched Case In T-SQL Command

### ISSUE THREAD

**Issue by mattcargile** [sqlcollaborative/dbatools#7935]
### Verified issue does not already exist?

Yes

### What error did you receive?

Error wasn't received. Database with a backup was output when when the `-No*Backup*` params are used. I _think_ this occurs due to the below two lines, namely the `-cnotin` code. The `msdb.dbo.backupset.database_name` respects the case used in the T-SQL command.

https://github.com/sqlcollaborative/dbatools/blob/1dfc259c25968d617722ae040018fce5a3fada4b/functions/Get-DbaDatabase.ps1#L317

https://github.com/sqlcollaborative/dbatools/blob/1dfc259c25968d617722ae040018fce5a3fada4b/functions/Get-DbaDatabase.ps1#L324

### Steps to Reproduce

```powershell
New-DbaDatabase -SqlInstance localhost -Database TSQLCASETEST
Invoke-DbaQuery -SqlInstance localhost -Query "BACKUP DATABASE tsqlcasetest TO DISK = '$HOME\tsqlcasetest.bak'"
Get-DbaDatabase -SqlInstance localhost -NoFullBackup
```

### Are you running the latest release?

Yes

### Other details or mentions

Not really sure how to handle. It seems like there isn't a perfect solution without getting the case sensitivity of every database, maybe? That would seem like it would get really messy.

In my own environment, my solution was to change the code on the one server that didn't use the correct casing.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)
        Mar 13 2020 14:53:45
        Copyright (C) 2017 Microsoft Corporation
        Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```
```sql
Microsoft SQL Server 2008 (SP2) - 10.0.4064.0 (X64)
        Feb 25 2011 13:56:11
        Copyright (c) 1988-2008 Microsoft Corporation
        Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

### .NET Framework Version

```powershell
.NET 5.0.11
```

**Comment by chightow** [comment]
fix is straight forward.  SQL doesn't allow two databases with the exact same characters to be on the same server i.e. [Test] and [TEST]. but [Test] and [ Test] can. 

Not sure why cnotin was used, it doesn't need to be case sensitive. and Get-DBABackupHistory explodes when you've got a databses with the same name, but one has a leading space anyways so it would blow up differently. 

$array = @(" hello")
"hello" -in $array
returns false

so it's not needed even for that edge case. 

$inputObject = $inputObject | Where-Object { $_.Name -notin $lastFullBackups.Database -and $_.Name -ne 'tempdb' }

I'll make the change and put in a pull request.

**Comment by wsmelton** [comment]
If you are in an instance with case sensitive collation you can have a database with the same name but different casing.  That is why we use a case sensitive comparison operator in PowerShell.

**Comment by chightow** [comment]
[get-DbaSqlInstanceCollationStringCompareTools.txt](https://github.com/sqlcollaborative/dbatools/files/7546742/get-DbaSqlInstanceCollationStringCompareTools.txt)

@wsmelton 
that's Not any more Accurate than using in. 

Would this be helpful, since it gives you an accurate string comparison for any given Collation

**Comment by wsmelton** [comment]
I'm not referring to comparing an array to a single value. I'm only talking about case-sensitive comparison. In that there is a significant difference between using `-notin` vs `-cnotin`. By default PowerShell comparison operators `in`, `eq`, etc are all non-case comparisons. When you using any of them prefixed with `c` then it turns it to do a case-sensitive comparison. So there is a strong difference between using `-notin` vs `-cnotin`.

![image](https://user-images.githubusercontent.com/11204251/142000071-4ae67467-2cbd-4da1-98e9-0a792ff5964f.png)

If I have a SQL Server instance with case-sensitive collation I can create the 3 databases in this example without errors. Have you tested the change in your PR against an instance of SQL Server that defaults to use a case-sensitive collation?

**Comment by chightow** [comment]
PR  andreas approved uses collation Check, to decide whether or not to do -cin  or -in  

it's still wrong though. 

waiting for it to be merged or for them to tell me to do it the way that handles all collations correctly.

Prior to pull it handled CS_WS_AS  Correctly only Maybe the KS ones too , but I don't have any of those. 

as currently approved  handles CI_WS_AS, CS_WS_AS correctly

But it's still wrong
Doesn't do anything for AI,WI

and most instance collations used are probably WI

that's why I asked if we should just use the String Compare SMO gives us for any collation we want. that way it's always right and you don't have to write a bunch of if else stuff 


so this bit doesn't grow to be like 1k lines long trying to replicate string comparisons that SMO gives us for free

"""
 if ( $server.Collation -like "*_CS*" -or $server.Collation -like "*_BIN*"  ) {
                    # Collation Check, when Case Sensitive collation use cnotin for database name comparision
                    $inputObject = $inputObject | Where-Object { $_.Name -cnotin $lastFullBackups.Database -and $_.Name -ne 'tempdb' }
                } else {
                    $inputObject = $inputObject | Where-Object { $_.Name -notin $lastFullBackups.Database -and $_.Name -ne 'tempdb' }
                }

""

it would instead be 
"""
$x = get-DbaSqlInstanceCollationStringCompareTools $server

 $inputObject = $inputObject | Where-Object { $x.notin( $_.Name,$lastFullBackups.Database) -and $_.Name -ne 'tempdb' }
"""

and that handles any collation the instance has correctly

**Comment by wsmelton** [comment]
If it is still wrong why are you not submitting a PR to completely fix it?

**Comment by chightow** [comment]
well I've never submitted a new Module Is what I have fine?

**Comment by wsmelton** [comment]
```
get-DbaSqlInstanceCollationStringCompareTools
$inputObject = $inputObject | Where-Object { $x.notin( $_.Name,$lastFullBackups.Database) -and $_.Name -ne 'tempdb' 
```

The above, looking at your text file, is excessive and won't scale with large environments.

**Comment by chightow** [comment]
is it the in function or equals, or that they're Methods on a PscustomObject? 
Or just that the names terrible?

Function

**Comment by wsmelton** [comment]
The problem with using SMO's `StringComparer` is that depends on `Microsoft.SqlServer.Management.SqlParser` I believe which was not ported to dotnet core. So not sure if using that will end up getting different results based on culture and dotnet version running on a given machine.

I'm also not fond of using collation checks // @potatoqualitee @andreasjordan // because those are going to give different results for any given server and possibly in Azure SQL too (if they limit the collations you can use compared to on-premises). 

What is the issue with using PowerShell native string comparison again?

**Comment by wsmelton** [comment]
The function you have @chightow is performant in it is creating a new object based on the input. `Get-DbaDatabase` is already a function that has performance issues natively from SMO enumeration. I think newer versions of SMO they are improving this but there are some environments I've touched it just can't be used.

If you have an internal function that has to iterate over each input and then use a script method on that object it is a performance hit from PowerShell side. Array comparison in PowerShell is more efficient as-is.

**Comment by andreasjordan** [comment]
My point of view:
On case insensitive instances (should be most cases) users can run the backup command with different case for the same database, so data in msdb has different (case) values for the same database. So comparing should be case insensitive too.
On case sensitive instances (probably edge case) users might be creating two databases with the "same" name - or don't they? (Don't have a case sensitive instance today) so we should compare case sensitive as well. That was my idea when I used "-cin" in my last change some months ago.
The current change should work for both cases.

**Comment by chightow** [comment]
@wsmelton  I'll check, I think it's in .net core got to start up wsl.

**Comment by wsmelton** [comment]
The library we depend upon for SMO is packaged with the module. You can find them in the bin\smo directory.

**Comment by mattcargile** [comment]
I was playing with `Get-StringComparer()` in `pwsh` and it was working. I've got `.NET 6.0.0`.

**Comment by chightow** [comment]
@wsmelton 

So basically this is the reason 

"""
create table #Collations
( [name] varchar(255), [ceq works] bit, [eq works] bit, [neither work] bit default 0  )

insert into #Collations
( [name], [ceq works], [eq works] )
SELECT name, case when name like '%_BIN%'
or (name like '%_CS%' and name like '%_AS%' and name like '%_KS%' and name like '%_WS%') then 1 else 0 end as [ceq works], 
case when name like '%_CI%' and name like '%_AS%' and name like '%_KS%' and name like '%_WS%' then 1 else 0 end as [eq works]
FROM sys.fn_helpcollations()

update #Collations
set [neither work] = 1
where [ceq works] = 0
and [eq works] = 0

Declare @CollationCount float = ( select count(1) from #Collations )
declare @Ceq float,
		@eq float,
		@neither float

select @ceq = count(1) / @CollationCount  from #Collations where [ceq works] = 1
select @eq = count(1) / @CollationCount  from #Collations where [eq works] = 1
select @neither = count(1) / @CollationCount  from #Collations where [neither work] = 1

select @ceq*100 as [ceq works percentage], @eq*100 as [eq works percentage], @neither*100 as [neither works percentage]
"""

even with collation check we're leaving ~80% of possible collations returning incorrect results at least on windows hosting sql 2019

**Comment by chightow** [comment]
Don't think I even need a real instance for it to work 

would this be better? 

Function Get-DbaCollationEquals
{
	param( [string]$Collation, [string]$String1, [string]$string2,[Microsoft.SqlServer.Management.Smo.Server]$SqlInstance )
	if ( -not $SqlInstance ) {
		$SqlInstance = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server
	}
	return $SqlInstance.getStringComparer($Collation).Compare($string1, $string2) -eq 0
}
Function Get-DbaCollationNotEquals
{
	param( [string]$Collation, [string]$String1, [string]$string2 )
	return -not (Get-DbaCollationEquals -Collation $Collation -String1 $string1 -string2 $String2)
}
Function Get-DbaCollationIN
{
	param( [string]$Collation, [string]$String, [string]$array )
	$SqlInstance = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server
	 foreach ( $x in $array ) {
		 
            if (Get-DbaCollationEquals -SqlInstance $SqlInstance -Collation $Collation -String1 $string1 -string2 $x) {
                return $true
            }
        }
        return $false
}
Function Get-DbaCollationNotIN
{
	param( [string]$Collation, [string]$String, [string]$array )
	return -not (Get-DbaCollationIN -Collation $Collation -String $String -array $array )
}
example: 

$Collation = 'SQL_Latin1_General_CP1_CI_AI'
Get-DbaCollationEquals -Collation $Collation -String1 'a' -string2 'Á'
	true

'a' -eq 'Á'
false

'a' -ceq 'Á'
false

**Comment by wsmelton** [comment]
We are trying to solve something that is a non-issue here. Just revert the comparison operator back to `-notin` and we fix this issue. Collation is irrelevant for this direct issue because the comparison is being done in PowerShell, **not** in SQL Server.

We have no reason to try and perform string comparisons based on collation in SQL Server when the data is being compared within PowerShell's processing.

Summary of points:

- If we are using PowerShell comparison operators the collation of SQL Server is irrelevant.
- SMO class `Server.Databases` will return a list of database names, irrelevant of the collation.
- Users that rename a database and then try to get the last backup date are on their own; nothing we can do about bad data in their backup history.
- We are calling `Get-DbaDbBackupHistory` which is running a T-SQL statement to pull the data. We don't control what casing that data comes out as so whether you have `Test`, `TEST`, or `TEst` use of `-notin` will cover it. 
- We cannot be expected to compare `Test` with `Test ` (or `Test It` with `TestIt`), that is a data issue that the user will have to address or account for by use of other command(s) to get the last backup date.

**Comment by mattcargile** [comment]
So then the case of having two databases where one is named `Test` and one is `TEST` on a CS Collation wouldn't be covered? I would assume this situation is mostly impractical in a production instance.



> Don't think I even need a real instance for it to work
> 
> would this be better?
> 
> ```
> Function Get-DbaCollationEquals
> ...
> ```

To your point @chightow, I would assume you wouldn't derive the functions and use the already derived `$server` object in the function `Get-DbaDatabase`.

**Comment by chightow** [comment]
@mattcargile  
Just depends on what you want to work 

-in  is faster than Get-DbaCollationIn by about 130ms on comparing an array with 32767k elements

`
$start = [long] 1
$end = [long] 32767
$number = @()

while ($start -lt $end){
	$Number = $number + @('1')
	$start = $start + 1
}
Measure-Command { '0' -in $number }
measure-command { Get-DbaCollationIN '0' -in $number }
` 
probably can make it go faster, but it'll be more confusing to read.

**Comment by mattcargile** [comment]
> @mattcargile Just depends on what you want to work
> 
> -in is faster than Get-DbaCollationIn by about 130ms on comparing an array with 32767k elements
> 
> ` $start = [long] 1 $end = [long] 32767 $number = @()
> 
> while ($start -lt $end){ $Number = $number + @('1') $start = $start + 1 } Measure-Command { '0' -in $number } measure-command { Get-DbaCollationIN '0' -in $number } ` probably can make it go faster, but it'll be more confusing to read.

I think we are missing each other. I'm just talking about how to incorporate the spirit of your functions into `Get-DbaDatabase` as opposed to general performance of the comparison outside of the applicable dbatools function.

**Comment by wsmelton** [comment]
> So then the case of having two databases where one is named Test and one is TEST on a CS Collation wouldn't be covered?

If we change it back to `-notin` then we cover both, again collation is irrelevant.

**Comment by mattcargile** [comment]
> > So then the case of having two databases where one is named Test and one is TEST on a CS Collation wouldn't be covered?
> 
> If we change it back to `-notin` then we cover both, again collation is irrelevant.

Well wouldn't it give inconsistent results between these databases if one was backed up and one wasn't. It would remove both of them from the output when only one of them was backed up.

**Comment by wsmelton** [comment]
> Well wouldn't it give inconsistent results between these databases if one was backed up and one wasn't. It would remove both of them from the output when only one of them was backed up.

You are not going to resolve nor should we be responsible for every possible variation. If a DBA chose to build a SQL Server instance with case-sensitive collation and then chose to create a database as `TEST` and one as `Test`...that is on them and they should have known better. 

I see no justification for adding in overly complex string comparison to something that is a bad practice from the start. (Referencing duplicate database names at different casing)

**Comment by wsmelton** [comment]
If we find more than one database when trying to gather the last backup date we should throw out a warning and not include the data at that point. If we cannot consistently pull a last backup date it should not be provided at all.

We are talking about a single property on the Database SMO object, that we are adding for convenience to try and match the functionality in SSMS. If we cannot do that on a given run because of data inconsistency then we should not include unverified data in the output. The user can always just run `Get-DbaDbBackupHistory` on their on to get the same details (and be much more efficient/performant compared to using `Get-DbaDatabase`).

**Comment by chightow** [comment]
https://github.com/sqlcollaborative/dbatools/pull/7945/commits/53494e30fd3c192836968667b1b100a6f161d6a9

is just the change from cin to In, Added the Collation check, because of @andreasjordan's points about _CS collations. 
thought about why it wasn't giving correct results for _AS collations or  _WI collations 

started playing with getstringcomparer() and it gave the expected results which is why I asked if we wanted to use it.

> > If it is still wrong why are you not submitting a PR to completely fix it?

So I asked how to approach it

just trying to help 

You can roll it back

**Comment by potatoqualitee** [comment]
I always prefer considering all use-cases if possible. If technology such as case sensitivity allows a DBA to create a database named `TEST` and a database named `test`, that is a valid use-case that we can aim to support, especially if we have contributors who are eager to discuss and address the problem. 

While I agree that matching in PowerShell can be a suitable solution, it seems that there is a desire for a more specific, more encompassing solution. If that's possible and there's a willingness to solve this in a way that does not break current functionality, I'd like for us to continue exploring that. This seems like a fun problem to solve.
