### ISSUE TITLE
dbatools.io / github Slack Invite expired

### ISSUE THREAD

**Issue by Andy-VG** [sqlcollaborative/dbatools#8013]
### What error did you receive?

**This link is no longer active**
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

### Steps to Reproduce

Navigate to https://dbatools.io/slack or https://github.com/sqlcollaborative/dbatools/issues/new/choose 

Both refer to Slack invites that are expired.

### Other details or mentions

This was previously resolved in #7264 but presumably the invite is time-limited and needs to be periodically renewed(?)

**Comment by andreasjordan** [comment]
@potatoqualitee - can you have a look?

**Comment by potatoqualitee** [comment]
I updated it just last week, it should be resolved. let me check again.

**Comment by potatoqualitee** [comment]
Okay so it seems in order to make this work (for my reference)

1. The "forever" links only work for 2000 invitees. 
2. Once a link expires, it has to be deactivated
3. Then recreate it
4. Then update 

I'm having issues tho, and still gotta get into Cloudflare. i need 2fa to get in, so it'll be a lil bit. Sorry slack makes this a horrible experience; they aren't interesting in hosting communities and when we set this one up, there weren't any real, corporate network-friendly alternatives.

**Comment by potatoqualitee** [comment]
K should be fixed now! The link will be good for another 2k users, which generally takes about 5 months. I'll keep an eye on it till then.

**Comment by JodanJodan** [comment]
@potatoqualitee The link is inactivate again, could you recreate it?

**Comment by MaxGripe** [comment]
The self-invite link has expired again

**Comment by niphlod** [comment]
ping @potatoqualitee

**Comment by potatoqualitee** [comment]
thank you both 🙇🏼  i have updated it to a new link at https://join.slack.com/t/sqlcommunity/shared_invite/zt-2js52bqu9-uEMyR0_j~eKlGyqQfz_9yw
