### ISSUE TITLE
Get-DbaTcpPort Clarify SQL Server / Computer Name

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbatools#803]
﻿### Is this a *feature* OR *bug*:
Bug

### System Details
When running function against a server name that has SQL running on custom port you have to put the port as part of the server name you are checking.

- Operating system name and version:
Windows 2012 R2
- Output from `$PSVersionTable`:
Name                           Value                                                                                                                                                                                        
----                           -----                                                                                                                                                                                        
PSVersion                      5.0.10586.117                                                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                      
BuildVersion                   10.0.10586.117                                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                                          
SerializationVersion           1.1.0.1 
```
Evaluate $PSVersionTable in PowerShell and paste the output here
```

- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```0.8.904

- SQL Server version for source/target
SQL 2012 source 
SQL 2016 target

### Steps to Reproduce
Get-DbaTcpPort -SqlServer Servername -Detailed- fails
Get-DbaTcpPort -SqlServer 'Servername,Port' -Detailed - succeeds, but we already know the port with this


### Action Results



### Expected Results
Expect to get the port of a server since you might not know it

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by gbargsley** [comment]
@PowerDBAKlaas, @ctrlbold  wanted me to post this bug about an issue we see.  She tried to troubleshoot but we still could not get a good result.

**Comment by ctrlbold** [comment]
Oh, sorry. For this one, I wanted @PowerDBAKlaas to help with the direction of using SqlServer vs ComputerName for this command.

**Comment by PowerDBAKlaas** [comment]
I just did some tests with Get-DbaTcpPort:

On a server with 4 instances, I get "WARNING: Can't connect to sql1. Moving on."
But when using -Detailed, I get Port 1433 for 15 IP's on default instance, 1 port 58030 on IP 0.0.0.0 and 14 times Port 0 for one named instance, 14 times Port 0 for another named instance, and nothing for a sqlexpress instance.

On a server with only a sqlexpress instance, I get "WARNING: Can't connect to sql1. Moving on." when submitting only the computername to -SqlServer, while I get 1 Port 62680 and 8 times Port 0 when I use -Detailed.

I believe I get the Ports for the non default instances on those computers because the Browser Service is running, and I am local admin.
If SQL Server is running on a non standard port as a security measure, it would be absurd if anyone could just find that port anyway. When connecting as SQL user (even sa, or a privileged sql user) who is not local admin, the user has to know the port to use and shouldn't be able to detect it if he doesn't.

Being local admin I think it is preferred to enter at Computer level, because by querying the ComputerManagement namespace, the user gets the ports for all instances on the computer. When connecting to SQL instance, I think the port will only be returned when it is not needed (because Browser service 'redirects'), and it will not be returned when it would be needed for a 'computername\instancename;port' type of connection, as @gbargsley experienced.

@ctrlbold , that would also make clear we need a -ComputerName parameter.

Anyway, the logic where a port isn't returned when we don't need -Detailed while it is available, should be improved.

**Comment by potatoqualitee** [comment]
![image](https://user-images.githubusercontent.com/8278033/28501967-54dc1ae6-6fe8-11e7-8a42-a8312565559e.png)
