### ISSUE TITLE
Read-DbaTransactionLog

### ISSUE THREAD

**Issue by ctrlbold** [sqlcollaborative/dbatools#903]
Command based off this bombass article: http://www.sqlserverlogexplorer.com/reading-sql-server-transaction-logs

**Comment by Stuart-Moore** [comment]
Goes off to recycle another old presentation.

On 3 Mar 2017 6:33 p.m., "Chrissy LeMaire" <notifications@github.com> wrote:

Command based off this bombass article: http://www.sqlserverlogexplorer.com/
reading-sql-server-transaction-logs

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sqlcollaborative/dbatools/issues/903>, or mute the
thread

**Comment by ctrlbold** [comment]
Ohh, you got this already?

**Comment by Stuart-Moore** [comment]
Not in posh,  but did it with t-sql a few years ago

**Comment by ctrlbold** [comment]
Yep, this is just some embedded T-SQL 💃

**Comment by Stuart-Moore** [comment]
What are you thinking we should do with the data? Just dump it into an internal table or pass it back as a PS object for analysis? Bring it back to PS may make adding some search features easier as we can then do multiple passes over the data with only one read from the server. So we'd end up with a suite of functions (read, analyse, find, etc)

And this is one function that should enforce 1 db at a time. Scanning all the tlogs is going to be a massive perf hit on a server. Probably also want to look at doing a check on the size of the live t-log before diving in. Could be generating a lot of IO pulling a couple of Gb back through.

And do you want fn_dump_dblog functionality including? This lets you parse old t-log backups in the same way, just 64 parameters rather than 2 :)

though there is a  problem with fn_dump_dblog :

> Edit 8/15/13: Beware – Jonathan just found out from a customer system that uses this extensively that every time fn_dump_dblog is called, it creates a new hidden SQLOS scheduler and up to three threads, which will not go away (and will not be reused) until a server restart. It’s a bug that the SQL team is going to fix now we’ve alerted them to it. Use with caution.
> 
> Edit 5/15/15: It’s fixed in SQL Server 2012 SP2+ and SQL Server 2014. The fix won’t be backported any earlier.
> 

https://www.sqlskills.com/blogs/paul/using-fn_dblog-fn_dump_dblog-and-restoring-with-stopbeforemark-to-an-lsn/ 

which could cause people issues if they're not patched up, think we should have a warning if we catch they're on a 'buggy' version

**Comment by ctrlbold** [comment]
agreed on one at a time.  and also a prompt asking to proceed for unpatched versions. Initially, let's do a read then incorporate more after 1.0 what u think?

**Comment by Stuart-Moore** [comment]
Sounds good. Read is dead dead simple for live log,  so there'll be a PR in for that in a bit.

Do the reading of older log files needs a bit more checking. I'll see if I can get something knocked together, but at least we'll have an initial stab for 1.0
