### ISSUE TITLE
Get-DbaAgentJob fails to write out to data table

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbatools#989]
Writing result out to database table results in an error using the function Get-DbaAgentJob. I use similar commands with many of the dbatools functions but normally together with Get-SqlRegisteredServerName and it works generally.  This works with with for example Get-DbaRunningJob, Test-DbaJobOwner and many more. 

When running the following command: 

`$result = Get-DbaAgentJob -SqlInstance INSTANCENAME  | Out-DbaDataTable 
Write-DbaDataTable -InputObject $result -SqlServer INSTANCENAME -Table SqlManagementRepository.dbo.SqlAgentJobs -AutoCreate -Confirm:$false
`

It results in following error. 

> Exception calling "WriteToServer" with "1" argument(s): "The given value of type Guid from the data source cannot be converted to type varchar of the specified target column."
At line:356 char:4
+             $bulkCopy.WriteToServer($InputObject)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

**Comment by PowerDBAKlaas** [comment]
Actually there is nothing wrong with Get-DbaAgentJob.
We could add a property with the GUID as string, but I don't feel that's the right decision.
@ctrlbold @wsmelton 

@peturgretars you can either change the datatype of your destination column to Uniqueidentifier, or put a Select-Object between Get-AgentJob and Write-DataTable to cast the Guid to a string, which will be imported into a varchar().

In the near future it may be necessary to do the same for existing functions, since we have some that are now returning PSCustomObjects (containing strings and numbers), but will return the original objects when we rewrite them.

**Comment by peturgretars** [comment]
@PowerDBAKlaas 
Thanks for this update. It works when selecting columns.
